VSSS-INF: jsonSaveManager Class Reference
jsonSaveManager Class Reference
#include <jsonSaveManager.h>
Public Member Functions
jsonSaveManager (V4LInterface *interf)
Constructor for JSON Save Manager. "explicit" means that all params types must be satisfied.
void load (std::string file_path="config/quicksave.json")
Loads all avaliable configurations in the given .json file.
void save (std::string file_path="config/quicksave.json")
Saves all volatile data set in the interface to a given .json file.
void save_robots ()
Save robot configurations from interface to our JSON object.
void load_robots ()
Load robot configurations from our JSON object to the interface.
void save_camera ()
Save camera configurations from interface to our JSON object.
void load_camera ()
Load camera configurations from our JSON object to the interface.
void config_matrix (json &mat_config, int(&mat)[4][2], bool save)
Configures vision's warp matrix to match it's defaults.
int read_configs_from_file (std::string file_path="config/quicksave.json")
Read a given file and place it's data in our JSON object.
void write_configs_to_file (std::string file_path="config/quicksave.json")
Actually writes our JSON object in the given file.
Private Member Functions
bool exists (json &config, std::string name)
Auxiliar function that checks if a given configuration is already set in our JSON object.
Private Attributes
json configs
Global JSON object that keeps data between save/load calls.
V4LInterface * interface
Pointer to main interface object. Used to get/set it's values at runtime.
Detailed Description
Definition at line 14 of file jsonSaveManager.h.
Constructor & Destructor Documentation
jsonSaveManager()
jsonSaveManager::jsonSaveManager (V4LInterface * interf) inline explicit
Constructor for JSON Save Manager. "explicit" means that all params types must be satisfied.
Parameters
interf Main interface object.
Definition at line 42 of file jsonSaveManager.h.
 :interface(interf){};
Member Function Documentation
config_matrix()
void jsonSaveManager::config_matrix (json & mat_config, int(&) mat[4][2], bool save)
Configures vision's warp matrix to match it's defaults.
Parameters
mat_config Ready-to-save warp matrix.
mat Ready-to-load warp matrix.
save The direction of the conversion. "true" converts data from 'mat' to 'mat_config'; false converts data from 'mat_config' to 'mat'.
Definition at line 154 of file jsonSaveManager.cpp.
Referenced by load_camera(), and save_camera().
{
     for (int i = 0; i < 4; ++i) {
         for (int j = 0; j < 2; ++j) {
             string pos_string = "["+std::to_string(i)+"]["+std::to_string(j)+"]";
             if(save) mat_config[pos_string] = mat[i][j];
             else mat[i][j] = mat_config[pos_string];
         }
     }
 }
exists()
bool jsonSaveManager::exists (json & config, std::string name) private
Auxiliar function that checks if a given configuration is already set in our JSON object.
Parameters
config Our JSON configuration object.
name Name of the given configuration.
Returns
bool True if the configuration exists; false otherwise.
Definition at line 188 of file jsonSaveManager.cpp.
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::end(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::find().
Referenced by load_camera(), and load_robots().
{
     return (config.find(name) != config.end());
 }
load()
void jsonSaveManager::load (std::string file_path = "config/quicksave.json")
Loads all avaliable configurations in the given .json file.
Parameters
file_path Path to the .json file.
Definition at line 5 of file jsonSaveManager.cpp.
References debug_warning, load_camera(), load_robots(), and read_configs_from_file().
Referenced by VSSS_GUI::V4LInterface::__event_bt_load_clicked(), VSSS_GUI::V4LInterface::__event_bt_quick_load_clicked(), and VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked().
{
     int error = read_configs_from_file(file_path);
     if(error == 1) debug_warning("File " + file_path + " not found");
     else if(error == 2) debug_warning(file_path + " is not a valid JSON file");
     if(!error){
         load_camera();
         load_robots();
     }
 }
load_camera()
void jsonSaveManager::load_camera ()
Load camera configurations from our JSON object to the interface.
Definition at line 102 of file jsonSaveManager.cpp.
References ImageView::adjust_mat, ImageView::adjust_rdy, VSSS_GUI::V4LInterface::camera_card, config_matrix(), configs, VSSS_GUI::V4LInterface::ctrl_list_default, exists(), VSSS_GUI::V4LInterface::imageView, interface, VSSS_GUI::V4LInterface::offsetL, VSSS_GUI::V4LInterface::offsetR, VSSS_GUI::__ctrl_holder::qctrl, v4lcap::set_control(), Vision::setAmin(), Vision::setBlur(), Vision::setDilate(), Vision::setErode(), Vision::setHue(), Vision::setSaturation(), Vision::setValue(), VSSS_GUI::V4LInterface::vcap, VisionGUI::vision, VSSS_GUI::V4LInterface::visionGUI, ImageView::warp_mat, and VSSS_GUI::V4LInterface::warped.
Referenced by load().
{
     if(!exists(configs["Cameras"], interface->camera_card)) return;
     json& camera_config = configs["Cameras"][interface->camera_card];
     string hsv_calibs[4] = {"Main", "Green", "Ball", "Opp."};
     for (int i = 0; i < 4; ++i) {
         json& hsv = camera_config["HSV Calibration"][hsv_calibs[i]];
         Vision& vision = *(interface->visionGUI.vision);
         if(exists(hsv, "hue_min")) vision.setHue(i, 0, hsv["hue_min"]);
         if(exists(hsv, "hue_max")) vision.setHue(i, 1, hsv["hue_max"]);
         if(exists(hsv, "saturation_min")) vision.setSaturation(i, 0, hsv["saturation_min"]);
         if(exists(hsv, "saturation_max")) vision.setSaturation(i, 1, hsv["saturation_max"]);
         if(exists(hsv, "value_min")) vision.setValue(i, 0, hsv["value_min"]);
         if(exists(hsv, "value_max")) vision.setValue(i, 1, hsv["value_max"]);
         if(exists(hsv, "dilate")) vision.setDilate(i, hsv["dilate"]);
         if(exists(hsv, "erode")) vision.setErode(i, hsv["erode"]);
         if(exists(hsv, "blur")) vision.setBlur(i, hsv["blur"]);
         if(exists(hsv, "amin")) vision.setAmin(i, hsv["amin"]);
     }
     if(exists(camera_config, "warp_mat")){
         json& warp_mat = camera_config["warp_mat"];
         config_matrix(warp_mat, interface->imageView.warp_mat, false);
         interface->warped = true;
     } else {
         interface->warped = false;
     }
     if(exists(camera_config, "adjust_mat")) {
         json &adjust_mat = camera_config["adjust_mat"];
         config_matrix(adjust_mat, interface->imageView.adjust_mat, false);
         interface->imageView.adjust_rdy = true;
     } else {
         interface->imageView.adjust_rdy= false;
     }
     if(exists(camera_config, "offsetL")) interface->offsetL = camera_config["offsetL"];
     if(exists(camera_config, "offsetR")) interface->offsetR = camera_config["offsetR"];
     if(exists(camera_config, "Camera Properties")){
         json& properties_config = camera_config["Camera Properties"];
         for(ControlHolder& ctrl : interface->ctrl_list_default) {
             string name = string((char *) ctrl.qctrl.name);
             if(exists(properties_config, name)){
                 int value = properties_config[name];
                 interface->vcap.set_control(ctrl.qctrl.id, value);
             }
         }
     }
 }
load_robots()
void jsonSaveManager::load_robots ()
Load robot configurations from our JSON object to the interface.
Definition at line 37 of file jsonSaveManager.cpp.
References configs, exists(), interface, VSSS_GUI::V4LInterface::robotGUI, Robots::set_default_velocity(), Robots::set_ID(), Robots::set_role(), Robots::SIZE, RobotGUI::update_ids(), RobotGUI::update_robot_functions(), and RobotGUI::update_speed_sliders().
Referenced by load().
{
     if(!exists(configs, "Robots")) return;
     for (int i = 0; i < Robots::SIZE; ++i) {
         json& robot_config = configs["Robots"]["Robot "+std::to_string(i+1)];
         if(exists(robot_config, "ID")){
             string id = robot_config["ID"];
             // debug_log("setting id: " + id);
             Robots::set_ID(i, id[0]);
         }
         if(exists(robot_config, "role")) {
             Robots::set_role(i, robot_config["role"]);
         }
         if(exists(robot_config, "speed")){
             string tmp_speed = robot_config["speed"];
             Robots::set_default_velocity(i, stof(tmp_speed));
         }
     }
     interface->robotGUI.update_ids();
     interface->robotGUI.update_robot_functions();
     interface->robotGUI.update_speed_sliders();
 }
read_configs_from_file()
int jsonSaveManager::read_configs_from_file (std::string file_path = "config/quicksave.json")
Read a given file and place it's data in our JSON object.
Parameters
file_path Path to the .json file.
Returns
int 0 case load is successful; 1 case file couldn't be opened; 2 case parse error; 3 case unknown error.
Definition at line 164 of file jsonSaveManager.cpp.
References configs.
Referenced by load(), and save().
{
     try {
         std::ifstream file(file_path);
         if(file.is_open()) {
             file >> configs;
             file.close();
         }
         else return 1;
     } catch(std::exception& e) {
         string error = e.what();
         if(error.find("parse_error") != string::npos)
             return 2;
         return 3;
     }
     return 0;
 }
save()
void jsonSaveManager::save (std::string file_path = "config/quicksave.json")
Saves all volatile data set in the interface to a given .json file.
Parameters
file_path Path to the .json file.
Definition at line 17 of file jsonSaveManager.cpp.
References debug_log, debug_warning, read_configs_from_file(), save_camera(), save_robots(), and write_configs_to_file().
Referenced by VSSS_GUI::V4LInterface::__event_bt_quick_save_clicked(), VSSS_GUI::V4LInterface::__event_bt_save_clicked(), and VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked().
{
     int error = read_configs_from_file(file_path);
     if(error == 1) debug_log("Creating " + file_path);
     else if(error == 2) debug_warning(file_path + " is not a valid JSON file, will be overwritten");
     save_camera();
     save_robots();
     write_configs_to_file(file_path);
 }
save_camera()
void jsonSaveManager::save_camera ()
Save camera configurations from interface to our JSON object.
Definition at line 60 of file jsonSaveManager.cpp.
References ImageView::adjust_mat, ImageView::adjust_rdy, VSSS_GUI::V4LInterface::camera_card, config_matrix(), configs, VSSS_GUI::V4LInterface::ctrl_list_default, v4lcap::get_control(), Vision::getAmin(), Vision::getBlur(), Vision::getDilate(), Vision::getErode(), Vision::getHue(), Vision::getSaturation(), Vision::getValue(), VSSS_GUI::V4LInterface::imageView, interface, VSSS_GUI::V4LInterface::offsetL, VSSS_GUI::V4LInterface::offsetR, VSSS_GUI::__ctrl_holder::qctrl, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer >::value(), VSSS_GUI::V4LInterface::vcap, VisionGUI::vision, VSSS_GUI::V4LInterface::visionGUI, ImageView::warp_mat, and VSSS_GUI::V4LInterface::warped.
Referenced by save().
{
     json& camera_config = configs["Cameras"][interface->camera_card];
     string hsv_calibs[4] = {"Main", "Green", "Ball", "Opp."};
     for (int i = 0; i < 4; ++i) {
         json& hsv = camera_config["HSV Calibration"][hsv_calibs[i]];
         Vision& vision = *(interface->visionGUI.vision);
         hsv["hue_min"] = vision.getHue(i, 0);
         hsv["hue_max"] = vision.getHue(i, 1);
         hsv["saturation_min"] = vision.getSaturation(i, 0);
         hsv["saturation_max"] = vision.getSaturation(i, 1);
         hsv["value_min"] = vision.getValue(i, 0);
         hsv["value_max"] = vision.getValue(i, 1);
         hsv["dilate"] = vision.getDilate(i);
         hsv["erode"] = vision.getErode(i);
         hsv["blur"] = vision.getBlur(i);
         hsv["amin"] = vision.getAmin(i);
     }
     if(interface->warped) {
         json &warp_mat = camera_config["warp_mat"];
         config_matrix(warp_mat, interface->imageView.warp_mat, true);
     }
     if(interface->imageView.adjust_rdy) {
         json &adjust_mat = camera_config["adjust_mat"];
         config_matrix(adjust_mat, interface->imageView.adjust_mat, true);
     }
     camera_config["offsetL"] = interface->offsetL;
     camera_config["offsetR"] = interface->offsetR;
     json& properties_config = camera_config["Camera Properties"];
     for(ControlHolder ctrl : interface->ctrl_list_default) {
         v4l2_control control{};
         interface->vcap.get_control(&control, ctrl.qctrl.id);
         string name = string((char *) ctrl.qctrl.name);
         properties_config[name] = control.value;
     }
 }
save_robots()
void jsonSaveManager::save_robots ()
Save robot configurations from interface to our JSON object.
Definition at line 27 of file jsonSaveManager.cpp.
References configs, Robots::get_default_velocity(), Robots::get_ID(), Robots::get_role(), and Robots::SIZE.
Referenced by save().
{
     for (int i = 0; i < Robots::SIZE; ++i) {
         json& robot_config = configs["Robots"]["Robot "+std::to_string(i+1)];
         // debug_warning(string(1, Robots::get_ID(i)));
         robot_config["ID"] = string(1, Robots::get_ID(i));
         robot_config["role"] = Robots::get_role(i);
         robot_config["speed"] = to_string(round(Robots::get_default_velocity(i)*1000)/1000); // salvar como string pois double zoa as casas decimais
     }
 }
write_configs_to_file()
void jsonSaveManager::write_configs_to_file (std::string file_path = "config/quicksave.json")
Actually writes our JSON object in the given file.
Parameters
file_path Path to the .json file.
Definition at line 181 of file jsonSaveManager.cpp.
References configs, and debug_success.
Referenced by save().
{
     std::ofstream file(file_path);
     file << std::setw(4) << configs << endl;
     file.close();
     debug_success("Config file written.");
 }
Field Documentation
configs
json jsonSaveManager::configs private
Global JSON object that keeps data between save/load calls.
Definition at line 20 of file jsonSaveManager.h.
Referenced by load_camera(), load_robots(), read_configs_from_file(), save_camera(), save_robots(), and write_configs_to_file().
interface
V4LInterface* jsonSaveManager::interface private
Pointer to main interface object. Used to get/set it's values at runtime.
Definition at line 25 of file jsonSaveManager.h.
Referenced by load_camera(), load_robots(), and save_camera().
The documentation for this class was generated from the following files:
src/aux/jsonSaveManager.h
src/aux/jsonSaveManager.cpp