VSSS-INF: StrategyGUI Class Reference
StrategyGUI Class Reference
#include <strategyGUI.hpp>
Data Structures
class ModelColumns
Public Member Functions
StrategyGUI ()
Constructor of a StrategyGUI object.
void configureTestFrame ()
Inicialization of labels and values from Test Parameters frame.
void createFormationFrame ()
Formation frame creator.
void createTransitionsFrame ()
Transitions frame creator.
~StrategyGUI ()
Destructor of a StrategyGUI object.
Data Fields
ModelColumns strategyColumns
Gtk::Frame menu_fm
Gtk::Frame info_text_fm
Gtk::Frame info_img_fm
Gtk::TreeView m_TreeView
Glib::RefPtr< Gtk::ListStore > m_refTreeModel
Gtk::VBox menu_vbox
Gtk::HBox menu_hbox [2]
Gtk::Image strategy_img
Gtk::Button select_button
Gtk::ScrolledWindow m_ScrolledWindow
Gtk::TextView strategy_description_view
Glib::RefPtr< Gtk::TextBuffer > strategy_description_text
Strategy strategy
bool updating_formation_flag = false
Gtk::Frame formation_fm
bool formation_flag = false
bool update_interface_flag = false
Gtk::Grid formation_grid
Gtk::Button bt_loadFormation
Gtk::Button bt_deleteFormation
Gtk::ToggleButton bt_createFormation
Gtk::Button bt_saveFormation
Gtk::ComboBoxText formation_box
Gtk::Entry formation_name_entry
cv::Point formation_positions [3]
float formation_orientations [3]
Gtk::Frame behavior_fm
Gtk::Grid behavior_grid
Gtk::ToggleButton bt_penaltyBehavior
Gtk::Frame transitions_fm
Gtk::Grid transitions_grid
Gtk::CheckButton transitions_check
Private Member Functions
char * unconstant_char (const char *c_str)
Converts a constant string to an inconstant one.
void _event_loadFormation_bt_clicked ()
Event triggered when a formation is selected and 'load' button is clicked.
void _event_deleteFormation_bt_clicked ()
Event triggered when the delete button is clicked.
void _event_saveFormation_bt_clicked ()
Event triggered when the save button is clicked.
void _event_createFormation_bt_clicked ()
Event triggered when the 'create formation' button is clicked.
void _event_formation_box_changed ()
Event triggered when a formation (or none) is selected.
void _event_set_penalty_behavior ()
Event triggered when the 'penalty' button is clicked.
void _event_transitions_checkbox_signal_clicked ()
Switches Strategy's full_transition_enabled flag value.
void loadSavedFormations ()
Loads formation.txt file and appends the saved formations on the checkbox.
Detailed Description
Definition at line 15 of file strategyGUI.hpp.
Constructor & Destructor Documentation
StrategyGUI()
StrategyGUI::StrategyGUI ()
Constructor of a StrategyGUI object.
Definition at line 3 of file strategyGUI.cpp.
References configureTestFrame(), createFormationFrame(), createTransitionsFrame(), strategy, and Strategy::testFrame.
{
     createFormationFrame();
     createTransitionsFrame();
     pack_start(strategy.testFrame, false, true, 5);
     configureTestFrame();
 }
~StrategyGUI()
StrategyGUI::~StrategyGUI ()
Destructor of a StrategyGUI object.
Definition at line 10 of file strategyGUI.cpp.
 {}
Member Function Documentation
_event_createFormation_bt_clicked()
void StrategyGUI::_event_createFormation_bt_clicked () private
Event triggered when the 'create formation' button is clicked.
Makes the text field and 'save' button available
Definition at line 246 of file strategyGUI.cpp.
References bt_createFormation, bt_saveFormation, formation_flag, and formation_name_entry.
Referenced by createFormationFrame().
{
     formation_flag = !formation_flag;
     bt_createFormation.set_active(!formation_flag);
     bt_saveFormation.set_sensitive(formation_flag);
     formation_name_entry.set_sensitive(formation_flag);
 }
_event_deleteFormation_bt_clicked()
void StrategyGUI::_event_deleteFormation_bt_clicked () private
Event triggered when the delete button is clicked.
Deletes the selected formation from the formations file (config/formation.txt)
Definition at line 89 of file strategyGUI.cpp.
References bt_createFormation, bt_saveFormation, formation_box, formation_flag, formation_name_entry, and loadSavedFormations().
Referenced by createFormationFrame().
{
     std::ofstream tmpTxtFile;
     std::ifstream txtFile;
     std::string formationName;
     std::string line;
     txtFile.open("config/formation.txt");
     tmpTxtFile.open("config/tmp_formation.txt");
     if(txtFile.is_open() && tmpTxtFile.is_open()) {
         getline(txtFile, line);
         // formações salvas
         int n = atoi(line.c_str());
         // se só tem uma formação salva, apaga o arquivo
         if(n-1 == 0) {
             std::cout << "There was only one formation saved. Formation file deleted.\n";
             txtFile.close();
             tmpTxtFile.close();
             // desabilita os botões
             formation_flag = false;
             bt_createFormation.set_active(false);
             bt_saveFormation.set_sensitive(false);
             formation_name_entry.set_sensitive(false);
             // salva as alterações
             txtFile.close();
             tmpTxtFile.close();
             // remove os arquivos
             system("rm -rf config/formation.txt");
             system("rm -rf config/tmp_formation.txt");
             // atualiza a interface
             loadSavedFormations();
             return;
         }
         // decrementa o número de formações no novo arquivo
         tmpTxtFile << (n-1) << std::endl;
         // para cada prox linha
         for(int i = 0; i < n; i++) {
             // move o cursor enquanto não é a linha que eu quero e copia os dados para o novo arquivo
             getline(txtFile, line);
             // ignora a linha selecionada
             if(i == formation_box.get_active_row_number() - 1)
                 continue;
             tmpTxtFile << line << std::endl;
         }
         // desabilita os botões
         formation_flag = false;
         bt_createFormation.set_active(false);
         bt_saveFormation.set_sensitive(false);
         formation_name_entry.set_sensitive(false);
         // salva as alterações
         txtFile.close();
         tmpTxtFile.close();
         // agora as alterações não são mais temporárias
         system("rm -rf config/formation.txt");
         system("mv config/tmp_formation.txt config/formation.txt");
         // atualiza a interface
         loadSavedFormations();
     } else std::cout << "Could not delete formation.\n";
 }
_event_formation_box_changed()
void StrategyGUI::_event_formation_box_changed () private
Event triggered when a formation (or none) is selected.
Checks if a formation is selected and, case positive, makes the 'load' and 'save' buttons available
Definition at line 254 of file strategyGUI.cpp.
References bt_deleteFormation, bt_loadFormation, and formation_box.
Referenced by createFormationFrame().
{
     if(formation_box.get_active_row_number() == 0) {
         bt_loadFormation.set_sensitive(false);
         bt_deleteFormation.set_sensitive(false);
         return;
     }
     bt_loadFormation.set_sensitive(true);
     bt_deleteFormation.set_sensitive(true);
 }
_event_loadFormation_bt_clicked()
void StrategyGUI::_event_loadFormation_bt_clicked () private
Event triggered when a formation is selected and 'load' button is clicked.
Loads the saved formations file and changes robot's position flags The formation will be updated on camcap
Definition at line 26 of file strategyGUI.cpp.
References bt_deleteFormation, bt_loadFormation, formation_box, formation_orientations, formation_positions, update_interface_flag, and updating_formation_flag.
Referenced by createFormationFrame().
{
     std::ifstream txtFile;
     std::string line;
     char * tmp_substr;
     if(formation_box.get_active_row_number() == 0) {
         bt_loadFormation.set_sensitive(false);
         bt_deleteFormation.set_sensitive(false);
         return;
     }
     txtFile.open("config/formation.txt");
     if(txtFile.is_open()) {
         getline(txtFile, line);
         // formações salvas
         int n = atoi(line.c_str());
         // para cada prox linha
         for(int i = 0; i < n; i++) {
             // move o cursor enquanto não é a linha que eu quero
             getline(txtFile, line);
             if(i == formation_box.get_active_row_number() - 1) {
                 std::vector<std::string> strs;
                 boost::split(strs, line, boost::is_any_of(" "));
                 // pega robot 1 x position value
                 formation_positions[0].x = atof(strs.at(1).c_str());
                 // pega robot 1 y position value
                 formation_positions[0].y = atof(strs.at(2).c_str());
                 // pega robot 1 theta position value
                 formation_orientations[0] = atof(strs.at(3).c_str());
                 // pega robot 2 x position value
                 formation_positions[1].x = atof(strs.at(4).c_str());
                 // pega robot 2 y position value
                 formation_positions[1].y = atof(strs.at(5).c_str());
                 // pega robot 2 theta position value
                 formation_orientations[1] = atof(strs.at(6).c_str());
                 // pega robot 3 x position value
                 formation_positions[2].x = atof(strs.at(7).c_str());
                 // pega robot 3 y position value
                 formation_positions[2].y = atof(strs.at(8).c_str());
                 // pega robot 3 theta position value
                 formation_orientations[2] = atof(strs.at(9).c_str());
             }
         }
         // atualiza interface
         update_interface_flag = true;
         std::cout << "Begin positioning...\n";
         // valores disponíveis: formation_positions e formation_orientations
         // isso é atualizado no camcap
         // manda atualizar
         updating_formation_flag = true;
         txtFile.close();
     } else {
         // não existem formações salvas
         std::cout << "You removed the file before I could read it.\n";
     }
 }
_event_saveFormation_bt_clicked()
void StrategyGUI::_event_saveFormation_bt_clicked () private
Event triggered when the save button is clicked.
Adds the formation in the formations file (config/formation.txt)
Definition at line 152 of file strategyGUI.cpp.
References bt_createFormation, bt_saveFormation, formation_flag, formation_name_entry, formation_orientations, formation_positions, and loadSavedFormations().
Referenced by createFormationFrame().
{
     std::ofstream tmpTxtFile;
     std::ifstream txtFile;
     std::string formationName;
     std::string line;
     if(!formation_flag) {
         std::cout << "Synchronicity error. Flag should be set.\n";
         return;
     }
     txtFile.open("config/formation.txt");
     tmpTxtFile.open("config/tmp_formation.txt");
     // verifica se o nome foi preenchido
     formationName = formation_name_entry.get_text();
     if(formationName == "") {
         std::cout << "Your formation needs to have a name.";
         return;
     }
     // coloca a string no formato certo para ser salva no arquivo
     for(int i = 0; formationName[i] != '\0'; i++) {
         if(!(formationName[i] >= 'a' && formationName[i] <= 'z') && !(formationName[i] >= 'A' && formationName[i] <= 'Z')) {
             formationName[i] = '_';
         }
     }
     if (txtFile.is_open() && tmpTxtFile.is_open()) {
         getline(txtFile, line);
         // formações salvas
         int n = atoi(line.c_str());
         // incrementa o número de formações no novo arquivo
         tmpTxtFile << (n+1) << std::endl;
         // para cada prox linha
         for(int i = 0; i < n; i++) {
             // move o cursor enquanto não é a linha que eu quero e copia os dados para o novo arquivo
             getline(txtFile, line);
             tmpTxtFile << line << std::endl;
         }
         // grava os novos dados no arquivo
         tmpTxtFile << formationName << " ";
         for(int i = 0; i < 3; i++) {
             // não importa deixar o " " no final pois na leitura ele é ignorado
             tmpTxtFile << formation_positions[i].x << " " << formation_positions[i].y << " " << formation_orientations[i] << " ";
         }
         tmpTxtFile << std::endl;
         // desabilita os botões
         formation_flag = false;
         bt_createFormation.set_active(false);
         bt_saveFormation.set_sensitive(false);
         formation_name_entry.set_sensitive(false);
         // salva as alterações
         txtFile.close();
         tmpTxtFile.close();
         // agora as alterações não são mais temporárias
         system("rm -rf config/formation.txt");
         system("mv config/tmp_formation.txt config/formation.txt");
         // atualiza a interface
         loadSavedFormations();
     } else if(tmpTxtFile.is_open()) { // primeira formação salva
         tmpTxtFile << 1 << std::endl;
         // grava os novos dados no arquivo
         tmpTxtFile << formationName << " ";
         for(int i = 0; i < 3; i++) {
             // não importa deixar o " " no final pois na leitura ele é ignorado
             tmpTxtFile << formation_positions[i].x << " " << formation_positions[i].y << " " << formation_orientations[i] << " ";
         }
         tmpTxtFile << std::endl;
         // desabilita os botões
         formation_flag = false;
         bt_createFormation.set_active(false);
         bt_saveFormation.set_sensitive(false);
         formation_name_entry.set_sensitive(false);
         // salva as alterações
         tmpTxtFile.close();
         // agora as alterações não são mais temporárias
         system("mv config/tmp_formation.txt config/formation.txt");
         // atualiza a interface
         loadSavedFormations();
     } else std::cout << "Could not save formation.\n";
 }
_event_set_penalty_behavior()
void StrategyGUI::_event_set_penalty_behavior () private
Event triggered when the 'penalty' button is clicked.
Not implemented yet
_event_transitions_checkbox_signal_clicked()
void StrategyGUI::_event_transitions_checkbox_signal_clicked () private
Switches Strategy's full_transition_enabled flag value.
Definition at line 264 of file strategyGUI.cpp.
References debug_log, strategy, and Strategy::transitions_enabled.
Referenced by createTransitionsFrame().
{
     strategy.transitions_enabled = !strategy.transitions_enabled;
     debug_log("Transitions: " + to_string(strategy.transitions_enabled));
 }
configureTestFrame()
void StrategyGUI::configureTestFrame ()
Inicialization of labels and values from Test Parameters frame.
Definition at line 317 of file strategyGUI.cpp.
References TestFrame::configureHScale(), TestFrame::setLabel(), strategy, and Strategy::testFrame.
Referenced by StrategyGUI().
{
     std::string labels[5] = {"Goalie Line", "Goalie Offset", "Name 3", "Name 4", "Name 5"};
     double min[5] = {0, 0, 0, 0, 0};
     double max[5] = {160, 100, 100, 100, 100};
     double currentValue[5] = {60, 15, 20, 30, 40};
     double digits[5] = {0, 0, 0, 0, 0};
     double steps[5] = {5, 1, 1, 1, 1};
     for (int i = 0; i < 5; i++) {
         strategy.testFrame.setLabel(i, labels[i]);
         strategy.testFrame.configureHScale(i, currentValue[i], min[i], max[i], digits[i], steps[i]);
     }
 }
createFormationFrame()
void StrategyGUI::createFormationFrame ()
Formation frame creator.
Definition at line 331 of file strategyGUI.cpp.
References _event_createFormation_bt_clicked(), _event_deleteFormation_bt_clicked(), _event_formation_box_changed(), _event_loadFormation_bt_clicked(), _event_saveFormation_bt_clicked(), bt_createFormation, bt_deleteFormation, bt_loadFormation, bt_saveFormation, formation_box, formation_fm, formation_grid, formation_name_entry, and loadSavedFormations().
Referenced by StrategyGUI().
{
     pack_start(formation_fm, false, true, 5);
     formation_fm.add(formation_grid);
     formation_fm.set_label("Formation");
     formation_grid.set_halign(Gtk::ALIGN_CENTER);
     bt_createFormation.set_label("Create Formation");
     loadSavedFormations();
     bt_loadFormation.set_label("Load");
     bt_deleteFormation.set_label("Delete");
     formation_name_entry.set_max_length(30);
     formation_name_entry.set_width_chars(30);
     formation_name_entry.set_text(Glib::ustring::format("Formation_name"));
     bt_saveFormation.set_label("Save");
     formation_grid.set_border_width(10);
     formation_grid.set_column_spacing(5);
     formation_grid.attach(bt_createFormation, 0, 0, 1, 1);
     formation_grid.attach(formation_box, 0, 1, 1, 1);
     formation_grid.attach(bt_loadFormation, 1, 1, 1, 1);
     formation_grid.attach(bt_deleteFormation, 2, 1, 1, 1);
     formation_grid.attach(formation_name_entry, 0, 2, 1, 1);
     formation_grid.attach(bt_saveFormation, 1, 2, 1, 1);
     formation_box.set_sensitive(false); // habilita quando der start
     bt_createFormation.set_sensitive(false); // habilita quando der start
     bt_loadFormation.set_sensitive(false); // habilita só quando selecionar uma formação
     bt_deleteFormation.set_sensitive(false); // habilita só quando selecionar uma formação
     bt_saveFormation.set_sensitive(false); // habilita só quando o createFormation está ativado
     formation_name_entry.set_sensitive(false); // habilita só quando o createFormation está ativado
     formation_box.signal_changed().connect(sigc::mem_fun(*this, &StrategyGUI::_event_formation_box_changed));
     bt_createFormation.signal_pressed().connect(sigc::mem_fun(*this, &StrategyGUI::_event_createFormation_bt_clicked));
     bt_saveFormation.signal_clicked().connect(sigc::mem_fun(*this, &StrategyGUI::_event_saveFormation_bt_clicked));
     bt_loadFormation.signal_clicked().connect(sigc::mem_fun(*this, &StrategyGUI::_event_loadFormation_bt_clicked));
     bt_deleteFormation.signal_clicked().connect(sigc::mem_fun(*this, &StrategyGUI::_event_deleteFormation_bt_clicked));
 }
createTransitionsFrame()
void StrategyGUI::createTransitionsFrame ()
Transitions frame creator.
Definition at line 299 of file strategyGUI.cpp.
References _event_transitions_checkbox_signal_clicked(), transitions_check, transitions_fm, and transitions_grid.
Referenced by StrategyGUI().
{
     pack_start(transitions_fm, false, true, 5);
     transitions_fm.set_label("Transitions");
     transitions_fm.add(transitions_grid);
     transitions_grid.set_border_width(10);
     transitions_grid.set_column_spacing(5);
     transitions_grid.set_halign(Gtk::ALIGN_CENTER);
     transitions_grid.attach(transitions_check, 0, 0, 1, 1);
     transitions_check.set_label("Enable Transitions");
     transitions_check.set_active();
     transitions_check.signal_clicked().connect(sigc::mem_fun(*this, &StrategyGUI::_event_transitions_checkbox_signal_clicked));
 }
loadSavedFormations()
void StrategyGUI::loadSavedFormations () private
Loads formation.txt file and appends the saved formations on the checkbox.
File structure: Number of formations formation_name r1x r1y r1o r2x r2y r2o r3x r3y r3o
Definition at line 269 of file strategyGUI.cpp.
References formation_box, and unconstant_char().
Referenced by _event_deleteFormation_bt_clicked(), _event_saveFormation_bt_clicked(), and createFormationFrame().
{
     std::ifstream txtFile;
     std::string line;
     txtFile.open("config/formation.txt");
     formation_box.remove_all();
     formation_box.append("None");
     if(txtFile.is_open()) {
         getline(txtFile, line);
         // formações salvas
         int n = atoi(line.c_str());
         // para cada prox linha
         for(int i = 0; i < n; i++) {
             getline(txtFile, line);
             // pega o nome da formação
             formation_box.append(strtok(unconstant_char(line.c_str()), " "));
         }
         txtFile.close();
     } else {
         // não existem formações salvas
         // std::cout << "There's no saved robot formations.\n";
     }
     // seleciona o None como padrão
     formation_box.set_active(0);
 }
unconstant_char()
char * StrategyGUI::unconstant_char (const char * c_str) private
Converts a constant string to an inconstant one.
Parameters
c_str Constant string to be converted
Returns
char* Not-const converted string
Definition at line 12 of file strategyGUI.cpp.
Referenced by loadSavedFormations().
{
     char * uc;
     int len;
     // tamanho da string
     for(len = 0; c_str[len] != '\0'; len++);
     // aloca nova string
     uc = (char *) malloc(len*sizeof(char));
     // copia dados
     for(int i = 0; i < len; i++)
         uc[i] = c_str[i];
     return uc;
 }
Field Documentation
behavior_fm
Gtk::Frame StrategyGUI::behavior_fm
Definition at line 124 of file strategyGUI.hpp.
behavior_grid
Gtk::Grid StrategyGUI::behavior_grid
Definition at line 125 of file strategyGUI.hpp.
bt_createFormation
Gtk::ToggleButton StrategyGUI::bt_createFormation
Definition at line 117 of file strategyGUI.hpp.
Referenced by _event_createFormation_bt_clicked(), _event_deleteFormation_bt_clicked(), _event_saveFormation_bt_clicked(), createFormationFrame(), and CamCap::start_signal().
bt_deleteFormation
Gtk::Button StrategyGUI::bt_deleteFormation
Definition at line 116 of file strategyGUI.hpp.
Referenced by _event_formation_box_changed(), _event_loadFormation_bt_clicked(), and createFormationFrame().
bt_loadFormation
Gtk::Button StrategyGUI::bt_loadFormation
Definition at line 115 of file strategyGUI.hpp.
Referenced by _event_formation_box_changed(), _event_loadFormation_bt_clicked(), and createFormationFrame().
bt_penaltyBehavior
Gtk::ToggleButton StrategyGUI::bt_penaltyBehavior
Definition at line 126 of file strategyGUI.hpp.
bt_saveFormation
Gtk::Button StrategyGUI::bt_saveFormation
Definition at line 118 of file strategyGUI.hpp.
Referenced by _event_createFormation_bt_clicked(), _event_deleteFormation_bt_clicked(), _event_saveFormation_bt_clicked(), and createFormationFrame().
formation_box
Gtk::ComboBoxText StrategyGUI::formation_box
Definition at line 119 of file strategyGUI.hpp.
Referenced by _event_deleteFormation_bt_clicked(), _event_formation_box_changed(), _event_loadFormation_bt_clicked(), createFormationFrame(), loadSavedFormations(), and CamCap::start_signal().
formation_flag
bool StrategyGUI::formation_flag = false
Definition at line 112 of file strategyGUI.hpp.
Referenced by _event_createFormation_bt_clicked(), _event_deleteFormation_bt_clicked(), _event_saveFormation_bt_clicked(), and CamCap::capture_and_show().
formation_fm
Gtk::Frame StrategyGUI::formation_fm
Definition at line 111 of file strategyGUI.hpp.
Referenced by createFormationFrame().
formation_grid
Gtk::Grid StrategyGUI::formation_grid
Definition at line 114 of file strategyGUI.hpp.
Referenced by createFormationFrame().
formation_name_entry
Gtk::Entry StrategyGUI::formation_name_entry
Definition at line 120 of file strategyGUI.hpp.
Referenced by _event_createFormation_bt_clicked(), _event_deleteFormation_bt_clicked(), _event_saveFormation_bt_clicked(), and createFormationFrame().
formation_orientations
float StrategyGUI::formation_orientations[3]
Updated only if the flag is activated
Definition at line 122 of file strategyGUI.hpp.
Referenced by _event_loadFormation_bt_clicked(), _event_saveFormation_bt_clicked(), CamCap::formation_creation(), and CamCap::update_formation_information().
formation_positions
cv::Point StrategyGUI::formation_positions[3]
Updated only if the flag is activated
Definition at line 121 of file strategyGUI.hpp.
Referenced by _event_loadFormation_bt_clicked(), _event_saveFormation_bt_clicked(), CamCap::formation_creation(), and CamCap::update_formation_information().
info_img_fm
Gtk::Frame StrategyGUI::info_img_fm
Definition at line 92 of file strategyGUI.hpp.
info_text_fm
Gtk::Frame StrategyGUI::info_text_fm
Definition at line 91 of file strategyGUI.hpp.
m_refTreeModel
Glib::RefPtr<Gtk::ListStore> StrategyGUI::m_refTreeModel
Definition at line 94 of file strategyGUI.hpp.
m_ScrolledWindow
Gtk::ScrolledWindow StrategyGUI::m_ScrolledWindow
Definition at line 103 of file strategyGUI.hpp.
m_TreeView
Gtk::TreeView StrategyGUI::m_TreeView
Definition at line 93 of file strategyGUI.hpp.
menu_fm
Gtk::Frame StrategyGUI::menu_fm
Definition at line 90 of file strategyGUI.hpp.
menu_hbox
Gtk::HBox StrategyGUI::menu_hbox[2]
Definition at line 97 of file strategyGUI.hpp.
menu_vbox
Gtk::VBox StrategyGUI::menu_vbox
Definition at line 96 of file strategyGUI.hpp.
select_button
Gtk::Button StrategyGUI::select_button
Definition at line 101 of file strategyGUI.hpp.
strategy
Strategy StrategyGUI::strategy
Definition at line 107 of file strategyGUI.hpp.
Referenced by _event_transitions_checkbox_signal_clicked(), CamCap::capture_and_show(), configureTestFrame(), CamCap::start_signal(), and StrategyGUI().
strategy_description_text
Glib::RefPtr<Gtk::TextBuffer> StrategyGUI::strategy_description_text
Definition at line 105 of file strategyGUI.hpp.
strategy_description_view
Gtk::TextView StrategyGUI::strategy_description_view
Definition at line 104 of file strategyGUI.hpp.
strategy_img
Gtk::Image StrategyGUI::strategy_img
Definition at line 99 of file strategyGUI.hpp.
strategyColumns
ModelColumns StrategyGUI::strategyColumns
Definition at line 88 of file strategyGUI.hpp.
transitions_check
Gtk::CheckButton StrategyGUI::transitions_check
Definition at line 129 of file strategyGUI.hpp.
Referenced by createTransitionsFrame().
transitions_fm
Gtk::Frame StrategyGUI::transitions_fm
Definition at line 127 of file strategyGUI.hpp.
Referenced by createTransitionsFrame().
transitions_grid
Gtk::Grid StrategyGUI::transitions_grid
Definition at line 128 of file strategyGUI.hpp.
Referenced by createTransitionsFrame().
update_interface_flag
bool StrategyGUI::update_interface_flag = false
Definition at line 113 of file strategyGUI.hpp.
Referenced by _event_loadFormation_bt_clicked(), and CamCap::formation_creation().
updating_formation_flag
bool StrategyGUI::updating_formation_flag = false
Definition at line 109 of file strategyGUI.hpp.
Referenced by _event_loadFormation_bt_clicked(), CamCap::capture_and_show(), and CamCap::updating_formation().
The documentation for this class was generated from the following files:
src/gui/strategyGUI.hpp
src/gui/strategyGUI.cpp