VSSS-INF: FlyingMessenger Class Reference
FlyingMessenger Class Reference
#include <flyingMessenger.hpp>
Public Member Functions
FlyingMessenger ()
Constructor of a new FlyingMessenger object.
std::vector< message > sendCMDs (std::vector< Robots::Command > commands)
Iterates between all robots instances and send specific messages to each one.
void send_msg (char id, std::string msg)
This method calls sendMessage method from xbee (instance of SerialCom class) and pass id and msg.
void send_old_format (std::string cmd)
Send command using old formatation of the string.
double get_battery (char id)
Get the battery charge value.
ack_count get_ack_count (char id)
Get the ack count of identified robot.
void reset_lost_acks ()
Resets all acks counters from robots.
void start_xbee (const std::string &port, int baud=115200)
This method creates the xbee connection passing the port and the baudrate.
void stop_xbee ()
Stops xbee connection and purge the instance of xbee (instance of SerialCom class).
void update_msg_time ()
Calculates the gap between sent messages.
void set_frameskipper (int frames)
int get_frameskipper ()
double get_time ()
Private Member Functions
void add_robots ()
Calls SerialCom's addNew method and add 6 possible connections to the robots based on their ID and address.
std::string position_msg (Robots::Command command)
Prepare the message to send to the robot a position message.
std::string speed_msg (Robots::Command command)
Prepare the message to send to the robot a speed message.
std::string orientation_msg (Robots::Command command)
Prepare the message to send to the robot a orientation message.
std::string vector_msg (Robots::Command command)
Prepare the message to send to the robot a vector message.
std::string rounded_str (double num)
Method to round the double number passed.
Private Attributes
SerialCom * xbee = nullptr
Creates a pointer to SerialCom class.
double time_between_msgs
int frameskip
int send_cmd_count
std::chrono::system_clock::time_point previous_msg_time
Detailed Description
Definition at line 24 of file flyingMessenger.hpp.
Constructor & Destructor Documentation
FlyingMessenger()
FlyingMessenger::FlyingMessenger ()
Constructor of a new FlyingMessenger object.
Definition at line 148 of file flyingMessenger.cpp.
References DEFAULT_FRAMESKIP.
{
     setlocale(LC_ALL,"C");
     send_cmd_count = 0;
     frameskip = DEFAULT_FRAMESKIP;
     previous_msg_time = std::chrono::system_clock::now();
 }
Member Function Documentation
add_robots()
void FlyingMessenger::add_robots () private
Calls SerialCom's addNew method and add 6 possible connections to the robots based on their ID and address.
Definition at line 15 of file flyingMessenger.cpp.
{
     if(!xbee) return;
     xbee->newRobot('A', 0x88a0);
     xbee->newRobot('B', 0xb24a);
     xbee->newRobot('C', 0x215c);
     xbee->newRobot('D', 0x35f6);
     xbee->newRobot('E', 0x97e7);
     xbee->newRobot('F', 0x6b0d);
     xbee->newRobot('G', 0x56bc);
 }
get_ack_count()
ack_count FlyingMessenger::get_ack_count (char id)
Get the ack count of identified robot.
Parameters
id Identification of the robot.
Returns
ack_count Return the number of acks of the specific robot.
Definition at line 119 of file flyingMessenger.cpp.
{
     if(!xbee) return {-1,-1,-1};
     else return xbee->get_ack_count(id);
 }
get_battery()
double FlyingMessenger::get_battery (char id)
Get the battery charge value.
Parameters
id Identification of the robot.
Returns
double Returns the value of battery energy of the specific robot.
Definition at line 104 of file flyingMessenger.cpp.
Referenced by ControlGUI::_robot_status().
{
     if(!xbee) return -1;
     std::string msg = xbee->getResponse(id,"B");
     if(msg.empty() || msg[0] != 'B') return -1;
     return ((stod(msg.substr(1)) - 6.4)/2.0)*100;
 }
get_frameskipper()
int FlyingMessenger::get_frameskipper ()
Definition at line 133 of file flyingMessenger.cpp.
Referenced by ControlGUI::ControlGUI().
{
     return frameskip;
 }
get_time()
double FlyingMessenger::get_time ()
Returns
time_between_msgs Gap between sent messages
Definition at line 137 of file flyingMessenger.cpp.
Referenced by ControlGUI::update_msg_time().
{
     return time_between_msgs;
 }
orientation_msg()
std::string FlyingMessenger::orientation_msg (Robots::Command command) private
Prepare the message to send to the robot a orientation message.
The message will send orientation value and the max velocity of the tragetory.
Parameters
robot Gets a Robot instance to prepare the specific message.
Returns
std::string Message containg prepared orientation message.
Definition at line 93 of file flyingMessenger.cpp.
References Robots::Command::Msg, Robots::_Status::orientation, Robots::Command::Status, Robots::Command::_Msg::theta, and Robots::_Status::vmax.
{
     double orientation = (command.Status.orientation + command.Msg.theta)*180/M_PI;
     return ("O"+ rounded_str(orientation)+";"+ rounded_str(command.Status.vmax));
 }
position_msg()
std::string FlyingMessenger::position_msg (Robots::Command command) private
Prepare the message to send to the robot a position message.
The message will send x position, y position and the velocity needed to make tragetory.
Parameters
robot Gets a Robot instance to prepare the specific message.
Returns
std::string Message containing prepared position and velocity message.
Definition at line 76 of file flyingMessenger.cpp.
References Robots::Command::Msg, Robots::_Status::orientation, Robots::_Status::position, Robots::Command::Status, Robots::Command::_Msg::target, and Robots::_Status::vmax.
{
     double diff_x = command.Msg.target.x - command.Status.position.x;
     double diff_y = command.Msg.target.y - command.Status.position.y;
     double transTarget_x = cos(command.Status.orientation)*diff_x + sin(command.Status.orientation)*diff_y;
     double transTarget_y = -(-sin(command.Status.orientation)*diff_x + cos(command.Status.orientation)*diff_y);
     double pos_x = transTarget_x*(150.0/640.0);
     double pos_y = transTarget_y*(130.0/480.0);
     return ("P"+ rounded_str(pos_x)+";"+ rounded_str(pos_y)+";"+ rounded_str(command.Status.vmax));
 }
reset_lost_acks()
void FlyingMessenger::reset_lost_acks ()
Resets all acks counters from robots.
This method calls reset_lost_acks method from xbee (instance of SerialCom class). that will iterate through all robots inside robots vector and sets 0 to all.
Definition at line 124 of file flyingMessenger.cpp.
{
     if(!xbee) return;
     xbee->reset_lost_acks();
 }
rounded_str()
std::string FlyingMessenger::rounded_str (double num) private
Method to round the double number passed.
Parameters
num Double number passed to be rounded.
Returns
std::string Returns a string containing the rounded double number passed.
Definition at line 111 of file flyingMessenger.cpp.
{
     double rounded_num = round(num*100)/100;
     std::ostringstream ss;
     ss << rounded_num;
     return ss.str();
 }
send_msg()
void FlyingMessenger::send_msg (char id, std::string msg)
This method calls sendMessage method from xbee (instance of SerialCom class) and pass id and msg.
Parameters
id Identification of the robot.
msg Message that will be sent to robot.
Definition at line 27 of file flyingMessenger.cpp.
Referenced by ControlGUI::_send_test().
{
     if(!xbee) return;
     xbee->sendMessage(id,msg);
 }
send_old_format()
void FlyingMessenger::send_old_format (std::string cmd)
Send command using old formatation of the string.
Parameters
cmd String containing the message that will be sent to the robot.
Definition at line 32 of file flyingMessenger.cpp.
Referenced by ControlGUI::_send_command().
{
     if(!xbee) return;
     char id = cmd[0];
     std::string msg = cmd.substr(2,cmd.find('#')-2);
     xbee->sendMessage(id,msg);
 }
sendCMDs()
std::vector< message > FlyingMessenger::sendCMDs (std::vector< Robots::Command > commands)
Iterates between all robots instances and send specific messages to each one.
Parameters
robots Vector containing all robots instances.
Returns
std::vector<message> Returns a vector of all acks received after send commands to each robots.
Definition at line 40 of file flyingMessenger.cpp.
References ORIENTATION, SPEED, and VECTOR.
Referenced by CamCap::send_cmd_thread().
{
     vector<message> acks;
     if(!xbee || ++send_cmd_count <= frameskip) return acks;
     for(Robots::Command command : commands){
         std::string msg;
         switch (command.cmdType){
             case Robots::CMD::SPEED:
                 msg = speed_msg(command);
                 break;
             case Robots::CMD::ORIENTATION:
                 msg = orientation_msg(command);
                 break;
             case Robots::CMD::VECTOR:
                 msg = vector_msg(command);
                 break;
             default: // POSITION
                 if(command.Msg.target.x != -1 && command.Msg.target.y != -1)
                     msg = position_msg(command);
         }
         if(!msg.empty()) {
             int ack = xbee->sendMessage(command.ID,msg);
             acks.push_back({command.ID, std::to_string(ack)});
         }
     }
     update_msg_time();
     send_cmd_count=0;
     return acks;
 }
set_frameskipper()
void FlyingMessenger::set_frameskipper (int frames)
Definition at line 129 of file flyingMessenger.cpp.
Referenced by ControlGUI::set_frameskipper().
{
     frameskip = frames;
 }
speed_msg()
std::string FlyingMessenger::speed_msg (Robots::Command command) private
Prepare the message to send to the robot a speed message.
The message will send left and right wheel speed to the robot.
Parameters
robot Gets a Robot instance to prepare the specific message.
Returns
std::string Message containing prepared speed message.
Definition at line 89 of file flyingMessenger.cpp.
References Robots::Command::_Msg::_Velocity::left, Robots::Command::Msg, Robots::Command::_Msg::_Velocity::right, and Robots::Command::_Msg::Velocity.
{
     return (rounded_str(command.Msg.Velocity.right)+";"+ rounded_str(command.Msg.Velocity.left));
 }
start_xbee()
void FlyingMessenger::start_xbee (const std::string & port, int baud = 115200)
This method creates the xbee connection passing the port and the baudrate.
All connections are instances of SerialCom class.
Parameters
port String path of the serial port that handles xbee radio (Eg. /dev/ttyUSB1).
baud Baudrate of the communication between host pc and xbee.
Definition at line 4 of file flyingMessenger.cpp.
Referenced by ControlGUI::_start_serial().
{
     xbee = new SerialCom(port, baud);
     add_robots();
 }
stop_xbee()
void FlyingMessenger::stop_xbee ()
Stops xbee connection and purge the instance of xbee (instance of SerialCom class).
Definition at line 9 of file flyingMessenger.cpp.
Referenced by ControlGUI::_update_cb_serial().
{
     if(!xbee) return;
     delete xbee;
     xbee = nullptr;
 }
update_msg_time()
void FlyingMessenger::update_msg_time ()
Calculates the gap between sent messages.
Definition at line 141 of file flyingMessenger.cpp.
{
     auto now = std::chrono::system_clock::now();
     std::chrono::duration<double, std::milli> time_diff = now - previous_msg_time;
     time_between_msgs = time_diff.count();
     previous_msg_time = now;
 }
vector_msg()
std::string FlyingMessenger::vector_msg (Robots::Command command) private
Prepare the message to send to the robot a vector message.
The message will send orientation value and the max velocity of the tragetory.
Parameters
robot Gets a Robot instance to prepare the specific message.
Returns
std::string Message containg prepared orientation message.
Definition at line 98 of file flyingMessenger.cpp.
References Robots::Command::Msg, Robots::_Status::orientation, Robots::Command::Status, Robots::Command::_Msg::theta, and Robots::_Status::vmax.
{
     double orientation = atan2(sin(command.Status.orientation + command.Msg.theta), cos(command.Status.orientation + command.Msg.theta));
     orientation = orientation*(180.0/M_PI);
     return ("V"+ rounded_str(orientation)+";"+ rounded_str(command.Status.vmax));
 }
Field Documentation
frameskip
int FlyingMessenger::frameskip private
Definition at line 34 of file flyingMessenger.hpp.
previous_msg_time
std::chrono::system_clock::time_point FlyingMessenger::previous_msg_time private
Definition at line 35 of file flyingMessenger.hpp.
send_cmd_count
int FlyingMessenger::send_cmd_count private
Definition at line 34 of file flyingMessenger.hpp.
time_between_msgs
double FlyingMessenger::time_between_msgs private
Definition at line 33 of file flyingMessenger.hpp.
xbee
SerialCom* FlyingMessenger::xbee = nullptr private
Creates a pointer to SerialCom class.
SerialCom class defines interaction methods with xbee radios like initial configuration, send and get message. More details can be found on serialCom.hpp.
Definition at line 31 of file flyingMessenger.hpp.
The documentation for this class was generated from the following files:
src/communication/flyingMessenger.hpp
src/communication/flyingMessenger.cpp