VSSS-INF: TestFrame Class Reference
TestFrame Class Reference
#include <testFrame.hpp>
Public Member Functions
TestFrame ()
~TestFrame ()
double getValue (int index)
void configureHScale (int index, double currentValue, double min, double max, double digits=1, double steps=1)
void setLabel (int index, std::string label)
void setName (std::string name)
Private Member Functions
void init ()
Private Attributes
Gtk::Grid grid
Gtk::HScale hscale [5]
Gtk::Label label [5]
Detailed Description
Definition at line 8 of file testFrame.hpp.
Constructor & Destructor Documentation
TestFrame()
TestFrame::TestFrame ()
Definition at line 57 of file testFrame.cpp.
References init().
                      {
   init();
 }
~TestFrame()
TestFrame::~TestFrame ()
Definition at line 61 of file testFrame.cpp.
 {}
Member Function Documentation
configureHScale()
void TestFrame::configureHScale (int index, double currentValue, double min, double max, double digits = 1, double steps = 1)
Definition at line 19 of file testFrame.cpp.
References hscale.
Referenced by ControlGUI::configureTestFrame(), and StrategyGUI::configureTestFrame().
{
     if (index < 0 || index > 4) {
       std::cout << "TestFrame::configureHScale: invalid index error." << std::endl;
         return;
     }
     hscale[index].set_digits(digits);
     hscale[index].set_increments(steps,steps*5);
     hscale[index].set_range(min,max);
     hscale[index].set_value(currentValue);
 }
getValue()
double TestFrame::getValue (int index)
Definition at line 11 of file testFrame.cpp.
References hscale.
Referenced by Strategy::get_variables().
{
     if(index < 0 || index > 4) {
       std::cout << "TestFrame::getValue: invalid index error." << std::endl;
         return -1;
     }
     return hscale[index].get_value();
 }
init()
void TestFrame::init () private
Definition at line 35 of file testFrame.cpp.
References grid, hscale, and label.
Referenced by TestFrame().
                      {
     add(grid);
     set_label("Test Parameters");
     grid.set_border_width(10);
     grid.set_column_spacing(5);
     grid.set_halign(Gtk::ALIGN_CENTER);
     grid.set_column_homogeneous(true);
     grid.set_size_request(300,-1);
     for (int i = 0; i < 5; i++) {
         grid.attach(label[i], 0, i, 1, 1);
         grid.attach(hscale[i], 1, i, 4, 1);
         label[i].set_text("HScale");
         hscale[i].set_digits(0);
         hscale[i].set_increments(1,1);
         hscale[i].set_range(0,100);
         hscale[i].set_valign(Gtk::ALIGN_CENTER);
     }
 }
setLabel()
void TestFrame::setLabel (int index, std::string label)
Definition at line 3 of file testFrame.cpp.
References label.
Referenced by ControlGUI::configureTestFrame(), and StrategyGUI::configureTestFrame().
{
     if(index < 0 || index > 4) {
       std::cout << "TestFrame::setLabel: invalid index error." << std::endl;
         return;
     }
     label[index].set_text(lb);
 }
setName()
void TestFrame::setName (std::string name)
Definition at line 31 of file testFrame.cpp.
{
     set_label(name);
 }
Field Documentation
grid
Gtk::Grid TestFrame::grid private
Definition at line 10 of file testFrame.hpp.
Referenced by init().
hscale
Gtk::HScale TestFrame::hscale[5] private
Definition at line 12 of file testFrame.hpp.
Referenced by configureHScale(), getValue(), and init().
label
Gtk::Label TestFrame::label[5] private
Definition at line 13 of file testFrame.hpp.
Referenced by init(), and setLabel().
The documentation for this class was generated from the following files:
src/gui/testFrame.hpp
src/gui/testFrame.cpp