VSSS-INF: v4lcap Class Reference
v4lcap Class Reference
#include <v4lcap.hpp>
Data Structures
struct buffer
struct buffer_holder
Public Types
enum memory_type { MEM_READ, MEM_MMAP, MEM_USER }
enum device_status { OPENED = 1 << 0, MMAP_INIT = 1 << 1, STREAM_ON = 1 << 2 }
Public Member Functions
int xioctl (int fd, int request, void *arg)
v4lcap ()
~v4lcap ()
bool open_device (const char *devname, bool emulate_fmt)
By getting device name and emulated format, this method open the connection to the camera.
bool start_capturing (enum memory_type mem_type, int nbuffers)
This method starts capturing and streaming from opened device passing memory type and number of buffers used.
bool start_capturing ()
This method starts capturing and streaming from opened device.
bool init_mmap (int nbuffers)
This method requests buffers from host system to allocate streaming from camera.
bool set_input (int index)
Set the input object.
bool set_standard (v4l2_std_id std_id)
Set the standard object.
bool set_pixel_format (unsigned int pixel_format)
Set the pixel format object.
bool set_frame_size (int width, int height, unsigned int type)
Set the frame size object.
bool set_frame_interval (struct v4l2_fract &fract)
Set the frame interval object.
bool set_control (int ctrl_id, int value)
Set the control object.
bool streamon (enum v4l2_buf_type type)
Query stream to initiate.
bool streamon (int type)
void * grab_raw (unsigned char *raw)
void * grab_rgb (unsigned char *rgb)
bool streamoff (enum v4l2_buf_type type)
Query stream to terminate.
bool streamoff (int type)
bool stop_capturing ()
Closes capturing query.
bool uninit_mmap ()
Free all requested buffers.
bool close_device ()
Close camera communication with pc.
bool is_opened ()
Verify if camera is open.
bool query_capability (struct v4l2_capability *cap)
Verify query lenght capability.
bool get_format (struct v4l2_format *fmt, unsigned int type)
Get the format object.
bool get_format (struct v4l2_format *fmt)
bool get_input_index (unsigned int *input)
Get the input index object.
bool get_input (struct v4l2_input *input)
Get the input object.
bool get_standard_id (v4l2_std_id *std_id)
Get the standard id object.
bool get_standard (struct v4l2_standard *standard)
Get the standard object.
bool get_stream_parameter (struct v4l2_streamparm *streamparm, unsigned int type)
Get the stream parameter object.
bool get_control (struct v4l2_control *ctrl, unsigned int ctrl_id)
Get the control object.
bool query_control (struct v4l2_queryctrl *qctrl)
Query control options.
bool query_control_menu (struct v4l2_querymenu *qmenu)
Query control menu.
bool request_buffers (struct v4l2_requestbuffers *req_buff, int nbuffers, enum v4l2_memory memory, enum v4l2_buf_type type)
Request buffers allocation from SO.
bool request_buffers (struct v4l2_requestbuffers *req_buff)
bool request_buffers_mmap (struct v4l2_requestbuffers *req_buff, int nbuffers)
bool query_buffer (struct v4l2_buffer *buffer)
Query buffers to camera.
bool query_buffer (struct v4l2_buffer *buf, unsigned int type, unsigned int memory, unsigned int index)
bool query_buffer (struct v4l2_buffer *buf, enum v4l2_buf_type type, enum v4l2_memory memory, unsigned int index)
bool enqueue_buff (struct v4l2_buffer *vbuf)
Enqueue requested buffers and set capture params.
bool enqueue_buff (struct v4l2_buffer *vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, int index)
bool enqueue_buff (struct v4l2_buffer *vbuf, unsigned int buf_type, unsigned int memory, int index)
bool dequeue_buff (struct v4l2_buffer *vbuf)
Dequeue buffers allocated.
bool dequeue_buff (struct v4l2_buffer *vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, bool *again)
bool dequeue_buff (struct v4l2_buffer *vbuf, unsigned int buf_type, unsigned int memory, bool *again)
bool init_mmap (struct v4l2_requestbuffers *req_buff)
Get current format of data, request buffers from mmap, allocate buffers and map memory allocated.
bool enum_audio_input (struct v4l2_audio *audio, int index=0, bool init=false)
Enumerate audio inputs.
bool enum_audio_output (struct v4l2_audioout *audiout, int index=0, bool init=false)
Enumerate audio outputs.
bool enum_dv_timings (...)
Enumerate supported Digital Video timings.
bool enum_image_format (int fd, struct v4l2_fmtdesc *fmtdesc)
Enumerate image formats.
bool enum_image_format (struct v4l2_fmtdesc *fmtdesc, int index=0, bool init=false)
bool enum_frame_size (struct v4l2_frmsizeenum *frmsize, int pixel_format, int index=0, bool init=false)
Enumerate frame sizes.
bool enum_frame_interval (struct v4l2_frmivalenum *frmi, int pixel_format, int width, int height, int index=0, bool init=false)
enumerate frame intervals
bool enum_video_freq_bands (...)
Enumerate supported frequency bands.
bool enum_video_input (struct v4l2_input *input, int index=0, bool init=false)
Enumerate video inputs.
bool enum_video_output (struct v4l2_output *output, int index=0, bool init=false)
Enumerate video outputs.
bool enum_video_standard (struct v4l2_standard *std, int index=0, bool init=false)
Enumerate supported video.
bool enum_control_user_base (struct v4l2_queryctrl *qctrl, bool init=false)
bool enum_control_private_base (struct v4l2_queryctrl *qctrl, bool init=false)
bool enum_control_default (struct v4l2_queryctrl *qctrl, bool init=false)
bool show_controls ()
bool enum_control_menu (struct v4l2_querymenu *qmenu, v4l2_queryctrl &ctrl, int index=0, bool init=false)
Fills menu controll with values.
bool set_format (struct v4l2_format *fmt)
Static Public Member Functions
static bool enum_device_name (char device[16], int ndev_max, bool init=false)
Search and returns the path name of device that could be opened in the host by.
Data Fields
int fd
bool emulate_format
bool needs_convert
struct v4l2_format format_src format_dest
Video format that the cam's video should be returned, if not null. If format is not supported, this will change to another one. Gets the format from de camera. Destination format of the video.
struct v4lconvert_data * v4lconv
Data obtained from camera.
struct v4l2_requestbuffers reqbuf
unsigned int status
struct buffer_holder buffers
Detailed Description
Definition at line 20 of file v4lcap.hpp.
Member Enumeration Documentation
device_status
enum v4lcap::device_status
Enumerator
OPENED
MMAP_INIT
STREAM_ON
Definition at line 50 of file v4lcap.hpp.
{
         OPENED = 1 << 0, MMAP_INIT = 1 << 1, STREAM_ON = 1 << 2
     };
memory_type
enum v4lcap::memory_type
Enumerator
MEM_READ
MEM_MMAP
MEM_USER
Definition at line 23 of file v4lcap.hpp.
                      {
         MEM_READ, MEM_MMAP, MEM_USER
     };
Constructor & Destructor Documentation
v4lcap()
v4lcap::v4lcap ()
Definition at line 26 of file v4lcap.cpp.
 : fd(0), emulate_format(true), needs_convert(false), v4lconv(NULL), status(0), buffers() {}
~v4lcap()
v4lcap::~v4lcap ()
Definition at line 28 of file v4lcap.cpp.
References close_device().
                 {
     close_device();
 }
Member Function Documentation
close_device()
bool v4lcap::close_device ()
Close camera communication with pc.
Returns
true If close goes right
false Can't close webcam communication
Definition at line 462 of file v4lcap.cpp.
References emulate_format, fd, MMAP_INIT, OPENED, status, STREAM_ON, streamoff(), uninit_mmap(), and v4lconv.
Referenced by VSSS_GUI::V4LInterface::__event_cb_device_changed(), open_device(), and ~v4lcap().
{
     if(!(status & OPENED)) return true;
     if(status & STREAM_ON) streamoff(V4L2_BUF_TYPE_VIDEO_CAPTURE);
     if(status & MMAP_INIT) uninit_mmap();
     int r = 0;
     if(v4lconv) v4lconvert_destroy(v4lconv);
     if(emulate_format) r = v4l2_close(fd);
     else r = close(fd);
     if(r < 0) {
         cout << "Unable to close device!" << endl;
         return false;
     }
     fd = 0;
     return true;
 }
dequeue_buff() [1/3]
bool v4lcap::dequeue_buff (struct v4l2_buffer * vbuf)
Dequeue buffers allocated.
Parameters
vbuf
Returns
true
false
Definition at line 150 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by dequeue_buff(), grab_raw(), and grab_rgb().
{
     return xioctl(fd, VIDIOC_DQBUF, vbuf) >= 0;
 }
dequeue_buff() [2/3]
bool v4lcap::dequeue_buff (struct v4l2_buffer * vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, bool * again)
Definition at line 166 of file v4lcap.cpp.
References dequeue_buff().
{
     memset(vbuf, 0, sizeof(struct v4l2_buffer));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     int r = dequeue_buff(vbuf);
     // if the buffer is not avaliable, try again.
     *again = (r < 0) && (errno == EAGAIN);
     return(r >= 0) || (*again);
 }
dequeue_buff() [3/3]
bool v4lcap::dequeue_buff (struct v4l2_buffer * vbuf, unsigned int buf_type, unsigned int memory, bool * again)
Definition at line 154 of file v4lcap.cpp.
References dequeue_buff().
{
     memset(vbuf, 0, sizeof(struct v4l2_buffer));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     int r = dequeue_buff(vbuf);
     // if the buffer is not avaliable, try again.
     *again = (r < 0) && (errno == EAGAIN);
     return(r >= 0) || (*again);
 }
enqueue_buff() [1/3]
bool v4lcap::enqueue_buff (struct v4l2_buffer * vbuf)
Enqueue requested buffers and set capture params.
Parameters
vbuf
Returns
true
false
Definition at line 128 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by enqueue_buff(), grab_raw(), grab_rgb(), and start_capturing().
{
     return xioctl(fd, VIDIOC_QBUF, vbuf) >= 0;
 }
enqueue_buff() [2/3]
bool v4lcap::enqueue_buff (struct v4l2_buffer * vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, int index)
Definition at line 132 of file v4lcap.cpp.
References enqueue_buff().
{
     memset(vbuf, 0, sizeof(*vbuf));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     vbuf->index = index;
     return enqueue_buff(vbuf);
 }
enqueue_buff() [3/3]
bool v4lcap::enqueue_buff (struct v4l2_buffer * vbuf, unsigned int buf_type, unsigned int memory, int index)
Definition at line 141 of file v4lcap.cpp.
References enqueue_buff().
{
     memset(vbuf, 0, sizeof(*vbuf));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     vbuf->index = index;
     return enqueue_buff(vbuf);
 }
enum_audio_input()
bool v4lcap::enum_audio_input (struct v4l2_audio * audio, int index = 0, bool init = false)
Enumerate audio inputs.
Parameters
audio
index
init
Returns
true
false
Definition at line 575 of file v4lcap.cpp.
References fd, and xioctl().
{
     if(init) audio->index = index;
     else ++audio->index;
     audio->reserved[0] = 0;
     audio->reserved[1] = 0;
     return xioctl(fd, VIDIOC_ENUMAUDIO, audio) >= 0;
 }
enum_audio_output()
bool v4lcap::enum_audio_output (struct v4l2_audioout * audiout, int index = 0, bool init = false)
Enumerate audio outputs.
Parameters
audiout
index
init
Returns
true
false
Definition at line 585 of file v4lcap.cpp.
References fd, and xioctl().
{
     if(init) audiout->index = index;
     else ++audiout->index;
     audiout->reserved[0] = 0;
     audiout->reserved[1] = 0;
     return xioctl(fd, VIDIOC_ENUMAUDOUT, audiout) >= 0;
 }
enum_control_default()
bool v4lcap::enum_control_default (struct v4l2_queryctrl * qctrl, bool init = false)
Parameters
qctrl
init
Returns
true
false
Definition at line 656 of file v4lcap.cpp.
References query_control().
Referenced by VSSS_GUI::V4LInterface::__make_control_list_default().
{
     if(init) qctrl->id = V4L2_CTRL_FLAG_NEXT_CTRL;
     else qctrl->id |= V4L2_CTRL_FLAG_NEXT_CTRL;
     return query_control(qctrl);
 }
enum_control_menu()
bool v4lcap::enum_control_menu (struct v4l2_querymenu * qmenu, v4l2_queryctrl & ctrl, int index = 0, bool init = false)
Fills menu controll with values.
Parameters
qmenu Pointer to menu
ctrl
index
init
Returns
true
false
Definition at line 687 of file v4lcap.cpp.
References query_control_menu().
Referenced by VSSS_GUI::V4LInterface::__make_control_list_default().
{
     if(init) {
         //memset(qmenu, 0, sizeof(struct v4l2_querymenu));
         qmenu->id = ctrl.id;
         qmenu->index = ctrl.minimum;
     } else qmenu->index++;
     if((int) qmenu->index > ctrl.maximum)
         return false;
     while(!query_control_menu(qmenu))
         qmenu->index++;
     return true;
 }
enum_control_private_base()
bool v4lcap::enum_control_private_base (struct v4l2_queryctrl * qctrl, bool init = false)
Parameters
qctrl
init
Returns
true
false
Definition at line 678 of file v4lcap.cpp.
References query_control().
{
     if(init) qctrl->id = V4L2_CID_PRIVATE_BASE;
     else ++qctrl->id;
     if (!query_control(qctrl)) return false;
     return true;
 }
enum_control_user_base()
bool v4lcap::enum_control_user_base (struct v4l2_queryctrl * qctrl, bool init = false)
Parameters
qctrl
init
Returns
true
false
Definition at line 663 of file v4lcap.cpp.
References query_control().
{
     if(init) qctrl->id = V4L2_CID_BASE;
     else {
         ++qctrl->id;
         if (qctrl->id >= V4L2_CID_LASTP1) return false;
     }
     while(!query_control(qctrl)) {
         ++qctrl->id;
         if (qctrl->id > V4L2_CID_LASTP1) return false;
     }
     return true;
 }
enum_device_name()
bool v4lcap::enum_device_name (char device[16], int ndev_max, bool init = false) static
Search and returns the path name of device that could be opened in the host by.
Parameters
device Path name of the device that will be filled inside the method.
ndev_max Max number of devices (cameras) on host.
init Boolean trigger the method.
Returns
true Camera was found and the name will be filled inside 'device' param.
false Camera was not found.
Definition at line 45 of file v4lcap.cpp.
Referenced by VSSS_GUI::V4LInterface::__update_cb_device().
{
     static int __dev_count = 0;
     bool not_found = true;
     struct stat st;
     if(init) __dev_count = 0;
     while(not_found && __dev_count < ndev_max) {
         snprintf(device, 15, "/dev/video%d", __dev_count);
         ++__dev_count;
         if(stat(device, &st) != 0) continue;
         not_found = false;
     }
     return !not_found;
 }
enum_dv_timings()
bool v4lcap::enum_dv_timings (...)
Enumerate supported Digital Video timings.
Parameters
...
Returns
true
false
enum_frame_interval()
bool v4lcap::enum_frame_interval (struct v4l2_frmivalenum * frmi, int pixel_format, int width, int height, int index = 0, bool init = false)
enumerate frame intervals
Parameters
frmi
pixel_format
width
height
index
init
Returns
true
false
Definition at line 624 of file v4lcap.cpp.
References fd, CONST::height, CONST::width, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_frame_interval().
{
     if(init) frmi->index = 0;
     else ++frmi->index;
     frmi->pixel_format = pixel_format;
     frmi->width = width;
     frmi->height = height;
     return xioctl(fd, VIDIOC_ENUM_FRAMEINTERVALS, frmi) >= 0;
 }
enum_frame_size()
bool v4lcap::enum_frame_size (struct v4l2_frmsizeenum * frmsize, int pixel_format, int index = 0, bool init = false)
Enumerate frame sizes.
Parameters
frmsize
pixel_format
index
init
Returns
true
false
Definition at line 615 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_frame_size().
{
     if(init) frmsize->index = index;
     else ++frmsize->index;
     frmsize->pixel_format = pixel_format;
     return xioctl(fd, VIDIOC_ENUM_FRAMESIZES, frmsize) >= 0;
 }
enum_image_format() [1/2]
bool v4lcap::enum_image_format (int fd, struct v4l2_fmtdesc * fmtdesc)
Enumerate image formats.
Parameters
fd
fmtdesc
Returns
true
false
Definition at line 595 of file v4lcap.cpp.
References xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_format_desc(), and enum_image_format().
{
     return xioctl(fd, VIDIOC_ENUM_FMT, fmtdesc) >= 0;
 //      int r = xioctl(fd, VIDIOC_ENUM_FMT, fmtdesc);
 //      if (r >= 0) return true;
 //      if( EINVAL == errno ) perror("VIDIOC_ENUM_FMT");
 //      return false;
 }
enum_image_format() [2/2]
bool v4lcap::enum_image_format (struct v4l2_fmtdesc * fmtdesc, int index = 0, bool init = false)
Definition at line 603 of file v4lcap.cpp.
References enum_image_format(), and fd.
{
     if(init) {
         memset(fmtdesc, 0, sizeof(struct v4l2_fmtdesc));
         fmtdesc->index = index;
     } else fmtdesc->index++;
     fmtdesc->type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     return enum_image_format(fd, fmtdesc);
     //return xioctl(fd, VIDIOC_ENUM_FMT, fmtdesc) >= 0;
 }
enum_video_freq_bands()
bool v4lcap::enum_video_freq_bands (...)
Enumerate supported frequency bands.
Parameters
...
Returns
true
false
enum_video_input()
bool v4lcap::enum_video_input (struct v4l2_input * input, int index = 0, bool init = false)
Enumerate video inputs.
Parameters
input
index
init
Returns
true
false
Definition at line 635 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_input().
{
     if(init) input->index = index;
     else ++input->index;
     return xioctl(fd, VIDIOC_ENUMINPUT, input) >= 0;
 }
enum_video_output()
bool v4lcap::enum_video_output (struct v4l2_output * output, int index = 0, bool init = false)
Enumerate video outputs.
Parameters
output
index
init
Returns
true
false
Definition at line 642 of file v4lcap.cpp.
References fd, and xioctl().
{
     if(init) output->index = index;
     else ++output->index;
     return xioctl(fd, VIDIOC_ENUMOUTPUT, output) >= 0;
 }
enum_video_standard()
bool v4lcap::enum_video_standard (struct v4l2_standard * std, int index = 0, bool init = false)
Enumerate supported video.
Parameters
std
index
init
Returns
true
false
Definition at line 649 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_standard(), and get_standard().
{
     if(init) std->index = index;
     else ++std->index;
     return xioctl(fd, VIDIOC_ENUMSTD, std) >= 0;
 }
get_control()
bool v4lcap::get_control (struct v4l2_control * ctrl, unsigned int ctrl_id)
Get the control object.
Parameters
ctrl
ctrl_id
Returns
true
false
Definition at line 537 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__set_control_hscale(), VSSS_GUI::V4LInterface::__update_control_widgets(), and jsonSaveManager::save_camera().
{
     ctrl->id = ctrl_id;
     return xioctl(fd, VIDIOC_G_CTRL, ctrl) >= 0;
 }
get_format() [1/2]
bool v4lcap::get_format (struct v4l2_format * fmt, unsigned int type)
Get the format object.
Parameters
fmt
type
Returns
true
false
Definition at line 494 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked(), VSSS_GUI::V4LInterface::__update_cb_format_desc(), VSSS_GUI::V4LInterface::__update_cb_frame_interval(), VSSS_GUI::V4LInterface::__update_cb_frame_size(), init_mmap(), set_frame_size(), and set_pixel_format().
{
     fmt->type = type;
     return xioctl(fd, VIDIOC_G_FMT, fmt) >= 0;
 }
get_format() [2/2]
bool v4lcap::get_format (struct v4l2_format * fmt)
Definition at line 489 of file v4lcap.cpp.
References fd, and xioctl().
{
     fmt->type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     return xioctl(fd, VIDIOC_G_FMT, fmt) >= 0;
 }
get_input()
bool v4lcap::get_input (struct v4l2_input * input)
Get the input object.
Parameters
input
Returns
true
false
Definition at line 503 of file v4lcap.cpp.
References fd, get_input_index(), and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_input().
{
     unsigned int index;
     if (!get_input_index(&index)) return false;
     input->index = index;
     return xioctl(fd, VIDIOC_ENUMINPUT, input) >= 0;
 }
get_input_index()
bool v4lcap::get_input_index (unsigned int * input)
Get the input index object.
Parameters
input
Returns
true
false
Definition at line 499 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by get_input().
{
     return xioctl(fd, VIDIOC_G_INPUT, input) >= 0;
 }
get_standard()
bool v4lcap::get_standard (struct v4l2_standard * standard)
Get the standard object.
Parameters
standard
Returns
true
false
Definition at line 517 of file v4lcap.cpp.
References enum_video_standard(), fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_standard().
{
     v4l2_std_id std_id;
     if(xioctl(fd, VIDIOC_G_STD, &std_id) < 0) return false;
     if(enum_video_standard(standard, 0, true)) {
         do {
             if(standard->id == std_id)
                 return true;
         } while(enum_video_standard(standard));
     }
     return false;
 }
get_standard_id()
bool v4lcap::get_standard_id (v4l2_std_id * std_id)
Get the standard id object.
Parameters
std_id This type is a set, each bit representing another video standard.
See also
https://www.linuxtv.org/downloads/v4l-dvb-apis-old/vidioc-enumstd.html#v4l2-std-id
Returns
true
false
Definition at line 513 of file v4lcap.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_G_STD, std_id) >= 0;
 }
get_stream_parameter()
bool v4lcap::get_stream_parameter (struct v4l2_streamparm * streamparm, unsigned int type)
Get the stream parameter object.
Parameters
streamparm
type
Returns
true
false
Definition at line 532 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__update_cb_frame_interval(), and set_frame_interval().
{
     streamparm->type = type;
     return xioctl(fd, VIDIOC_G_PARM, streamparm) >= 0;
 }
grab_raw()
void * v4lcap::grab_raw (unsigned char * raw)
Parameters
raw
Returns
void*
Definition at line 346 of file v4lcap.cpp.
References buffers, v4lcap::buffer_holder::buffs, dequeue_buff(), enqueue_buff(), and v4lcap::buffer::start.
{
     struct v4l2_buffer vbuf;
     memset(&vbuf, 0, sizeof(struct v4l2_buffer));
     /* dequeue buffer */
     // =========================================================================
     int count = 0;
     bool again = false;
     do {
         dequeue_buff(&vbuf, V4L2_BUF_TYPE_VIDEO_CAPTURE, V4L2_MEMORY_MMAP, &again);
         if(count > 100) {
             std::cout << "Cannot dequeue buffer " << vbuf.index << std::endl;
             break;
         }
         count++;
     } while(again);
     // =========================================================================
     unsigned char * data = (unsigned char *) buffers.buffs[vbuf.index].start;
     for(unsigned int i = 0; i < vbuf.bytesused; ++i) {
         *raw = *data;
         ++data;
         ++raw;
     }
     // =========================================================================
     if(!enqueue_buff(&vbuf))
         std::cout << "Can't enqueue buffer " << vbuf.index << " !" << std::endl;
     return data;
 }
grab_rgb()
void * v4lcap::grab_rgb (unsigned char * rgb)
Definition at line 382 of file v4lcap.cpp.
References buffers, v4lcap::buffer_holder::buffs, dequeue_buff(), enqueue_buff(), format_dest, needs_convert, v4lcap::buffer::start, and v4lconv.
Referenced by CamCap::capture_and_show(), and VSSS_GUI::V4LInterface::grab_rgb().
{
     struct v4l2_buffer vbuf;
     memset(&vbuf, 0, sizeof(struct v4l2_buffer));
     /* dequeue buffer */
     // =========================================================================
     int count = 0;
     bool again = false;
     do {
         dequeue_buff(&vbuf, V4L2_BUF_TYPE_VIDEO_CAPTURE, V4L2_MEMORY_MMAP, &again);
         if(count > 100) {
             std::cout << "Cannot dequeue buffer " << vbuf.index << std::endl;
             break;
         }
         count++;
     } while (again);
     // =========================================================================
     unsigned char * data = (unsigned char *) buffers.buffs[vbuf.index].start;
     if(needs_convert) {
         int err = 0;
         err = v4lconvert_convert(v4lconv, &format_src, &format_dest, (unsigned char *) data, vbuf.bytesused, rgb, format_dest.fmt.pix.sizeimage);
         if (err < 0)
             std::cout << "OOpsss \n";
     }
 //      for (int i = 0; i < format_dest.fmt.pix.sizeimage; ++i) {
 //          *rgb = *data;
 //          ++rgb;
 //          ++data;
 //      }
     // =========================================================================
     if(!enqueue_buff(&vbuf))
         std::cout << "Can't enqueue buffer " << vbuf.index << " !" << std::endl;
     return NULL;
 }
init_mmap() [1/2]
bool v4lcap::init_mmap (int nbuffers)
This method requests buffers from host system to allocate streaming from camera.
Parameters
nbuffers Number of buffers requested.
Returns
true Buffers successfully allocated.
false If cannot allocate buffers.
Definition at line 179 of file v4lcap.cpp.
References buffers, v4lcap::buffer_holder::buffs, emulate_format, fd, get_format(), v4lcap::buffer::length, v4lcap::buffer_holder::qtd, query_buffer(), reqbuf, request_buffers_mmap(), and v4lcap::buffer::start.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and start_capturing().
{
     // = Get current format ====================================================
     if(!get_format(&format_src, V4L2_BUF_TYPE_VIDEO_CAPTURE)) return false;
     // = Request buffers by mmap ===============================================
     if(!request_buffers_mmap(&reqbuf, nbuffers)) {
         std::cout << "Can't request mmap buffers.\n";
         return false;
     }
     if(reqbuf.count < 2) {
         // = Request 0 buffers to clean memory driver ==========================
         request_buffers_mmap(&reqbuf, 0);
         std::cout << "Insufficient buffer memory.\n";
         return false;
     }
     // = Alloc buffer holders ==================================================
     buffers.qtd = reqbuf.count;
     buffers.buffs = (struct buffer *) calloc(reqbuf.count, sizeof(struct buffer));
     if(!buffers.buffs) return false;
     // = Memory map: mmap ======================================================
     for (unsigned int i = 0; i < reqbuf.count; ++i) {
         struct v4l2_buffer buffer = { 0 };
         if (!query_buffer(&buffer, V4L2_BUF_TYPE_VIDEO_CAPTURE, V4L2_MEMORY_MMAP, i))
             std::cout << "Can't request buffer " << i << std::endl;
         buffers.buffs[i].length = buffer.length; /* remember for munmap() */
         if(emulate_format) {
             buffers.buffs[i].start = v4l2_mmap(NULL, //
                     buffer.length, //
                     PROT_READ | PROT_WRITE, /* recommended */
                     MAP_SHARED, /* recommended */
                     fd, //
                     buffer.m.offset);
         } else {
             buffers.buffs[i].start = mmap(NULL, //
                     buffer.length, //
                     PROT_READ | PROT_WRITE, /* recommended */
                     MAP_SHARED, /* recommended */
                     fd, //
                     buffer.m.offset);
         }
         if(MAP_FAILED == buffers.buffs[i].start) {
             /* If you do not exit here you should unmap() and free() the buffers mapped so far. */
             perror("mmap");
             exit(EXIT_FAILURE);
         }
 //          //////////////////////////////
 //          if (!query_buffer(&buffer, reqbuf.type, reqbuf.memory, i)) {
 //              std::cout << "Can't request buffer " << i << std::endl;
 //          }
 //          if (buffer.flags & V4L2_BUF_FLAG_MAPPED) {
 //              std::cout << "Buffer " << i << " mapped!" << std::endl;
 //          } else {
 //              std::cout << "Buffer " << i << " NOT mapped!" << std::endl;
 //          }
     }
     return true;
 }
init_mmap() [2/2]
bool v4lcap::init_mmap (struct v4l2_requestbuffers * req_buff)
Get current format of data, request buffers from mmap, allocate buffers and map memory allocated.
Parameters
req_buff
Returns
true
false
is_opened()
bool v4lcap::is_opened ()
Verify if camera is open.
Returns
true Camera is open
false Camera is not open
Definition at line 41 of file v4lcap.cpp.
References fd.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and VSSS_GUI::V4LInterface::__event_cb_device_changed().
{
     return fd > 0;
 }
open_device()
bool v4lcap::open_device (const char * devname, bool emulate_fmt)
By getting device name and emulated format, this method open the connection to the camera.
Parameters
devname Name of requested device.
emulate_fmt Boolean that sets up if camera will be emulated using libv4l2 wrapper.
Returns
true If device was open and ready to use.
false If device cannot be opened or device is not compatible with de library.
Definition at line 64 of file v4lcap.cpp.
References close_device(), emulate_format, fd, OPENED, query_capability(), status, and v4lconv.
Referenced by VSSS_GUI::V4LInterface::__event_cb_device_changed().
{
     fd = open(devname, O_RDWR);
     this->emulate_format = emulate_fmt;
     if(fd < 0) {
         cout << "Can not open " << devname << "device!" << endl;
         return false;
     }
     if(emulate_fmt) {
         int fd2 = v4l2_fd_open(fd, V4L2_ENABLE_ENUM_FMT_EMULATION);
         if(fd2 < 0) {
             cout << "Cannot use libv4l2 wrapper for " << devname << "!" << endl;
             emulate_fmt = false;
         }
     }
     struct v4l2_capability cap;
     if(!query_capability(&cap)) {
         cout << devname << " is not a V4L2 device!" << endl;
         if(emulate_fmt) v4l2_close(fd);
          else close(fd);
         return false;
     }
     v4lconv = v4lconvert_create(fd);
     if(!v4lconv) {
         close_device();
         return false;
     }
     status |= OPENED;
     return true;
 }
query_buffer() [1/3]
bool v4lcap::query_buffer (struct v4l2_buffer * buffer)
Query buffers to camera.
Parameters
buffer
Returns
true
false
Definition at line 120 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by init_mmap(), query_buffer(), and start_capturing().
{
     int r = xioctl(fd, VIDIOC_QUERYBUF, buffer);
     if(r >= 0) return true;
     perror("VIDIOC_QUERYBUF");
     return false;
 }
query_buffer() [2/3]
bool v4lcap::query_buffer (struct v4l2_buffer * buf, unsigned int type, unsigned int memory, unsigned int index)
Definition at line 112 of file v4lcap.cpp.
References query_buffer().
{
     buf->type = type;
     buf->memory = memory;
     buf->index = index;
     return query_buffer(buf);
 }
query_buffer() [3/3]
bool v4lcap::query_buffer (struct v4l2_buffer * buf, enum v4l2_buf_type type, enum v4l2_memory memory, unsigned int index)
Definition at line 104 of file v4lcap.cpp.
References query_buffer().
{
     buf->type = type;
     buf->memory = memory;
     buf->index = index;
     return query_buffer(buf);
 }
query_capability()
bool v4lcap::query_capability (struct v4l2_capability * cap)
Verify query lenght capability.
Parameters
cap
Returns
true
false
Definition at line 485 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_cb_device_changed(), and open_device().
{
     return xioctl(fd, VIDIOC_QUERYCAP, cap) >= 0;
 }
query_control()
bool v4lcap::query_control (struct v4l2_queryctrl * qctrl)
Query control options.
Parameters
qctrl
Returns
true
false
Definition at line 542 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by enum_control_default(), enum_control_private_base(), enum_control_user_base(), and show_controls().
{
     return xioctl(fd, VIDIOC_QUERYCTRL, qctrl) >= 0;
 }
query_control_menu()
bool v4lcap::query_control_menu (struct v4l2_querymenu * qmenu)
Query control menu.
Parameters
qmenu
Returns
true
false
Definition at line 546 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by enum_control_menu().
{
     return xioctl(fd, VIDIOC_QUERYMENU, qmenu) >= 0;
 }
request_buffers() [1/2]
bool v4lcap::request_buffers (struct v4l2_requestbuffers * req_buff, int nbuffers, enum v4l2_memory memory, enum v4l2_buf_type type)
Request buffers allocation from SO.
Parameters
req_buff
nbuffers
v4l2_memory
v4l2_buf_type
Returns
true
false
Definition at line 560 of file v4lcap.cpp.
Referenced by request_buffers_mmap().
{
     req_buff->reserved[0] = 0;
     req_buff->reserved[1] = 0;
     req_buff->count = nbuffers;
     req_buff->memory = memory;
     req_buff->type = type;
     return request_buffers(req_buff);
 }
request_buffers() [2/2]
bool v4lcap::request_buffers (struct v4l2_requestbuffers * req_buff)
Definition at line 550 of file v4lcap.cpp.
References fd, and xioctl().
{
     int r = xioctl(fd, VIDIOC_REQBUFS, req_buff);
     if(r >= 0) return true;
     perror("VIDIOC_REQBUFS");
     return false;
 }
request_buffers_mmap()
bool v4lcap::request_buffers_mmap (struct v4l2_requestbuffers * req_buff, int nbuffers)
Definition at line 570 of file v4lcap.cpp.
References request_buffers().
Referenced by init_mmap(), and uninit_mmap().
{
     return request_buffers(req_buff, nbuffers, V4L2_MEMORY_MMAP, V4L2_BUF_TYPE_VIDEO_CAPTURE);
 }
set_control()
bool v4lcap::set_control (int ctrl_id, int value)
Set the control object.
Parameters
ctrl_id
value
Returns
true
false
Definition at line 794 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__set_control(), VSSS_GUI::V4LInterface::__set_control_hscale(), and jsonSaveManager::load_camera().
{
     struct v4l2_control ctrl;
     ctrl.id = ctrl_id;
     ctrl.value = value;
     return xioctl(fd, VIDIOC_S_CTRL, &ctrl) >= 0;
 }
set_format()
bool v4lcap::set_format (struct v4l2_format * fmt)
Definition at line 712 of file v4lcap.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_S_FMT, fmt) >= 0;
 }
set_frame_interval()
bool v4lcap::set_frame_interval (struct v4l2_fract & fract)
Set the frame interval object.
Parameters
fract Time fraction to be set
Returns
true If time interval is set
false If cannot set time interval
Definition at line 780 of file v4lcap.cpp.
References fd, get_stream_parameter(), and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_cb_frame_interval_changed().
{
     v4l2_streamparm parm;
     if(!get_stream_parameter(&parm, V4L2_BUF_TYPE_VIDEO_CAPTURE))
         return false;
     if(!(parm.parm.capture.capability & V4L2_CAP_TIMEPERFRAME))
         return false;
     parm.parm.capture.timeperframe = fract;
     return xioctl(fd, VIDIOC_S_PARM, &parm) >= 0;
 }
set_frame_size()
bool v4lcap::set_frame_size (int width, int height, unsigned int type)
Set the frame size object.
Parameters
width Frame width
height Frame height
type Frame type
Returns
true If frame is set
false if cannot set frame
Definition at line 768 of file v4lcap.cpp.
References fd, get_format(), CONST::height, CONST::width, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and VSSS_GUI::V4LInterface::__event_cb_frame_size_changed().
{
     struct v4l2_format fmt;
     if(!get_format(&fmt, type))
         return false;
     fmt.fmt.pix.width = width;
     fmt.fmt.pix.height = height;
     return xioctl(fd, VIDIOC_S_FMT, &fmt) >= 0;
 }
set_input()
bool v4lcap::set_input (int index)
Set the input object.
Parameters
index ID of selected camera
Returns
true If querying is capable
false If querying is not capable
Definition at line 704 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_cb_input_changed().
{
     return xioctl(fd, VIDIOC_S_INPUT, &index) >= 0;
 }
set_pixel_format()
bool v4lcap::set_pixel_format (unsigned int pixel_format)
Set the pixel format object.
Parameters
pixel_format Pixel format param to set on capturing
Returns
true If format is set
false If cannot set the format
Definition at line 757 of file v4lcap.cpp.
References fd, get_format(), and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_cb_format_desc_changed().
{
     struct v4l2_format fmt;
     if(!get_format(&fmt, V4L2_BUF_TYPE_VIDEO_CAPTURE))
         return false;
     fmt.fmt.pix.pixelformat = pixel_format;
     return xioctl(fd, VIDIOC_S_FMT, &fmt) >= 0;
 }
set_standard()
bool v4lcap::set_standard (v4l2_std_id std_id)
Set the standard object.
Parameters
std_id This type is a set, each bit representing another video standard.
See also
https://www.linuxtv.org/downloads/v4l-dvb-apis-old/vidioc-enumstd.html#v4l2-std-id
Returns
true If querying is capable
false If querying is not capable
Definition at line 708 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by VSSS_GUI::V4LInterface::__event_cb_standard_changed().
{
     return xioctl(fd, VIDIOC_S_STD, &std_id) >= 0;
 }
show_controls()
bool v4lcap::show_controls ()
Returns
true
false
Definition at line 803 of file v4lcap.cpp.
References query_control().
{
     struct v4l2_queryctrl qctrl;
     cout << "=== Enumeratin controls via V4L2_CTRL_FLAG_NEXT_CTRL: ===" << endl;
     qctrl.id = V4L2_CTRL_FLAG_NEXT_CTRL;
     while(query_control(&qctrl)) {
         if((qctrl.flags & V4L2_CTRL_FLAG_DISABLED) != 0)
             cout << "[ Disabled ] " << qctrl.name;
         cout << "Control: " << qctrl.name << endl;
         qctrl.id |= V4L2_CTRL_FLAG_NEXT_CTRL;
     }
     cout << "=== Enumeratin controls via V4L2_CID_BASE until to V4L2_CID_LASTP1: ===" << endl;
     for(qctrl.id = V4L2_CID_BASE; qctrl.id <= V4L2_CID_LASTP1; ++qctrl.id) {
         if(!query_control(&qctrl))
             continue;
         if((qctrl.flags & V4L2_CTRL_FLAG_DISABLED) != 0) {
             cout << "[ Disabled ] " << qctrl.name;
         }
         cout << "Control: " << qctrl.name << endl;
     }
     cout << "=== Enumeratin controls via V4L2_CID_PRIVATE_BASE: ===" << endl;
     for(qctrl.id = V4L2_CID_PRIVATE_BASE; query_control(&qctrl); ++qctrl.id) {
         if((qctrl.flags & V4L2_CTRL_FLAG_DISABLED) != 0)
             cout << "[ Disabled ] " << qctrl.name;
         cout << "Control: " << qctrl.name << endl;
     }
     return true;
 }
start_capturing() [1/2]
bool v4lcap::start_capturing (enum memory_type mem_type, int nbuffers)
This method starts capturing and streaming from opened device passing memory type and number of buffers used.
Parameters
memory_type Defines memory type.
nbuffers Number of buffers used to streaming from camera.
Returns
true Streaming from camera is openned.
false Streaming cannot be started.
Definition at line 256 of file v4lcap.cpp.
References enqueue_buff(), format_dest, init_mmap(), MEM_MMAP, MEM_READ, MEM_USER, needs_convert, query_buffer(), reqbuf, streamon(), and v4lconv.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked().
{
     switch(mem_type) {
         case MEM_MMAP:
             if (!init_mmap(nbuffers)) return false;
             break;
         case MEM_USER:
         case MEM_READ:
         default:
             return false;
     }
     if(!init_mmap(nbuffers)) return false;
     // = Enqueue all buffers ===================================================
     for(unsigned int i = 0; i < reqbuf.count; ++i) {
         struct v4l2_buffer buffer = { 0 };
         if(!enqueue_buff(&buffer, reqbuf.type, reqbuf.memory, i))
             std::cout << "Can't enqueue buffer " << i << std::endl;
         if(!query_buffer(&buffer, reqbuf.type, reqbuf.memory, i))
             std::cout << "Can't request buffer " << i << std::endl;
         if(buffer.flags & V4L2_BUF_FLAG_QUEUED) {
             std::cout << "Buffer " << i << " queued!" << std::endl;
         } else {
             std::cout << "Buffer " << i << " NOT queued!" << std::endl;
         }
     }
     this->format_dest = this->format_src;
     format_dest.fmt.pix.pixelformat = V4L2_PIX_FMT_RGB24;
     if(format_src.fmt.pix.pixelformat != V4L2_PIX_FMT_RGB24) {
         needs_convert = true;
     } else {
         needs_convert = false;
     }
     if(needs_convert) {
         v4l2_format copy = format_src;
         v4lconvert_try_format(v4lconv, &format_dest, &format_src);
         // v4lconvert_try_format sometimes modifies the source format if it thinks
         // that there is a better format available. Restore our selected source
         // format since we do not want that happening.
         format_src = copy;
     }
     return streamon(V4L2_BUF_TYPE_VIDEO_CAPTURE);
 }
start_capturing() [2/2]
bool v4lcap::start_capturing ()
This method starts capturing and streaming from opened device.
Returns
true Streaming from camera is openned.
false Streaming cannot be started.
Definition at line 307 of file v4lcap.cpp.
References debug_error, debug_log, enqueue_buff(), format_dest, needs_convert, query_buffer(), reqbuf, streamon(), and v4lconv.
{
     // = Enqueue all buffers ===================================================
     for(unsigned int i = 0; i < reqbuf.count; ++i) {
         struct v4l2_buffer buffer = { 0 };
         if (!enqueue_buff(&buffer, reqbuf.type, reqbuf.memory, i))
             debug_error("Can't enqueue buffer " + std::to_string(i));
         if(!query_buffer(&buffer, reqbuf.type, reqbuf.memory, i))
             debug_error("Can't request buffer " + std::to_string(i));
         if(buffer.flags & V4L2_BUF_FLAG_QUEUED) {
             debug_log("Buffer " + std::to_string(i) + " queued!");
         } else {
             debug_error("Buffer " + std::to_string(i) + " NOT queued!");
         }
     }
     this->format_dest = this->format_src;
     format_dest.fmt.pix.pixelformat = V4L2_PIX_FMT_RGB24;
     if(format_src.fmt.pix.pixelformat != V4L2_PIX_FMT_RGB24) {
         needs_convert = true;
     } else {
         needs_convert = false;
     }
     if(needs_convert) {
         v4l2_format copy = format_src;
         v4lconvert_try_format(v4lconv, &format_dest, &format_src);
         // v4lconvert_try_format sometimes modifies the source format if it thinks
         // that there is a better format available. Restore our selected source
         // format since we do not want that happening.
         format_src = copy;
     }
     return streamon(V4L2_BUF_TYPE_VIDEO_CAPTURE);
 }
stop_capturing()
bool v4lcap::stop_capturing ()
Closes capturing query.
Returns
true Closed successfully
false Something goes wrong
Definition at line 433 of file v4lcap.cpp.
References streamoff().
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked().
{
     return streamoff(V4L2_BUF_TYPE_VIDEO_CAPTURE);
 }
streamoff() [1/2]
bool v4lcap::streamoff (enum v4l2_buf_type type)
Query stream to terminate.
Parameters
v4l2_buf_type Buffer type off running stream
Returns
true If all succeds
false If something goes wrong with query
Definition at line 425 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by close_device(), stop_capturing(), and streamoff().
{
     return xioctl(fd, VIDIOC_STREAMOFF, &type) >= 0;
 }
streamoff() [2/2]
bool v4lcap::streamoff (int type)
Definition at line 429 of file v4lcap.cpp.
References streamoff().
{
     return streamoff((enum v4l2_buf_type) type);
 }
streamon() [1/2]
bool v4lcap::streamon (enum v4l2_buf_type type)
Query stream to initiate.
Parameters
v4l2_buf_type Buffer type of streaming
Returns
true If all succeeds
false If something goes wrong with stream query
Definition at line 248 of file v4lcap.cpp.
References fd, and xioctl().
Referenced by start_capturing(), and streamon().
{
     return xioctl(fd, VIDIOC_STREAMON, &type) >= 0;
 }
streamon() [2/2]
bool v4lcap::streamon (int type)
Definition at line 252 of file v4lcap.cpp.
References streamon().
{
     return streamon((enum v4l2_buf_type) type);
 }
uninit_mmap()
bool v4lcap::uninit_mmap ()
Free all requested buffers.
Returns
true Free all buffers
false Nothing freed =,(
Definition at line 437 of file v4lcap.cpp.
References buffers, v4lcap::buffer_holder::buffs, emulate_format, v4lcap::buffer::length, v4lcap::buffer_holder::qtd, reqbuf, request_buffers_mmap(), and v4lcap::buffer::start.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and close_device().
{
     for(unsigned int i = 0; i < reqbuf.count; i++) {
         if(emulate_format) {
             if(-1 == v4l2_munmap(buffers.buffs[i].start, buffers.buffs[i].length))
                 return false;
         } else {
             if (-1 == munmap(buffers.buffs[i].start, buffers.buffs[i].length))
                 return false;
         }
     }
     // = free all requested buffers ================================================
     if(!request_buffers_mmap(&reqbuf, 1))
         std::cout << "Can't request 1 mmap buffers.\n";
     if(!request_buffers_mmap(&reqbuf, 0))
         std::cout << "Can't request 0 mmap buffers.\n";
     free(buffers.buffs);
     buffers.buffs = 0;
     buffers.qtd = 0;
     return true;
 }
xioctl()
int v4lcap::xioctl (int fd, int request, void * arg)
Definition at line 32 of file v4lcap.cpp.
References emulate_format.
Referenced by dequeue_buff(), enqueue_buff(), enum_audio_input(), enum_audio_output(), enum_frame_interval(), enum_frame_size(), enum_image_format(), enum_video_input(), enum_video_output(), enum_video_standard(), get_control(), get_format(), get_input(), get_input_index(), get_standard(), get_standard_id(), get_stream_parameter(), query_buffer(), query_capability(), query_control(), query_control_menu(), request_buffers(), set_control(), set_format(), set_frame_interval(), set_frame_size(), set_input(), set_pixel_format(), set_standard(), streamoff(), and streamon().
{
     int r;
     if(emulate_format) r = v4l2_ioctl(fd, request, arg);
     else r = ioctl(fd, request, arg);
     return r;
 }
Field Documentation
buffers
struct buffer_holder v4lcap::buffers
Definition at line 66 of file v4lcap.hpp.
Referenced by grab_raw(), grab_rgb(), init_mmap(), and uninit_mmap().
emulate_format
bool v4lcap::emulate_format
Definition at line 28 of file v4lcap.hpp.
Referenced by close_device(), init_mmap(), open_device(), uninit_mmap(), and xioctl().
fd
int v4lcap::fd
Definition at line 27 of file v4lcap.hpp.
Referenced by close_device(), dequeue_buff(), enqueue_buff(), enum_audio_input(), enum_audio_output(), enum_frame_interval(), enum_frame_size(), enum_image_format(), enum_video_input(), enum_video_output(), enum_video_standard(), get_control(), get_format(), get_input(), get_input_index(), get_standard(), get_standard_id(), get_stream_parameter(), init_mmap(), is_opened(), open_device(), query_buffer(), query_capability(), query_control(), query_control_menu(), request_buffers(), set_control(), set_format(), set_frame_interval(), set_frame_size(), set_input(), set_pixel_format(), set_standard(), streamoff(), and streamon().
format_dest
struct v4l2_format format_src v4lcap::format_dest
Video format that the cam's video should be returned, if not null. If format is not supported, this will change to another one. Gets the format from de camera. Destination format of the video.
Definition at line 37 of file v4lcap.hpp.
Referenced by grab_rgb(), start_capturing(), and CamCap::start_signal().
needs_convert
bool v4lcap::needs_convert
Definition at line 29 of file v4lcap.hpp.
Referenced by grab_rgb(), and start_capturing().
reqbuf
struct v4l2_requestbuffers v4lcap::reqbuf
Definition at line 48 of file v4lcap.hpp.
Referenced by init_mmap(), start_capturing(), and uninit_mmap().
status
unsigned int v4lcap::status
Definition at line 54 of file v4lcap.hpp.
Referenced by close_device(), and open_device().
v4lconv
struct v4lconvert_data* v4lcap::v4lconv
Data obtained from camera.
Definition at line 42 of file v4lcap.hpp.
Referenced by close_device(), grab_rgb(), open_device(), and start_capturing().
The documentation for this class was generated from the following files:
src/capture/v4lcap.hpp
src/capture/v4lcap.cpp