VSSS-INF: CPUTimer Class Reference
CPUTimer Class Reference
#include <cpuTimer.hpp>
Public Member Functions
CPUTimer ()
double getCPUCurrSecs ()
double getCPUTotalSecs ()
double getCronoCurrSecs ()
double getCronoTotalSecs ()
bool start ()
bool stop ()
void reset ()
void operator+= (CPUTimer t)
void increaseCPUTotalSecs (double s)
Private Member Functions
double getCPUTime ()
double getRealTime ()
Private Attributes
double CPUTStart
double CPUTStop
double CronoTStart
double CronoTStop
double CPUCurrSecs
double CPUTotalSecs
double CronoCurrSecs
double CronoTotalSecs
bool gottime
bool started
Detailed Description
Definition at line 23 of file cpuTimer.hpp.
Constructor & Destructor Documentation
CPUTimer()
CPUTimer::CPUTimer ()
Definition at line 11 of file cpuTimer.cpp.
References CPUCurrSecs, CPUTotalSecs, CronoCurrSecs, CronoTotalSecs, and started.
                    {
     started = false;
     CPUCurrSecs = 0;
     CPUTotalSecs = 0;
     CronoCurrSecs = 0;
     CronoTotalSecs = 0;
 }
Member Function Documentation
getCPUCurrSecs()
double CPUTimer::getCPUCurrSecs ()
Definition at line 19 of file cpuTimer.cpp.
References CPUCurrSecs.
Referenced by operator+=().
{
     return CPUCurrSecs;
 }
getCPUTime()
double CPUTimer::getCPUTime () private
Returns the amount of CPU time used by the current process, in seconds, or -1.0 if an error occurred.
Definition at line 87 of file cpuTimer.cpp.
Referenced by start(), and stop().
{
     #if defined(_POSIX_TIMERS) && (_POSIX_TIMERS > 0)
     /* Prefer high-res POSIX timers, when available. */
     clockid_t id;
     struct timespec ts;
     #if _POSIX_CPUTIME > 0
     /* Clock ids vary by OS.  Query the id, if possible. */
     if (clock_getcpuclockid( 0, &id ) == -1)
     #endif
     #if defined(CLOCK_PROCESS_CPUTIME_ID)
     /* Use known clock id for AIX, Linux, or Solaris. */
     id = CLOCK_PROCESS_CPUTIME_ID;
     #elif defined(CLOCK_VIRTUAL)
     /* Use known clock id for BSD or HP-UX. */
     id = CLOCK_VIRTUAL;
     #else
     id = (clockid_t) - 1;
     #endif
     if ((id != (clockid_t) - 1) && (clock_gettime( id, &ts ) != -1))
         return ((double) ts.tv_sec + (double) ts.tv_nsec / 1000000000.0);
     #endif
     #if defined(RUSAGE_SELF)
     struct rusage rusage;
     if (getrusage( RUSAGE_SELF, &rusage ) != -1)
         return ((double) rusage.ru_utime.tv_sec + (double) rusage.ru_utime.tv_usec / 1000000.0);
     #endif
     /* Failed. */
     return -1.0;
 }
getCPUTotalSecs()
double CPUTimer::getCPUTotalSecs ()
Definition at line 23 of file cpuTimer.cpp.
References CPUTotalSecs.
Referenced by operator+=().
{
     return CPUTotalSecs;
 }
getCronoCurrSecs()
double CPUTimer::getCronoCurrSecs ()
Definition at line 27 of file cpuTimer.cpp.
References CronoCurrSecs.
Referenced by operator+=().
{
     return CronoCurrSecs;
 }
getCronoTotalSecs()
double CPUTimer::getCronoTotalSecs ()
Definition at line 31 of file cpuTimer.cpp.
References CronoTotalSecs.
Referenced by CamCap::capture_and_show(), and operator+=().
{
     return CronoTotalSecs;
 }
getRealTime()
double CPUTimer::getRealTime () private
Returns the amount of real time used by the current process, in seconds, or -1.0 if an error occurred.
Definition at line 136 of file cpuTimer.cpp.
Referenced by start(), and stop().
{
     #if defined(_POSIX_TIMERS) && (_POSIX_TIMERS > 0)
     struct timespec ts;
     #if defined(CLOCK_MONOTONIC_PRECISE)
     /* BSD. --------------------------------------------- */
     const clockid_t id = CLOCK_MONOTONIC_PRECISE;
     #elif defined(CLOCK_MONOTONIC_RAW)
     /* Linux. ------------------------------------------- */
     const clockid_t id = CLOCK_MONOTONIC_RAW;
     #elif defined(CLOCK_HIGHRES)
     /* Solaris. ----------------------------------------- */
     const clockid_t id = CLOCK_HIGHRES;
     #elif defined(CLOCK_MONOTONIC)
     /* AIX, BSD, Linux, POSIX, Solaris. ----------------- */
     const clockid_t id = CLOCK_MONOTONIC;
     #elif defined(CLOCK_REALTIME)
     /* AIX, BSD, HP-UX, Linux, POSIX. ------------------- */
     const clockid_t id = CLOCK_REALTIME;
     #else
     /* Unknown. */
     const clockid_t id = (clockid_t) - 1;
     #endif
     if ((id != (clockid_t) - 1) && (clock_gettime( id, &ts ) != -1))
         return ((double) ts.tv_sec + (double) ts.tv_nsec / 1000000000.0);
     #elif defined(__MACH__) && defined(__APPLE__)
     /* OSX. --------------------------------------------- */
     static double timeConvert = 0.0;
     if (timeConvert == 0.0) {
         mach_timebase_info_data_t timeBase;
         (void) mach_timebase_info( &timeBase );
         timeConvert = (double) timeBase.numer / (double) timeBase.denom / 1000000000.0;
     }
     return (double) mach_absolute_time( ) * timeConvert;
     #else
     /* Failed. */
     return -1.0;
     #endif
     /* To avoid compilation warnings only!!! */
     return -1.0;
 }
increaseCPUTotalSecs()
void CPUTimer::increaseCPUTotalSecs (double s) inline
Definition at line 57 of file cpuTimer.hpp.
References CPUTotalSecs.
{
         CPUTotalSecs += s;
     };
operator+=()
void CPUTimer::operator+= (CPUTimer t)
Definition at line 76 of file cpuTimer.cpp.
References CPUCurrSecs, CPUTotalSecs, CronoCurrSecs, CronoTotalSecs, getCPUCurrSecs(), getCPUTotalSecs(), getCronoCurrSecs(), and getCronoTotalSecs().
{
     CPUCurrSecs += t.getCPUCurrSecs();
     CPUTotalSecs += t.getCPUTotalSecs();
     CronoCurrSecs += t.getCronoCurrSecs();
     CronoTotalSecs += t.getCronoTotalSecs();
 }
reset()
void CPUTimer::reset ()
Definition at line 68 of file cpuTimer.cpp.
References CPUCurrSecs, CPUTotalSecs, CronoCurrSecs, CronoTotalSecs, and started.
Referenced by CamCap::capture_and_show().
                      {
     started = false;
     CPUCurrSecs = 0;
     CPUTotalSecs = 0;
     CronoCurrSecs = 0;
     CronoTotalSecs = 0;
 }
start()
bool CPUTimer::start ()
Definition at line 35 of file cpuTimer.cpp.
References CPUCurrSecs, CPUTStart, CronoCurrSecs, CronoTStart, getCPUTime(), getRealTime(), gottime, and started.
Referenced by CamCap::capture_and_show().
                      {
     bool status = true;
     CPUCurrSecs = 0;
     CronoCurrSecs = 0;
     CPUTStart = getCPUTime();
     CronoTStart = getRealTime();
     gottime = false;
     started = status;
     return (status);
 }
stop()
bool CPUTimer::stop ()
Definition at line 49 of file cpuTimer.cpp.
References CPUTotalSecs, CPUTStart, CPUTStop, CronoTotalSecs, CronoTStart, CronoTStop, getCPUTime(), getRealTime(), and started.
Referenced by CamCap::capture_and_show().
                     {
     bool status = true;
     if (started) {
         CPUTStop = getCPUTime();
         CronoTStop = getRealTime();
         CPUTotalSecs += CPUTStop - CPUTStart;
         CronoTotalSecs += CronoTStop - CronoTStart;
     } else {
         std::cout << "CPUTimer::stop(): called without calling CPUTimer::start() first!\n";
         status = false;
     }
     started = false;
     return status;
 }
Field Documentation
CPUCurrSecs
double CPUTimer::CPUCurrSecs private
Definition at line 72 of file cpuTimer.hpp.
Referenced by CPUTimer(), getCPUCurrSecs(), operator+=(), reset(), and start().
CPUTotalSecs
double CPUTimer::CPUTotalSecs private
Definition at line 75 of file cpuTimer.hpp.
Referenced by CPUTimer(), getCPUTotalSecs(), increaseCPUTotalSecs(), operator+=(), reset(), and stop().
CPUTStart
double CPUTimer::CPUTStart private
Definition at line 59 of file cpuTimer.hpp.
Referenced by start(), and stop().
CPUTStop
double CPUTimer::CPUTStop private
Definition at line 64 of file cpuTimer.hpp.
Referenced by stop().
CronoCurrSecs
double CPUTimer::CronoCurrSecs private
Definition at line 78 of file cpuTimer.hpp.
Referenced by CPUTimer(), getCronoCurrSecs(), operator+=(), reset(), and start().
CronoTotalSecs
double CPUTimer::CronoTotalSecs private
Definition at line 81 of file cpuTimer.hpp.
Referenced by CPUTimer(), getCronoTotalSecs(), operator+=(), reset(), and stop().
CronoTStart
double CPUTimer::CronoTStart private
Definition at line 65 of file cpuTimer.hpp.
Referenced by start(), and stop().
CronoTStop
double CPUTimer::CronoTStop private
Definition at line 66 of file cpuTimer.hpp.
Referenced by stop().
gottime
bool CPUTimer::gottime private
Definition at line 83 of file cpuTimer.hpp.
Referenced by start().
started
bool CPUTimer::started private
Definition at line 84 of file cpuTimer.hpp.
Referenced by CPUTimer(), reset(), start(), and stop().
The documentation for this class was generated from the following files:
src/aux/cpuTimer.hpp
src/aux/cpuTimer.cpp