VSSS-INF: RobotGUI Class Reference
RobotGUI Class Reference
#include <robotGUI.hpp>
Public Member Functions
RobotGUI ()
void enable_buttons ()
void disable_buttons ()
void update_robot_functions ()
void update_speed_sliders ()
void update_speed_progressBars ()
void update_ids ()
Private Member Functions
void create_functions_frame ()
void create_speeds_frame ()
void create_ids_frame ()
void event_robots_function_done_bt_signal_clicked ()
void event_robots_function_edit_bt_signal_clicked ()
void event_robots_speed_edit_bt_signal_pressed ()
void event_robots_speed_done_bt_signal_clicked ()
void event_robots_id_done_bt_signal_clicked ()
void event_robots_id_edit_bt_signal_pressed ()
Private Attributes
double robots_speed_tmp [Robots::SIZE]
int robots_function_tmp [Robots::SIZE]
bool robots_speed_edit_flag = false
bool robots_function_edit_flag = false
bool robots_id_edit_flag = false
Gtk::Grid speeds_grid
Gtk::Frame robots_function_fm
Gtk::Frame robots_speed_fm
Gtk::VBox robots_function_vbox
Gtk::VBox robots_speed_vbox
Gtk::VBox robots_speed_slider_vbox [Robots::SIZE]
Gtk::HBox robots_function_hbox [Robots::SIZE+1]
Gtk::HBox robots_speed_hbox
Gtk::Frame robots_id_fm
Gtk::VBox robots_id_vbox
Gtk::HBox robots_id_hbox [Robots::SIZE+1]
Gtk::Button robots_id_edit_bt
Gtk::Button robots_id_done_bt
Gtk::Entry robots_id_box [Robots::SIZE]
Glib::ustring robots_id_tmp [Robots::SIZE]
Gtk::Button robots_speed_edit_bt
Gtk::Button robots_speed_done_bt
Gtk::Button robots_function_edit_bt
Gtk::Button robots_function_done_bt
Gtk::ComboBoxText cb_robot_function [Robots::SIZE]
Gtk::HScale robots_speed_hscale [Robots::SIZE]
Gtk::ProgressBar robots_speed_progressBar [Robots::SIZE]
Detailed Description
Definition at line 17 of file robotGUI.hpp.
Constructor & Destructor Documentation
RobotGUI()
RobotGUI::RobotGUI ()
Constructor of a RobotGUI object
Creates all robot's configuration frames and initialize data.
Definition at line 4 of file robotGUI.cpp.
References create_functions_frame(), create_ids_frame(), and create_speeds_frame().
                    {
     create_functions_frame();
     create_speeds_frame();
     create_ids_frame();
 }
Member Function Documentation
create_functions_frame()
void RobotGUI::create_functions_frame () private
Generates a Robot Functions frame
Definition at line 68 of file robotGUI.cpp.
References cb_robot_function, event_robots_function_done_bt_signal_clicked(), event_robots_function_edit_bt_signal_clicked(), Robots::get_role(), robots_function_done_bt, robots_function_edit_bt, robots_function_fm, robots_function_hbox, robots_function_vbox, and Robots::SIZE.
Referenced by RobotGUI().
{
     Gtk::Label *label;
     std::string function[Robots::SIZE];
     pack_start(robots_function_fm, false, true, 5); // coloca o frame no começo da aba
     robots_function_fm.add(robots_function_vbox); // adiciona um vbox
     // coloca os botões na primeira hbox
     robots_function_hbox[0].pack_start(robots_function_edit_bt, false, true, 5); // alinha pro começo
     robots_function_hbox[0].pack_end(robots_function_done_bt, false, true, 5); // alinha pro final
     // coloca essa hbox no começo da vbox
     robots_function_vbox.pack_start(robots_function_hbox[0], false, true, 5);
     // seta os textos das possíveis funções
     for(int i = 0; i < Robots::SIZE; i++)
         function[i].clear();
     function[0].append("Goalkeeper");
     function[1].append("Defense");
     function[2].append("Attack");
     // pra cada robô representado
     for(int i = 0; i < Robots::SIZE; i++) {
         // configura o rótulo
         switch(i) {
             case 1:
                 label = new Gtk::Label("Robot 2:");
                 break;
             case 2:
                 label = new Gtk::Label("Robot 3:");
                 break;
             default:
                 label = new Gtk::Label("Robot 1:");
         }
         // adiciona as opções de papel pro seletor de cada robo
         for(int j = 0; j < Robots::SIZE; j++)
             cb_robot_function[i].append(function[j]);
         // seleciona uma opção padrão
         cb_robot_function[i].set_active_text(function[Robots::get_role(i)]);
         // coloca o rótulo e o seletor na hbox que tá dentro da vbox
         robots_function_hbox[i+1].pack_start(*label, false, true, 5);
         robots_function_hbox[i+1].pack_start(cb_robot_function[i], false, true, 5);
         // coloca essa hbox dentro da vbox
         robots_function_vbox.pack_start(robots_function_hbox[i+1], false, true, 5);
     }
     // configuração inicial da interface
     // coloca as labels
     robots_function_fm.set_label("Robot Functions"); // nome que fica flutuando no frame
     robots_function_edit_bt.set_label("Edit");
     robots_function_done_bt.set_label("Done");
     // deixa os botões não clicáveis
     robots_function_done_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_function_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
     for (auto &i : cb_robot_function)
         i.set_state(Gtk::STATE_INSENSITIVE);
     // amarra eventos
     robots_function_edit_bt.signal_clicked().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_function_edit_bt_signal_clicked));
     robots_function_done_bt.signal_clicked().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_function_done_bt_signal_clicked));
 }
create_ids_frame()
void RobotGUI::create_ids_frame () private
Generates IDs frame
Definition at line 37 of file robotGUI.cpp.
References event_robots_id_done_bt_signal_clicked(), event_robots_id_edit_bt_signal_pressed(), Robots::get_ID(), robots_id_box, robots_id_done_bt, robots_id_edit_bt, robots_id_fm, robots_id_hbox, robots_id_vbox, and Robots::SIZE.
Referenced by RobotGUI().
{
     pack_start(robots_id_fm, false, true, 5);
     robots_id_fm.set_label("IDs");
     robots_id_fm.add(robots_id_vbox);
     robots_id_vbox.pack_start(robots_id_hbox[0], false, true, 5);
     robots_id_hbox[0].pack_start(robots_id_edit_bt, false, true, 5);
     robots_id_hbox[0].pack_end(robots_id_done_bt, false, true, 5);
     robots_id_edit_bt.set_label("Edit");
     robots_id_done_bt.set_label("Done");
     for(int i = 0; i < Robots::SIZE; i++) {
         Gtk::Label *label = new Gtk::Label("Robot " + std::to_string(i+1) + ": ");
         robots_id_hbox[i+1].pack_start(*label, false, true, 5);
         robots_id_hbox[i+1].pack_start(robots_id_box[i], false, true, 5);
         robots_id_vbox.pack_start(robots_id_hbox[i+1], false, true, 5);
         robots_id_box[i].set_max_length(1);
         robots_id_box[i].set_width_chars(2);
         robots_id_box[i].set_text(string(1, Robots::get_ID(i)));
         robots_id_box[i].set_state(Gtk::STATE_INSENSITIVE);
     }
     robots_id_done_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_id_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_id_edit_bt.signal_pressed().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_id_edit_bt_signal_pressed));
     robots_id_done_bt.signal_clicked().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_id_done_bt_signal_clicked));
 }
create_speeds_frame()
void RobotGUI::create_speeds_frame () private
Generates a Speeds control frame
Definition at line 141 of file robotGUI.cpp.
References event_robots_speed_done_bt_signal_clicked(), event_robots_speed_edit_bt_signal_pressed(), Robots::get_default_role_velocity(), robots_speed_done_bt, robots_speed_edit_bt, robots_speed_fm, robots_speed_hbox, robots_speed_hscale, robots_speed_progressBar, robots_speed_slider_vbox, robots_speed_vbox, Robots::SIZE, and speeds_grid.
Referenced by RobotGUI().
{
     // coloca o frame das velocidades na aba dos robos
     pack_start(robots_speed_fm, false, true, 5);
     robots_speed_fm.add(robots_speed_vbox); // adiciona uma vbox
     // adiciona os botões de edit numa hbox
     robots_speed_hbox.pack_start(robots_speed_edit_bt, false, true, 5);
     robots_speed_hbox.pack_end(robots_speed_done_bt, false, true, 5);
     // coloca essa hbox na vbox principal
     robots_speed_vbox.pack_start(robots_speed_hbox, false, true, 5);
     // coloca a grid das velocidades nessa vbox também
     robots_speed_vbox.pack_start(speeds_grid, false, true, 0);
     // configura a grade
     speeds_grid.set_border_width(10);
     speeds_grid.set_column_spacing(5);
     speeds_grid.set_halign(Gtk::ALIGN_CENTER);
     // pra cada robô
     for(int i = 0; i < Robots::SIZE; i++) {
         Gtk::Label * label; // ponteiro pq não deve ser destruído quando essa função acabar
         // seleciona a label correspondente
         switch(i) {
             case 1:
                 label = new Gtk::Label("DEF");
                 break;
             case 2:
                 label = new Gtk::Label("ATK");
                 break;
             default:
                 label = new Gtk::Label("GK");
         }
         // configura os sliders
         robots_speed_hscale[i].set_digits(1);
         robots_speed_hscale[i].set_increments(0.1,1);
         robots_speed_hscale[i].set_range(0,1.4);
         robots_speed_hscale[i].set_size_request(100,-1);
         robots_speed_hscale[i].set_value(Robots::get_default_role_velocity(i));
         robots_speed_hscale[i].set_state(Gtk::STATE_INSENSITIVE);
         // configura as barras de progresso
         robots_speed_progressBar[i].set_halign(Gtk::ALIGN_CENTER);
         robots_speed_progressBar[i].set_valign(Gtk::ALIGN_CENTER);
         robots_speed_progressBar[i].set_text(std::to_string(Robots::get_default_role_velocity(i)).substr(0,4));
         robots_speed_progressBar[i].set_show_text(true);
         robots_speed_progressBar[i].set_fraction(Robots::get_default_role_velocity(i)/1.4);
         // coloca o slider e a barra de progresso que representa a velocidade atual em um vbox exclusivo do robô
         robots_speed_slider_vbox[i].pack_start(robots_speed_hscale[i], false, true, 0);
         robots_speed_slider_vbox[i].pack_start(robots_speed_progressBar[i], false, true, 0);
         // adiciona o rótulo e o slider na hbox do robô
         speeds_grid.attach(*label, i, 0, 1, 1);
         speeds_grid.attach(robots_speed_slider_vbox[i], i, 1, 1, 1);
     }
     // configuração inicial
     robots_speed_fm.set_label("Speeds"); // nome do frame
     robots_speed_edit_bt.set_label("Edit"); // botões de edit
     robots_speed_done_bt.set_label("Done"); // e done
     robots_speed_done_bt.set_state(Gtk::STATE_INSENSITIVE); // deixa eles não clicáveis
     robots_speed_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
     // eventos
     robots_speed_edit_bt.signal_pressed().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_speed_edit_bt_signal_pressed));
     robots_speed_done_bt.signal_clicked().connect(sigc::mem_fun(*this, &RobotGUI::event_robots_speed_done_bt_signal_clicked));
 }
disable_buttons()
void RobotGUI::disable_buttons ()
Disables all dynamic buttons and inputs
Definition at line 226 of file robotGUI.cpp.
References robots_function_edit_bt, robots_id_edit_bt, and robots_speed_edit_bt.
Referenced by CamCap::start_signal().
{
     robots_id_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_speed_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_function_edit_bt.set_state(Gtk::STATE_INSENSITIVE);
 }
enable_buttons()
void RobotGUI::enable_buttons ()
Enables all dynamic buttons and inputs
Definition at line 220 of file robotGUI.cpp.
References robots_function_edit_bt, robots_id_edit_bt, and robots_speed_edit_bt.
Referenced by CamCap::start_signal().
{
     robots_id_edit_bt.set_state(Gtk::STATE_NORMAL);
     robots_speed_edit_bt.set_state(Gtk::STATE_NORMAL);
     robots_function_edit_bt.set_state(Gtk::STATE_NORMAL);
 }
event_robots_function_done_bt_signal_clicked()
void RobotGUI::event_robots_function_done_bt_signal_clicked () private
Updates robot's role after Done button is clicked
Definition at line 259 of file robotGUI.cpp.
References cb_robot_function, debug_log, robots_function_done_bt, robots_function_edit_bt, robots_function_edit_flag, Robots::set_role(), and Robots::SIZE.
Referenced by create_functions_frame().
{
     std::string s[Robots::SIZE];
     for(int i = 0; i < Robots::SIZE; i++) {
         s[i] = cb_robot_function[i].get_active_text();
         if (s[i].compare("Goalkeeper") == 0) {
             debug_log("Robot " + to_string(i+1) + ": Goalkeeper.");
             Robots::set_role(i, 0);
         } else if (s[i].compare("Defense") == 0) {
             debug_log("Robot " + to_string(i+1) + ": Defense.");
             Robots::set_role(i, 1);
         } else if (s[i].compare("Attack") == 0) {
             debug_log("Robot " + to_string(i+1) + ": Attack.");
             Robots::set_role(i, 2);
         } else {
             std::cout << "Error: not possible to set robot " << i+1 << " function." << std::endl;
         }
         cb_robot_function[i].set_state(Gtk::STATE_INSENSITIVE);
     }
     robots_function_edit_flag = false;
     robots_function_edit_bt.set_label("Edit");
     robots_function_done_bt.set_state(Gtk::STATE_INSENSITIVE);
 }
event_robots_function_edit_bt_signal_clicked()
void RobotGUI::event_robots_function_edit_bt_signal_clicked () private
Event triggered when robot function's Edit button is clicked
This method may update buttons' label/state and the active element in the combobox
Definition at line 234 of file robotGUI.cpp.
References cb_robot_function, robots_function_done_bt, robots_function_edit_bt, robots_function_edit_flag, robots_function_tmp, and Robots::SIZE.
Referenced by create_functions_frame().
{
     if(!robots_function_edit_flag) {
         robots_function_edit_flag = true;
         robots_function_edit_bt.set_label("Cancel");
         // atualiza interface
         for(int i = 0; i < Robots::SIZE; i++) {
             robots_function_tmp[i] = cb_robot_function[0].get_active_row_number();
             cb_robot_function[i].set_state(Gtk::STATE_NORMAL);
         }
         robots_function_edit_bt.set_state(Gtk::STATE_NORMAL);
         robots_function_done_bt.set_state(Gtk::STATE_NORMAL);
     } else {
         robots_function_edit_flag = false;
         robots_function_edit_bt.set_label("Edit");
         robots_function_done_bt.set_state(Gtk::STATE_INSENSITIVE);
         for(int i = 0; i < Robots::SIZE; i++) {
             cb_robot_function[i].set_state(Gtk::STATE_INSENSITIVE);
             cb_robot_function[i].set_active(robots_function_tmp[i]);
         }
     }
 }
event_robots_id_done_bt_signal_clicked()
void RobotGUI::event_robots_id_done_bt_signal_clicked () private
Event triggered when Robot Functions' done button is clicked
Assigns each robot (on RobotGUI) to its new ID
Definition at line 337 of file robotGUI.cpp.
References debug_warning, Robots::get_ID(), robots_id_box, robots_id_done_bt, robots_id_edit_bt, robots_id_edit_flag, Robots::set_ID(), and Robots::SIZE.
Referenced by create_ids_frame().
{
     for(int i = 0; i < Robots::SIZE; i++) {
         Robots::set_ID(i, string(robots_id_box[i].get_text())[0]);
         debug_warning("Robot[" + to_string(i+1) +  "].ID: " + std::string(1, Robots::get_ID(i)));
         robots_id_box[i].set_state(Gtk::STATE_INSENSITIVE);
     }
     robots_id_edit_flag = false;
     robots_id_done_bt.set_state(Gtk::STATE_INSENSITIVE);
     robots_id_edit_bt.set_label("Edit");
 }
event_robots_id_edit_bt_signal_pressed()
void RobotGUI::event_robots_id_edit_bt_signal_pressed () private
Event triggered when Robot Functions' edit button is clicked
Turns robot's ID combobox (non)editable and keeps the changes
Definition at line 319 of file robotGUI.cpp.
References robots_id_box, robots_id_done_bt, robots_id_edit_bt, robots_id_edit_flag, robots_id_tmp, and Robots::SIZE.
Referenced by create_ids_frame().
{
     robots_id_edit_bt.set_label(robots_id_edit_flag ? "Edit" : "Cancel");
     if (!robots_id_edit_flag) {
         for(int i = 0; i < Robots::SIZE; i++) {
             robots_id_box[i].set_state(Gtk::STATE_NORMAL);
             robots_id_tmp[i] = robots_id_box[i].get_text();
         }
         robots_id_done_bt.set_state(Gtk::STATE_NORMAL);
     } else {
         for(int i = 0; i < Robots::SIZE; i++) {
             robots_id_box[i].set_state(Gtk::STATE_INSENSITIVE);
             robots_id_box[i].set_text(robots_id_tmp[i]);
         }
         robots_id_done_bt.set_state(Gtk::STATE_INSENSITIVE);
     }
     robots_id_edit_flag = !robots_id_edit_flag;
 }
event_robots_speed_done_bt_signal_clicked()
void RobotGUI::event_robots_speed_done_bt_signal_clicked () private
Updates robot's speed after Done button is clicked
Definition at line 308 of file robotGUI.cpp.
References robots_speed_done_bt, robots_speed_edit_bt, robots_speed_edit_flag, robots_speed_hscale, Robots::set_default_role_velocity(), and Robots::SIZE.
Referenced by create_speeds_frame().
{
     robots_speed_edit_flag = false;
     robots_speed_edit_bt.set_label("Edit");
     robots_speed_done_bt.set_state(Gtk::STATE_INSENSITIVE);
     for(int i = 0; i < Robots::SIZE; i++) {
         robots_speed_hscale[i].set_state(Gtk::STATE_INSENSITIVE);
         Robots::set_default_role_velocity(i, (float) robots_speed_hscale[i].get_value());
     }
 }
event_robots_speed_edit_bt_signal_pressed()
void RobotGUI::event_robots_speed_edit_bt_signal_pressed () private
Event triggered when Speeds' Edit button is clicked
This method may update buttons' label/state and the value at the speed slider
Definition at line 286 of file robotGUI.cpp.
References robots_speed_done_bt, robots_speed_edit_bt, robots_speed_edit_flag, robots_speed_hscale, robots_speed_tmp, and Robots::SIZE.
Referenced by create_speeds_frame().
{
     if(!robots_speed_edit_flag) {
         robots_speed_edit_flag = true;
         robots_speed_edit_bt.set_label("Cancel");
         robots_speed_done_bt.set_state(Gtk::STATE_NORMAL);
         for(int i = 0; i < Robots::SIZE; i++) {
             robots_speed_tmp[i] = robots_speed_hscale[i].get_value();
             robots_speed_hscale[i].set_state(Gtk::STATE_NORMAL);
         }
     } else {
         robots_speed_edit_flag = false;
         robots_speed_edit_bt.set_label("Edit");
         robots_speed_done_bt.set_state(Gtk::STATE_INSENSITIVE);
         for(int i = 0; i < Robots::SIZE; i++) {
             robots_speed_hscale[i].set_state(Gtk::STATE_INSENSITIVE);
             robots_speed_hscale[i].set_value(robots_speed_tmp[i]);
         }
     }
 }
update_ids()
void RobotGUI::update_ids ()
Updates the IDs frame at screen
Definition at line 17 of file robotGUI.cpp.
References debug_log, Robots::get_ID(), robots_id_box, and Robots::SIZE.
Referenced by jsonSaveManager::load_robots().
{
     for (unsigned short i = 0; i < Robots::SIZE; i++) {
         debug_log("Updating ID: " + std::string(1, Robots::get_ID(i)));
         robots_id_box[i].set_text(Glib::ustring::format(Robots::get_ID(i)));
     }
 }
update_robot_functions()
void RobotGUI::update_robot_functions ()
Updates robot functions at the screen
Definition at line 12 of file robotGUI.cpp.
References cb_robot_function, Robots::get_role(), and Robots::SIZE.
Referenced by CamCap::capture_and_show(), and jsonSaveManager::load_robots().
{
     for (int i = 0; i < Robots::SIZE; i++)
         cb_robot_function[i].set_active(Robots::get_role(i));
 }
update_speed_progressBars()
void RobotGUI::update_speed_progressBars ()
Updates the speed progress bar at the screen
Definition at line 24 of file robotGUI.cpp.
References Robots::get_role(), Robots::get_velocity(), robots_speed_progressBar, and Robots::SIZE.
Referenced by CamCap::capture_and_show().
{
     for(int i = 0; i < Robots::SIZE; i++) { // GK / DEF / ATK
         robots_speed_progressBar[Robots::get_role(i)].set_fraction(Robots::get_velocity(i)/1.4);
         robots_speed_progressBar[Robots::get_role(i)].set_text(std::to_string(Robots::get_velocity(i)).substr(0,4));
     }
 }
update_speed_sliders()
void RobotGUI::update_speed_sliders ()
Updates the speed sliders after successful load
Definition at line 31 of file robotGUI.cpp.
References Robots::get_default_role_velocity(), robots_speed_hscale, and Robots::SIZE.
Referenced by jsonSaveManager::load_robots().
{
     for(int i = 0; i < Robots::SIZE; i++)
         robots_speed_hscale[i].set_value(Robots::get_default_role_velocity(i));
 }
Field Documentation
cb_robot_function
Gtk::ComboBoxText RobotGUI::cb_robot_function[Robots::SIZE] private
Functions dropdown selector
Definition at line 51 of file robotGUI.hpp.
Referenced by create_functions_frame(), event_robots_function_done_bt_signal_clicked(), event_robots_function_edit_bt_signal_clicked(), and update_robot_functions().
robots_function_done_bt
Gtk::Button RobotGUI::robots_function_done_bt private
Definition at line 50 of file robotGUI.hpp.
Referenced by create_functions_frame(), event_robots_function_done_bt_signal_clicked(), and event_robots_function_edit_bt_signal_clicked().
robots_function_edit_bt
Gtk::Button RobotGUI::robots_function_edit_bt private
Definition at line 49 of file robotGUI.hpp.
Referenced by create_functions_frame(), disable_buttons(), enable_buttons(), event_robots_function_done_bt_signal_clicked(), and event_robots_function_edit_bt_signal_clicked().
robots_function_edit_flag
bool RobotGUI::robots_function_edit_flag = false private
Disables the robot functions edition frame
Definition at line 24 of file robotGUI.hpp.
Referenced by event_robots_function_done_bt_signal_clicked(), and event_robots_function_edit_bt_signal_clicked().
robots_function_fm
Gtk::Frame RobotGUI::robots_function_fm private
Definition at line 28 of file robotGUI.hpp.
Referenced by create_functions_frame().
robots_function_hbox
Gtk::HBox RobotGUI::robots_function_hbox[Robots::SIZE+1] private
Hbox that lists robots in Robo Functions frame
Definition at line 35 of file robotGUI.hpp.
Referenced by create_functions_frame().
robots_function_tmp
int RobotGUI::robots_function_tmp[Robots::SIZE] private
Definition at line 21 of file robotGUI.hpp.
Referenced by event_robots_function_edit_bt_signal_clicked().
robots_function_vbox
Gtk::VBox RobotGUI::robots_function_vbox private
Robot Function frame main vbox
Definition at line 31 of file robotGUI.hpp.
Referenced by create_functions_frame().
robots_id_box
Gtk::Entry RobotGUI::robots_id_box[Robots::SIZE] private
Definition at line 43 of file robotGUI.hpp.
Referenced by create_ids_frame(), event_robots_id_done_bt_signal_clicked(), event_robots_id_edit_bt_signal_pressed(), and update_ids().
robots_id_done_bt
Gtk::Button RobotGUI::robots_id_done_bt private
Definition at line 42 of file robotGUI.hpp.
Referenced by create_ids_frame(), event_robots_id_done_bt_signal_clicked(), and event_robots_id_edit_bt_signal_pressed().
robots_id_edit_bt
Gtk::Button RobotGUI::robots_id_edit_bt private
Definition at line 41 of file robotGUI.hpp.
Referenced by create_ids_frame(), disable_buttons(), enable_buttons(), event_robots_id_done_bt_signal_clicked(), and event_robots_id_edit_bt_signal_pressed().
robots_id_edit_flag
bool RobotGUI::robots_id_edit_flag = false private
Disables the robot id edition frame
Definition at line 25 of file robotGUI.hpp.
Referenced by event_robots_id_done_bt_signal_clicked(), and event_robots_id_edit_bt_signal_pressed().
robots_id_fm
Gtk::Frame RobotGUI::robots_id_fm private
Definition at line 38 of file robotGUI.hpp.
Referenced by create_ids_frame().
robots_id_hbox
Gtk::HBox RobotGUI::robots_id_hbox[Robots::SIZE+1] private
the hbox that holds Edit and Done buttons
Definition at line 40 of file robotGUI.hpp.
Referenced by create_ids_frame().
robots_id_tmp
Glib::ustring RobotGUI::robots_id_tmp[Robots::SIZE] private
Definition at line 44 of file robotGUI.hpp.
Referenced by event_robots_id_edit_bt_signal_pressed().
robots_id_vbox
Gtk::VBox RobotGUI::robots_id_vbox private
Definition at line 39 of file robotGUI.hpp.
Referenced by create_ids_frame().
robots_speed_done_bt
Gtk::Button RobotGUI::robots_speed_done_bt private
Definition at line 48 of file robotGUI.hpp.
Referenced by create_speeds_frame(), event_robots_speed_done_bt_signal_clicked(), and event_robots_speed_edit_bt_signal_pressed().
robots_speed_edit_bt
Gtk::Button RobotGUI::robots_speed_edit_bt private
Definition at line 47 of file robotGUI.hpp.
Referenced by create_speeds_frame(), disable_buttons(), enable_buttons(), event_robots_speed_done_bt_signal_clicked(), and event_robots_speed_edit_bt_signal_pressed().
robots_speed_edit_flag
bool RobotGUI::robots_speed_edit_flag = false private
Disables the speed edition frame
Definition at line 23 of file robotGUI.hpp.
Referenced by event_robots_speed_done_bt_signal_clicked(), and event_robots_speed_edit_bt_signal_pressed().
robots_speed_fm
Gtk::Frame RobotGUI::robots_speed_fm private
Definition at line 29 of file robotGUI.hpp.
Referenced by create_speeds_frame().
robots_speed_hbox
Gtk::HBox RobotGUI::robots_speed_hbox private
Hbox that holds edit/done buttons
Definition at line 36 of file robotGUI.hpp.
Referenced by create_speeds_frame().
robots_speed_hscale
Gtk::HScale RobotGUI::robots_speed_hscale[Robots::SIZE] private
Speed selection sliders
Definition at line 52 of file robotGUI.hpp.
Referenced by create_speeds_frame(), event_robots_speed_done_bt_signal_clicked(), event_robots_speed_edit_bt_signal_pressed(), and update_speed_sliders().
robots_speed_progressBar
Gtk::ProgressBar RobotGUI::robots_speed_progressBar[Robots::SIZE] private
Bars that show robot's actual speed
Definition at line 53 of file robotGUI.hpp.
Referenced by create_speeds_frame(), and update_speed_progressBars().
robots_speed_slider_vbox
Gtk::VBox RobotGUI::robots_speed_slider_vbox[Robots::SIZE] private
Robot's vboxes that keep the slider and progress bar
Definition at line 34 of file robotGUI.hpp.
Referenced by create_speeds_frame().
robots_speed_tmp
double RobotGUI::robots_speed_tmp[Robots::SIZE] private
Definition at line 20 of file robotGUI.hpp.
Referenced by event_robots_speed_edit_bt_signal_pressed().
robots_speed_vbox
Gtk::VBox RobotGUI::robots_speed_vbox private
Speed frame main vbox
Definition at line 32 of file robotGUI.hpp.
Referenced by create_speeds_frame().
speeds_grid
Gtk::Grid RobotGUI::speeds_grid private
Definition at line 27 of file robotGUI.hpp.
Referenced by create_speeds_frame().
The documentation for this class was generated from the following files:
src/gui/robotGUI.hpp
src/gui/robotGUI.cpp