VSSS-INF: Strategy Class Reference
Strategy Class Reference
#include <strategy.hpp>
Public Member Functions
Strategy ()
void set_constants (int w, int h)
void get_targets (std::vector< cv::Point > advRobots)
void reset_flags ()
void set_roles ()
bool has_ball (int i)
void fixed_position_check (int i)
bool offensive_adv ()
void collision_check (int i)
void set_role (int i, int role)
bool is_near (int i, cv::Point point)
void position_to_vector (int i)
double potField (int robot_index, cv::Point goal, int behavior=2)
int pot_rotation_decision (int robot_index, cv::Point goal, cv::Point obst)
void def_wait (int i)
void pot_field_around (int i)
void crop_targets (int i)
void atk_routine (int i)
void def_routine (int i)
void gk_routine (int i)
void set_Ball (cv::Point b)
cv::Point get_Ball_Est ()
void get_past (int i)
void get_variables ()
Data Fields
TestFrame testFrame
cv::Point Ball
cv::Point Ball_Est
int distBall
LS LS_ball_x
LS LS_ball_y
double pot_thetaX = 0
double pot_thetaY = 0
double pot_theta = 0
double pot_goalTheta = 0
double pot_goalMag
double pot_magnitude [5]
double pot_angle [5]
double ball_angle = 0
double ball_mag = 0
std::vector< cv::Point > adv
int collision_count [3]
double past_transangle [3]
cv::Point past_position [3]
int atk
int def
int gk
int opp
double lock_angle
int frames_blocked
bool transitions_enabled = true
int t = 0
int timeout = 0
int transition_timeout = 0
bool action1 = false
Private Member Functions
double distance (cv::Point A, cv::Point B)
double distance_meters (cv::Point A, cv::Point B)
Detailed Description
Definition at line 21 of file strategy.hpp.
Constructor & Destructor Documentation
Strategy()
Strategy::Strategy ()
Definition at line 31 of file strategy.cpp.
References LS::init(), LS_ball_x, LS_ball_y, and PREDICAO_NUM_SAMPLES.
                    : distBall(0) {
     LS_ball_x.init(PREDICAO_NUM_SAMPLES,1);
     LS_ball_y.init(PREDICAO_NUM_SAMPLES,1);
 }
Member Function Documentation
atk_routine()
void Strategy::atk_routine (int i)
Definition at line 760 of file strategy.cpp.
References CONST::ABS_FIELD_HEIGHT, CONST::ABS_ROBOT_SIZE, ATK_PENALTI_STATE, Ball, CONST::COORD_BOX_DWN_Y, CONST::COORD_BOX_UP_Y, CONST::COORD_GOAL_ATK_FRONT_X, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, CONST::COORD_MID_FIELD_X, CONST::corner_atk_limit, CORNER_STATE, def, CONST::def_corner_line, DEF_CORNER_STATE, distance(), Robots::get_position(), Robots::get_status(), CONST::goalie_line, has_ball(), is_near(), Robots::kick(), CONST::max_approach, NORMAL_STATE, PI, POSITION, pot_field_around(), Robots::set_cmdType(), Robots::set_status(), Robots::set_target(), Robots::set_velocity(), SIDEWAYS, Robots::spin_clockwise(), Robots::spin_counter_clockwise(), and VECTOR.
Referenced by get_targets().
{
     cv::Point target;
     cv::Point goal = cv::Point(COORD_GOAL_ATK_FRONT_X, COORD_GOAL_MID_Y);
     double m1 = double(goal.y - Ball.y)/double(goal.x - Ball.x);
     double m2 = double(Robots::get_position(i).y - Ball.y)/double(Robots::get_position(i).x - Ball.x);
     double phi = atan((m2-m1)/(1+m2*m1));
     Robots::set_velocity(i);
     if(Robots::get_status(i) != ATK_PENALTI_STATE) {
         if((Robots::get_position(def).x < COORD_MID_FIELD_X // se o defensor tá atrás do meio de campo
             && Ball.x > corner_atk_limit + 5*ABS_ROBOT_SIZE  // se a bola tá depois do x do penalti
             && Ball.y > COORD_GOAL_UP_Y && Ball.y < COORD_GOAL_DWN_Y) // se a bola tá no meio em y, isso é um penalti
             ||
             (has_ball(i) && // atacante tem a posse de bola
             abs(phi)*180/PI < 30)) { // angulo com o gol tá bom
             Robots::set_status(i, ATK_PENALTI_STATE); // chuta
         }
         else if(Ball.x > corner_atk_limit && // se a bola tá depois da linha x da área adversária
             (Ball.y > COORD_GOAL_DWN_Y || Ball.y < COORD_GOAL_UP_Y)) { // e tá fora da área
             Robots::set_status(i, CORNER_STATE); // a bola tá no corner, gira
         }
         else if(Ball.x < def_corner_line) { // se a bola tá antes da nossa linha x da área
             Robots::set_status(i, DEF_CORNER_STATE); // a bola tá no nosso corner
         }
         else if(Ball.y > ABS_FIELD_HEIGHT - ABS_ROBOT_SIZE*1.5 || // se a bola tá na lateral de baixo
             Ball.y < ABS_ROBOT_SIZE*1.5) { // ou na lateral de cima
             Robots::set_status(i, SIDEWAYS); // sideways
         } else {
             Robots::set_status(i, NORMAL_STATE); // senão, age normalmente
         }
     }
     switch(Robots::get_status(i)) {
         case NORMAL_STATE:
             // leva a bola pro gol deles
             Robots::set_cmdType(i, Robots::CMD::VECTOR);
             pot_field_around(i);
             break;
         case SIDEWAYS:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             // empurra a bola no canto mesmo
             if(Ball.y > ABS_FIELD_HEIGHT - ABS_ROBOT_SIZE*1.5) { // se a bola tá na lateral inferior
                 if(distance(Robots::get_position(i), Ball) > ABS_ROBOT_SIZE // se a bola tá longe do robô
                     || Ball.x >= Robots::get_position(i).x + ABS_ROBOT_SIZE/1.5) { // ou se a bola não tá travada por ele
                     target = Ball;
                 }
                 else { // se a bola tá travada
                     Robots::spin_counter_clockwise(i, 0.8);
                 }
                 if(Ball.x < Robots::get_position(i).x) { // se a bola tá atrás do atacante
                     target.x = Ball.x - max_approach;
                     target.y = int(Ball.y - max_approach/2.0);
                 }
             }
             else if(Ball.y < ABS_ROBOT_SIZE*1.5) { // se a bola tá na lateral superior
                 if(distance(Robots::get_position(i), Ball) > ABS_ROBOT_SIZE // se a bola tá longe do robô
                     || Ball.x >= Robots::get_position(i).x + ABS_ROBOT_SIZE/1.5) { // ou se a bola não tá travada
                     target = Ball;
                 }
                 else { // se a bola tá travada
                     Robots::spin_clockwise(i, 0.8);
                 }
                 if(Ball.x < Robots::get_position(i).x) { // se a bola tá atrás do atacante
                     target.x = Ball.x - max_approach;
                     target.y = int(Ball.y + max_approach/2.0);
                 }
             }
             Robots::set_target(i, target);
             break;
         case CORNER_STATE:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             if(Ball.y < COORD_GOAL_MID_Y) { // se a bola tá acima do gol
                 if(Ball.y < COORD_GOAL_UP_Y) { // acima ou abaixo da trave, escolher o giro para levar a bola para o gol ou para faze-la entrar
                     if(Ball.x > Robots::get_position(i).x && distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE)
                         Robots::spin_clockwise(i, 0.8); // giro que leva a bola ao gol
                     else
                         target = Ball; // faz a bola travar no canto pra girar certo
                 } else {
                     if(Ball.y > Robots::get_position(i).y && distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE)
                         Robots::spin_counter_clockwise(i, 0.8); // giro para faze-la entrar
                     else
                         target = Ball;
                 }
             } else {
                 if(Ball.y > COORD_GOAL_DWN_Y) { // se a bola tá abaixo do gol
                     if(Ball.x > Robots::get_position(i).x && distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE)
                         Robots::spin_counter_clockwise(i, 0.8);
                     else
                         target = Ball; // faz a bola travar no canto pra girar certo
                 } else {
                     if(Ball.y > Robots::get_position(i).y && distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE)
                         Robots::spin_clockwise(i, 0.8); // giro para faze-la entrar
                     else
                         target = Ball;
                 }
             }
             Robots::set_target(i, target);
             break;
         case DEF_CORNER_STATE:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             //Robots::set_fixedPos(i, true);
             if(Ball.y > COORD_GOAL_MID_Y) {
                 target.x = goalie_line;
                 target.y = COORD_BOX_DWN_Y + ABS_ROBOT_SIZE;
                 if(distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE && Ball.y > Robots::get_position(i).y)
                     Robots::spin_counter_clockwise(i, 0.8);
                 // if(distance(Robots::get_position(i), robots[i].target) <= fixed_pos_distance) robots[i].target = Ball;
                 if(is_near(i, target) && Ball.y > Robots::get_position(i).y) {
                     target = Ball;
                 }
                 Robots::set_target(i, target);
             } else {
                 target.x = goalie_line;
                 target.y = COORD_BOX_UP_Y - ABS_ROBOT_SIZE;
                 if(distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE && Ball.y < Robots::get_position(i).y)
                     Robots::spin_clockwise(i, 0.8);
                 // if(distance(Robots::get_position(i), Robots::get_target(i)) <= fixed_pos_distance) robots[i].target = Ball;
                 if(is_near(i, target) && Ball.y < Robots::get_position(i).y) {
                     target = Ball;
                 }
                 Robots::set_target(i, target);
             }
             break;
         case ATK_PENALTI_STATE:
             Robots::set_cmdType(i, Robots::CMD::VECTOR);
             Robots::kick(i, goal);
             if(!has_ball(i))
                 Robots::set_status(i, NORMAL_STATE);
     }
     //crop_targets(i);
 }
collision_check()
void Strategy::collision_check (int i)
Definition at line 371 of file strategy.cpp.
References CONST::ABS_GOAL_SIZE_X, CONST::ABS_ROBOT_SIZE, ATK_PENALTI_STATE, ATTACKER, Ball, collision_count, CONST::collision_radius, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, CORNER_STATE, distance(), CONST::fixed_pos_distance, Robots::get_fixedPos(), get_past(), Robots::get_position(), Robots::get_role(), Robots::get_status(), Robots::get_target(), Robots::get_transAngle(), CONST::max_collision_count, past_position, past_transangle, PI, Robots::set_command(), Robots::set_target(), and Robots::set_transAngle().
Referenced by get_targets().
{
     if(Robots::get_fixedPos(i)) return;
     // se é atacante e está dentro do gol
     if (Robots::get_role(i) == ATTACKER &&
             Robots::get_position(i).y > COORD_GOAL_UP_Y && Robots::get_position(i).y < COORD_GOAL_DWN_Y &&
             Robots::get_position(i).x < ABS_GOAL_SIZE_X + 0.75 * ABS_ROBOT_SIZE) {
         // verifica se está colidindo
         if(distance(Robots::get_position(i), past_position[i]) <= collision_radius) {
             collision_count[i]++;
         } else {
             get_past(i);
             collision_count[i] = 0;
         }
         if(collision_count[i] >= max_collision_count) {
             cv::Point upper_corner;
             cv::Point lower_corner;
             double tempAngle;
             upper_corner.x = lower_corner.x = ABS_GOAL_SIZE_X;
             upper_corner.y = COORD_GOAL_UP_Y;
             lower_corner.y = COORD_GOAL_DWN_Y;
             if(distance(Robots::get_position(i), upper_corner) > distance(Robots::get_position(i), lower_corner) && Ball.y > COORD_GOAL_MID_Y){
                 tempAngle = atan2(sin(past_transangle[i]+(PI/2)),cos(past_transangle[i]+(PI/2)));
             } else if (distance(Robots::get_position(i), upper_corner) < distance(Robots::get_position(i), lower_corner) && Ball.y < COORD_GOAL_MID_Y) {
                 tempAngle = atan2(sin(past_transangle[i]-(PI / 2)), cos(past_transangle[i]-(PI / 2)));
             } else {
                 tempAngle = Robots::get_transAngle(i);
             }
             Robots::set_target(i, cv::Point(Ball.x, Robots::get_position(i).y));
             Robots::set_command(i, tempAngle);
         }
     }
     else if(Robots::get_status(i) != CORNER_STATE && Robots::get_status(i) != ATK_PENALTI_STATE) {
         if(distance(Robots::get_position(i), past_position[i]) <= collision_radius &&
             distance(Robots::get_position(i), Robots::get_target(i)) > fixed_pos_distance) {
             collision_count[i]++;
         } else {
             get_past(i);
             collision_count[i] = 0;
         }
         if(collision_count[i] >= max_collision_count) {
             Robots::set_transAngle(i, atan2(sin(past_transangle[i]+PI),cos(past_transangle[i]+PI)));
         }
     }
 }
crop_targets()
void Strategy::crop_targets (int i)
Definition at line 739 of file strategy.cpp.
References CONST::ABS_FIELD_HEIGHT, CONST::COORD_BOX_DEF_X, CONST::COORD_BOX_UP_Y, CONST::COORD_GOAL_ATK_FRONT_X, CONST::COORD_GOAL_DWN_Y, CONST::def_corner_line, Robots::get_target(), and Robots::set_target().
Referenced by def_routine().
{
     cv::Point target = Robots::get_target(i);
     if(target.y < 0)
         target.y = 0;
     if(target.y > ABS_FIELD_HEIGHT)
         target.y = ABS_FIELD_HEIGHT;
     if(target.x < 0)
         target.x = 0;
     if(target.x > COORD_GOAL_ATK_FRONT_X)
         target.x = COORD_GOAL_ATK_FRONT_X;
     if(target.x < COORD_BOX_DEF_X && target.y > COORD_BOX_UP_Y && target.y < COORD_GOAL_DWN_Y) // não deixa entrar na área
         target.x = def_corner_line;
     Robots::set_target(i, target);
 }
def_routine()
void Strategy::def_routine (int i)
Definition at line 918 of file strategy.cpp.
References CONST::ABS_ROBOT_SIZE, atk, ATK_PENALTI_STATE, Ball, Ball_Est, CONST::COORD_BOX_DEF_X, CONST::COORD_BOX_DWN_Y, CONST::COORD_BOX_UP_Y, CONST::COORD_GOAL_ATK_FRONT_X, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, CONST::COORD_MID_FIELD_X, CONST::corner_atk_limit, crop_targets(), CONST::def_corner_line, DEF_CORNER_STATE, def_wait(), distance(), Robots::get_position(), Robots::get_status(), CONST::goalie_line, is_near(), Robots::kick(), NORMAL_STATE, PI, POSITION, pot_field_around(), Robots::set_cmdType(), Robots::set_status(), Robots::set_target(), Robots::set_velocity(), Robots::spin_clockwise(), Robots::spin_counter_clockwise(), STEP_BACK, and VECTOR.
Referenced by get_targets().
{
     cv::Point target;
     cv::Point goal = cv::Point(COORD_GOAL_ATK_FRONT_X, COORD_GOAL_MID_Y);
     double m1 = double(goal.y - Ball_Est.y)/double(goal.x - Ball.x);
     double m2 = double(Robots::get_position(i).y - Ball.y)/double(Robots::get_position(i).x - Ball.x);
     double phi = atan((m2-m1)/(1+m2*m1));
     Robots::set_velocity(i);
     if(Robots::get_position(i).x > COORD_MID_FIELD_X
         && abs(phi)*180/PI < 30) {
         Robots::set_status(i, ATK_PENALTI_STATE);
     }
     else if(Robots::get_position(atk).x > Ball.x
         && Ball.x < COORD_MID_FIELD_X
         && distance(Robots::get_position(atk), Ball) > 3*ABS_ROBOT_SIZE) {
         Robots::set_status(i, STEP_BACK);
     }
     else if(Ball.x < def_corner_line) {
         Robots::set_status(i, DEF_CORNER_STATE);
     }
     else {
         Robots::set_status(i, NORMAL_STATE);
     }
     switch(Robots::get_status(i)) {
         case NORMAL_STATE:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             // se a bola está no corner adversário, espera o cruzamento
             if(Ball_Est.x > corner_atk_limit) {
                 int y_pos = Ball.y > COORD_GOAL_MID_Y ? COORD_GOAL_UP_Y : COORD_GOAL_DWN_Y;
                 target = cv::Point(COORD_MID_FIELD_X + COORD_MID_FIELD_X/4, y_pos);
                 Robots::set_target(i, target); // deve ser chamado antes do wait
                 def_wait(i);
             }
             else if(Ball_Est.x > COORD_MID_FIELD_X) { // se a bola está depois do meio de campo, avança um pouco
                 target = cv::Point(COORD_MID_FIELD_X - COORD_MID_FIELD_X/4, COORD_GOAL_MID_Y);
                 Robots::set_target(i, target); // deve ser chamado antes do wait
                 def_wait(i);
             }
             else { // senão, tenta tampar o angulo que o goleiro não consegue
                 // fixa uma posição em x
                 int x_pos = COORD_BOX_DEF_X + ABS_ROBOT_SIZE;
                 int ballTarget = Ball.y > COORD_GOAL_MID_Y ? COORD_GOAL_UP_Y : COORD_GOAL_DWN_Y;
                 double m = double(Ball.y - ballTarget) / double(Ball.x - ABS_ROBOT_SIZE);
                 auto y_proj = int(Ball.y - m * (Ball.x - x_pos));
                 // faz o crop do alvo se ele for muito discrepante (se a bola se aproximar muito do gol)
                 if(y_proj > COORD_GOAL_DWN_Y) y_proj = COORD_GOAL_DWN_Y;
                 else if(y_proj < COORD_GOAL_UP_Y) y_proj = COORD_GOAL_UP_Y;
                 target = cv::Point(x_pos, y_proj);
             }
             break;
         case STEP_BACK:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             if(Ball.x > Robots::get_position(i).x + ABS_ROBOT_SIZE) {
                 Robots::set_target(i, Ball);
             }
             else {
                 pot_field_around(i);
                 crop_targets(i);
             }
             break;
         case DEF_CORNER_STATE:
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             if(Ball.y > COORD_GOAL_MID_Y) {
                 target.x = goalie_line;
                 target.y = COORD_BOX_DWN_Y + ABS_ROBOT_SIZE;
                 if(distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE && Ball.y > Robots::get_position(i).y)
                     Robots::spin_counter_clockwise(i, 0.8);
                 // if(distance(Robots::get_position(i), Robots::get_target(i)) <= fixed_pos_distance) robots[i].target = Ball;
                 if(is_near(i, target) && Ball.y > Robots::get_position(i).y) {
                     target = Ball;
                 }
             } else {
                 target.x = goalie_line;
                 target.y = COORD_BOX_UP_Y - ABS_ROBOT_SIZE;
                 if(distance(Ball, Robots::get_position(i)) < ABS_ROBOT_SIZE && Ball.y < Robots::get_position(i).y)
                     Robots::spin_clockwise(i, 0.8);
                 // if(distance(Robots::get_position(i), Robots::get_target(i)) <= fixed_pos_distance) robots[i].target = Ball;
                 if(is_near(i, target) && Ball.y < Robots::get_position(i).y) {
                     target = Ball;
                 }
             }
             Robots::set_target(i, target);
             break;
         case ATK_PENALTI_STATE:
             Robots::set_cmdType(i, Robots::CMD::VECTOR);
             Robots::kick(i, Ball);
     }
 }
def_wait()
void Strategy::def_wait (int i)
Definition at line 685 of file strategy.cpp.
References Ball, distance(), CONST::fixed_pos_distance, Robots::get_position(), Robots::get_target(), Robots::look_at(), and Robots::set_fixedPos().
Referenced by def_routine().
{
     Robots::set_fixedPos(i, true);
     if(distance(Robots::get_position(i), Robots::get_target(i)) <= fixed_pos_distance) {
         Robots::look_at(i, Ball);
     }
 }
distance()
double Strategy::distance (cv::Point A, cv::Point B) private
Definition at line 1143 of file strategy.cpp.
Referenced by atk_routine(), collision_check(), def_routine(), def_wait(), fixed_position_check(), gk_routine(), has_ball(), is_near(), pot_field_around(), and set_roles().
{
     double dist = sqrt(pow(double(A.y - B.y), 2) + pow(double(A.x - B.x), 2));
     return dist;
 }
distance_meters()
double Strategy::distance_meters (cv::Point A, cv::Point B) private
Definition at line 1148 of file strategy.cpp.
References CONST::ABS_GOAL_TO_GOAL_WIDTH.
Referenced by potField().
{
     double dist = sqrt(pow(double(A.y - B.y), 2) + pow(double(A.x - B.x), 2));
     dist = 1.7*dist/ABS_GOAL_TO_GOAL_WIDTH;
     return dist;
 }
fixed_position_check()
void Strategy::fixed_position_check (int i)
Definition at line 342 of file strategy.cpp.
References CONST::ABS_GOAL_TO_GOAL_WIDTH, distance(), CONST::fixed_pos_distance, Robots::get_cmdType(), Robots::get_default_velocity(), Robots::get_fixedPos(), Robots::get_position(), Robots::get_target(), Robots::get_velocity(), POSITION, Robots::set_velocity(), Robots::stop(), and VECTOR.
Referenced by get_targets().
                                          { // Para posição fixa
     if(Robots::get_fixedPos(i) && (Robots::get_cmdType(i) == Robots::CMD::VECTOR || Robots::get_cmdType(i) == Robots::CMD::POSITION)) {
         Robots::set_velocity(i, float(Robots::get_default_velocity(i) * pow(distance(Robots::get_position(i), Robots::get_target(i))/(ABS_GOAL_TO_GOAL_WIDTH/4.0), 2)));
         // cout << "vmax " << robots[i].vmax << " distancia "<< distance(Robots::get_position(i), Robots::get_target(i)) << " distancia max " << ABS_GOAL_TO_GOAL_WIDTH/4<<endl;
         if(Robots::get_velocity(i) > Robots::get_default_velocity(i)) Robots::set_velocity(i);
         if(Robots::get_velocity(i) < 0.3) Robots::set_velocity(i, 0.3f);
         if(distance(Robots::get_target(i), Robots::get_position(i)) <= fixed_pos_distance) {
             Robots::stop(i);
         }
     }
 }
get_Ball_Est()
cv::Point Strategy::get_Ball_Est ()
Definition at line 1139 of file strategy.cpp.
References Ball_Est.
Referenced by CamCap::capture_and_show().
{
     return Ball_Est;
 }
get_past()
void Strategy::get_past (int i)
Definition at line 1159 of file strategy.cpp.
References Robots::get_position(), Robots::get_transAngle(), past_position, and past_transangle.
Referenced by collision_check().
{
     past_position[i] = Robots::get_position(i);
     past_transangle[i] = Robots::get_transAngle(i);
 }
get_targets()
void Strategy::get_targets (std::vector< cv::Point > advRobots)
Definition at line 102 of file strategy.cpp.
References adv, atk, atk_routine(), collision_check(), def, def_routine(), fixed_position_check(), Robots::get_usingPotField(), get_variables(), gk, gk_routine(), N_ROBOTS, position_to_vector(), reset_flags(), and set_roles().
Referenced by CamCap::capture_and_show().
{
     adv = std::move(advRobots);
     get_variables(); // pega a linha em que o goleiro deve ficar da interface
     reset_flags();
     set_roles();
     gk_routine(gk);
     def_routine(def);
     atk_routine(atk);
     for(int i = 0; i < N_ROBOTS; i++) {
         if(!Robots::get_usingPotField(i)) position_to_vector(i);
         fixed_position_check(i); // faz a desaceleração e a parada dos robôs
         collision_check(i);
     }
 } // get_targets
get_variables()
void Strategy::get_variables ()
Definition at line 1154 of file strategy.cpp.
References TestFrame::getValue(), CONST::goalie_line, CONST::goalie_offset, and testFrame.
Referenced by get_targets().
{
     goalie_line = (int)testFrame.getValue(0); // index da barrinha
     goalie_offset = (int)testFrame.getValue(1); // index da barrinha
 }
gk_routine()
void Strategy::gk_routine (int i)
Definition at line 1029 of file strategy.cpp.
References CONST::ABS_ROBOT_SIZE, Ball, Ball_Est, CONST::COORD_BOX_DEF_X, CONST::COORD_BOX_DWN_Y, CONST::COORD_BOX_UP_Y, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_UP_Y, CONST::COORD_MID_FIELD_X, distance(), Robots::get_position(), Robots::get_status(), Robots::get_target(), CONST::goalie_line, Robots::look_at(), MAX_VEL, NORMAL_STATE, PI, POSITION, Robots::set_cmdType(), Robots::set_fixedPos(), Robots::set_target(), Robots::set_velocity(), Robots::spin_clockwise(), and Robots::spin_counter_clockwise().
Referenced by get_targets().
{
     switch(Robots::get_status(i)) {
         case NORMAL_STATE:
             Robots::set_fixedPos(i, true);
             Robots::set_cmdType(i, Robots::CMD::POSITION);
             cv::Point target;
             target.x = goalie_line;
             target.y = Ball.y;
             // if bola com velocidade && vindo pra defesa && fora da area
             if(distance(Ball, Ball_Est) > ABS_ROBOT_SIZE && Ball.x > Ball_Est.x && (Ball.x > COORD_BOX_DEF_X)) {
                 double m = double(Ball.y - Ball_Est.y)/double(Ball.x - Ball_Est.x);
                 auto pred_y = int(Ball.y - m * (Ball.x - (goalie_line + ABS_ROBOT_SIZE)));
                 if(pred_y > COORD_GOAL_DWN_Y)
                     pred_y = COORD_GOAL_DWN_Y;
                 if(pred_y < COORD_GOAL_UP_Y)
                     pred_y = COORD_GOAL_UP_Y;
                 if(Ball.x > COORD_MID_FIELD_X) {
                     target.y = pred_y;
                 } else {
                     cv::Point v = cv::Point(0, Ball.y - pred_y); // vetor da predição à projeção (na linha do gol)
                     double vector_module = sqrt(pow(v.x,2) + pow(v.y,2)); // modulo
                     double approach = abs(Ball.y - pred_y) * (Ball.x - (Robots::get_position(i).x + ABS_ROBOT_SIZE))/float(COORD_MID_FIELD_X - Robots::get_position(i).x);
                     target.y = int(pred_y + (v.y/vector_module) * approach);
                 }
             } else {
                 target.y = Ball.y;
             }
             if(target.y > COORD_GOAL_DWN_Y) target.y = COORD_GOAL_DWN_Y - ABS_ROBOT_SIZE;
             if(target.y < COORD_GOAL_UP_Y) target.y = COORD_GOAL_UP_Y + ABS_ROBOT_SIZE;
             // if(Ball.x < COORD_BOX_DEF_X && Ball.y > COORD_GOAL_DWN_Y) {
             //  // if bola no corner inferior do gol
             //  robots[i].target.y = COORD_GOAL_DWN_Y + goalie_offset;
             // } else if (Ball.x < COORD_BOX_DEF_X && Ball.y < COORD_GOAL_UP_Y){
             //  // if bola no corner superior do gol
             //  robots[i].target.y = COORD_GOAL_UP_Y - goalie_offset;
             // }
             // if (Ball.x < COORD_BOX_DEF_X && Ball.y > COORD_BOX_UP_Y && Ball.y < COORD_GOAL_DWN_Y) {
             //  Robots::set_target(i, Ball);
             // }
             //Robots::set_velocity(i, float(0.3 + ((Robots::get_default_role_velocity(GOALKEEPER)-0.3) * (distance(Robots::get_position(i), Robots::get_target(i)))/ABS_GOAL_SIZE_Y)));
             // cout << "vmax " << robots[i].vmax << " distancia "<< distance(Robots::get_position(i), Robots::get_target(i)) << " distancia max " << ABS_GOAL_TO_GOAL_WIDTH/4<<endl;
             /*if(Robots::get_velocity(i) > Robots::get_default_velocity(i))
                 Robots::set_velocity(i);
             if(Robots::get_velocity(i) < 0.35)
                 Robots::set_velocity(i, 0.35f);*/
             // fixed_lookup(i);
             if(distance(Robots::get_position(i), Ball) < ABS_ROBOT_SIZE*1.3) {
                 if(Ball.y <= COORD_GOAL_UP_Y) {
                     Robots::spin_clockwise(i, 1.f);
                 } else if(Ball.y >= COORD_GOAL_DWN_Y) {
                     Robots::spin_counter_clockwise(i, 1.f);
                 }
             }
             if(distance(Robots::get_position(i), Ball) < ABS_ROBOT_SIZE*1.3) {
                 if(Ball.y <= Robots::get_position(i).y) {
                     Robots::spin_clockwise(i, 1.f);
                 } else if(Ball.y >= Robots::get_position(i).y){
                     Robots::spin_counter_clockwise(i, 1.f);
                 }
             }
             // chute pra tirar a bola da defesa
             if(abs(Ball.x - Robots::get_position(i).x) <= ABS_ROBOT_SIZE && Ball.y < COORD_BOX_DWN_Y && Ball.y > COORD_BOX_UP_Y) {
                 if (Ball.y <= Robots::get_position(i).y) {
                     target.y = 0;
                     target.x = goalie_line; //  + ABS_ROBOT_SIZE/2
                     Robots::set_velocity(i, MAX_VEL);
                 } else {
                     target.y = 480;
                     target.x = goalie_line; //  + ABS_ROBOT_SIZE/2
                     Robots::set_velocity(i, MAX_VEL);
                 }
             }
             Robots::set_target(i, target);
             if(distance(Robots::get_position(i), Robots::get_target(i)) < ABS_ROBOT_SIZE*3.0/4) {
                 Robots::look_at(i, PI/2);
             }
             break;
     }
 }
has_ball()
bool Strategy::has_ball (int i)
Definition at line 223 of file strategy.cpp.
References CONST::ABS_ROBOT_SIZE, Ball, distance(), Robots::get_orientation(), Robots::get_position(), and PI.
Referenced by atk_routine().
                              { // se i tem a bola, i pode levá-la pra frente
     double theta_i_ball = atan2(Ball.y - Robots::get_position(i).y, Ball.x - Robots::get_position(i).x);
     return distance(Robots::get_position(i), Ball) < ABS_ROBOT_SIZE*1.5 //< robô está perto da bola
            && (abs(Robots::get_orientation(i) - theta_i_ball)*180/PI < 30 || abs(Robots::get_orientation(i) - theta_i_ball)*180/PI > 150) //< bola está em uma das frentes
            && Ball.x > Robots::get_position(i).x + ABS_ROBOT_SIZE/2; // bola está na frente do atacante em relação ao gol inimigo
     ;
 }
is_near()
bool Strategy::is_near (int i, cv::Point point)
Definition at line 455 of file strategy.cpp.
References distance(), CONST::fixed_pos_distance, and Robots::get_position().
Referenced by atk_routine(), def_routine(), and pot_field_around().
{
     return distance(Robots::get_position(i), point) < fixed_pos_distance;
 }
offensive_adv()
bool Strategy::offensive_adv ()
position_to_vector()
void Strategy::position_to_vector (int i)
Definition at line 459 of file strategy.cpp.
References Robots::get_cmdType(), Robots::get_position(), Robots::get_target(), Robots::set_transAngle(), and VECTOR.
Referenced by get_targets().
{
     if(Robots::get_cmdType(i) != Robots::CMD::VECTOR)
         Robots::set_transAngle(i, atan2(double(Robots::get_position(i).y - Robots::get_target(i).y), - double(Robots::get_position(i).x - Robots::get_target(i).x)));
 }
pot_field_around()
void Strategy::pot_field_around (int i)
Definition at line 692 of file strategy.cpp.
References CONST::ABS_FIELD_HEIGHT, CONST::ABS_GOAL_SIZE_Y, CONST::ABS_ROBOT_SIZE, action1, Ball, Ball_Est, BALL_ONLY_OBS, CONST::COORD_GOAL_ATK_FRONT_X, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, distance(), Robots::get_position(), is_near(), CONST::max_approach, potField(), Robots::set_target(), Robots::set_transAngle(), and Robots::set_usingPotField().
Referenced by atk_routine(), and def_routine().
{
     Robots::set_usingPotField(i, true);
     cv::Point targets_temp;
     cv::Point goal = cv::Point(COORD_GOAL_ATK_FRONT_X, COORD_GOAL_MID_Y);
     double m1 = double(goal.y - Ball_Est.y)/double(goal.x - Ball_Est.x);
     double m2 = double(Robots::get_position(i).y - Ball_Est.y)/double(Robots::get_position(i).x - Ball_Est.x);
     // double ball_goal = distance(Ball_Est, goal);
     // double r1 = ball_goal + max_approach;
     double dist_up = distance(Ball_Est, cv::Point(COORD_GOAL_ATK_FRONT_X, COORD_GOAL_UP_Y));
     double dist_dwn = distance(Ball_Est, cv::Point(COORD_GOAL_ATK_FRONT_X, COORD_GOAL_DWN_Y));
     double beta = acos((pow(dist_up,2)+pow(dist_dwn,2)-pow(ABS_GOAL_SIZE_Y,2)) / (2*dist_up*dist_dwn));
     cv::Point v = cv::Point(goal.x - Ball_Est.x, goal.y - Ball_Est.y);
     double module = sqrt(pow(v.x,2) + pow(v.y,2));
     double phi = atan((m2-m1) / (1+m2*m1));
     // cout << "phi -> " << phi*180/PI << " 180 - phi -> " << 180 - phi*180/PI << endl;
     targets_temp.x = static_cast<int>(Ball_Est.x - (v.x/module) * max_approach);
     targets_temp.y = static_cast<int>(Ball_Est.y - (v.y/module) * max_approach);
     // crop
     if(targets_temp.y < 0) targets_temp.y = 0;
     if(targets_temp.y > ABS_FIELD_HEIGHT) targets_temp.y = ABS_FIELD_HEIGHT;
     if(targets_temp.x < 0) targets_temp.x = 0;
     if(targets_temp.x > COORD_GOAL_ATK_FRONT_X) targets_temp.x = COORD_GOAL_ATK_FRONT_X;
     Robots::set_target(i, targets_temp);
     Robots::set_transAngle(i, potField(i, targets_temp, BALL_ONLY_OBS));
     if(Robots::get_position(i).x > Ball.x + ABS_ROBOT_SIZE)
         action1 = false;
     if(is_near(i, targets_temp) || abs(phi) < beta/2 || action1) {
         v = cv::Point(Robots::get_position(i).x - Ball.x, Robots::get_position(i).y - Ball.y);
         // module = sqrt(pow(v.x,2) + pow(v.y,2));
         // targets_temp.x = (Ball.x - (v.x/module) * max_approach);
         // targets_temp.y = (Ball.y - (v.y/module) * max_approach);
         Robots::set_transAngle(i, atan2(double(Robots::get_position(i).y - Ball.y), - double(Robots::get_position(i).x - Ball.x)));
         action1 = true;
     }
 }
pot_rotation_decision()
int Strategy::pot_rotation_decision (int robot_index, cv::Point goal, cv::Point obst)
Definition at line 612 of file strategy.cpp.
References CONST::ABS_FIELD_HEIGHT, CONST::ABS_ROBOT_SIZE, Robots::get_position(), and PI.
Referenced by potField().
{
     int HORARIO = 1;
     int ANTI_HORARIO = -1;
     bool goal_ahead = Robots::get_position(robot_index).x > obst.x && obst.x > goal.x;
     bool goal_behind = Robots::get_position(robot_index).x < obst.x && obst.x < goal.x;
     if(obst.y < ABS_ROBOT_SIZE*2) {
         if(goal_ahead) return HORARIO;
         if(goal_behind) return ANTI_HORARIO;
     } else if(obst.y > (ABS_FIELD_HEIGHT - ABS_ROBOT_SIZE*2)) {
         if(goal_ahead) return ANTI_HORARIO;
         if(goal_behind) return HORARIO;
     }
     double angle_Obst_Robot = atan2(double(obst.y - Robots::get_position(robot_index).y), - double(obst.x - Robots::get_position(robot_index).x));
     double angle_Obst_Goal = atan2(double(obst.y - goal.y), - double(obst.x - goal.x));
     // printf("%f + %f = %f \n",fabs(angle_Obst_Robot)*180/PI,fabs(angle_Obst_Goal)*180/PI,(fabs(angle_Obst_Robot)+fabs(angle_Obst_Goal))*180/PI);
     if(angle_Obst_Robot > 0 && angle_Obst_Robot <= PI/2) { // ROBO NO PRIMEIRO QUAD
         if(angle_Obst_Goal > 0 && angle_Obst_Goal <= PI/2) { // OBJETIVO NO PRIMEIRO QUAD
             return 0;
         } else if(angle_Obst_Goal > PI/2 && angle_Obst_Goal <= PI) { // OBJETIVO NO SEGUNDO QUAD
             return ANTI_HORARIO;
         } else if(angle_Obst_Goal > -PI && angle_Obst_Goal <= -PI/2) {// OBJETIVO NO TERCEIRO QUAD
             return HORARIO;
         } else { // OBJETIVO NO QUARTO QUAD
             // printf("DECIDE" );
             if(fabs(angle_Obst_Robot)+fabs(angle_Obst_Goal) < PI) return HORARIO;
             else return ANTI_HORARIO;
         }
     } else if(angle_Obst_Robot > PI/2 && angle_Obst_Robot <= PI) { // ROBO NO SEGUNDO QUAD
         if(angle_Obst_Goal > 0 && angle_Obst_Goal <= PI/2) { // OBJETIVO NO PRIMEIRO QUAD
             return HORARIO;
         } else if(angle_Obst_Goal > PI/2 && angle_Obst_Goal <= PI) { // OBJETIVO NO SEGUNDO QUAD
             return 0;
         } else if(angle_Obst_Goal > -PI && angle_Obst_Goal <= -PI/2) {// OBJETIVO NO TERCEIRO QUAD
             return ANTI_HORARIO;
         } else { // OBJETIVO NO QUARTO QUAD
             // printf("DECIDE" );
             if(fabs(angle_Obst_Robot)+fabs(angle_Obst_Goal) < PI) return HORARIO;
             else return ANTI_HORARIO;
         }
     } else if(angle_Obst_Robot > -PI && angle_Obst_Robot <= -PI/2) {// ROBO NO TERCEIRO QUAD
         if(angle_Obst_Goal > 0 && angle_Obst_Goal <= PI/2) { // OBJETIVO NO PRIMEIRO QUAD
         //  printf("DECIDE" );
             if(fabs(angle_Obst_Robot)+fabs(angle_Obst_Goal) < PI) return ANTI_HORARIO;
             else return HORARIO;
         } else if(angle_Obst_Goal > PI/2 && angle_Obst_Goal <= PI) { // OBJETIVO NO SEGUNDO QUAD
             return HORARIO;
         } else if(angle_Obst_Goal > -PI && angle_Obst_Goal <= -PI/2) {// OBJETIVO NO TERCEIRO QUAD
             return 0;
         } else { // OBJETIVO NO QUARTO QUAD
             return ANTI_HORARIO;
         }
     } else { // ROBO NO QUARTO QUAD
         if(angle_Obst_Goal > 0 && angle_Obst_Goal <= PI/2) { // OBJETIVO NO PRIMEIRO QUAD
             return ANTI_HORARIO;
         } else if(angle_Obst_Goal > PI/2 && angle_Obst_Goal <= PI) { // OBJETIVO NO SEGUNDO QUAD
         //  printf("DECIDE" );
             if(fabs(angle_Obst_Robot)+fabs(angle_Obst_Goal) < PI) return ANTI_HORARIO;
             else return HORARIO;
         } else if(angle_Obst_Goal > -PI && angle_Obst_Goal <= -PI/2) {// OBJETIVO NO TERCEIRO QUAD
             return HORARIO;
         } else { // OBJETIVO NO QUARTO QUAD
             return 0;
         }
     }
 }
potField()
double Strategy::potField (int robot_index, cv::Point goal, int behavior = 2)
Definition at line 464 of file strategy.cpp.
References adv, Ball, ball_angle, BALL_IS_OBS, ball_mag, BALL_NOT_OBS, BALL_ONLY_OBS, distance_meters(), Robots::get_position(), NO_OBS, PI, pot_angle, pot_goalMag, pot_goalTheta, pot_magnitude, pot_rotation_decision(), pot_theta, pot_thetaX, pot_thetaY, and Robots::set_usingPotField().
Referenced by pot_field_around().
{
     Robots::set_usingPotField(robot_index, true);
     double gain_rep = 10;
     double gain_att = 1;
     double rep_radius = 0.2;
     double ball_rep_radius = 0.3;
     // float rot_angle = 0;
     ball_angle = 0;
     ball_mag = 0;
     pot_thetaX = 0;
     pot_thetaY = 0;
     pot_theta = 0;
     pot_goalTheta = 0;
     pot_goalMag = 0;
     for (unsigned short i = 0; i < adv.size(); i++) {
         if(distance_meters(Robots::get_position(robot_index), adv.at(i)) > 0 && distance_meters(Robots::get_position(robot_index), adv.at(i)) < rep_radius) {
             pot_magnitude[i] = gain_rep*pow(1/(distance_meters(Robots::get_position(robot_index), adv.at(i)) - 1/rep_radius), 2)/2;
             pot_angle[i] = atan2(double(Robots::get_position(robot_index).y - adv.at(i).y),- double(Robots::get_position(robot_index).x - adv.at(i).x));
             if(pot_rotation_decision(robot_index,goal,adv.at(i)) == 0) {
                 pot_magnitude[i] = 0;
             } else if(pot_rotation_decision(robot_index,goal,adv.at(i))>0) {
                     pot_angle[i] = atan2(sin(pot_angle[i]+PI/2),cos(pot_angle[i]+PI/2));
                     // printf("HORARIO ");
             } else {
                 pot_angle[i] = atan2(sin(pot_angle[i]+3*PI/2),cos(pot_angle[i]+3*PI/2));
                     // printf("ANTI-HORARIO ");
             }
             // printf("adv[%d] x %d, y %d| magnitude [%d] %f | angle[%d] %f\n",i,adv.at(i).x,adv.at(i).y,i,pot_magnitude[i],i,pot_angle[i]*180/PI);
         } else {
             pot_magnitude[i] = 0;
             pot_angle[i] = 0;
         }
     }
     int j = 3;
     for (int i = 0; i < 3; i++) {
         if(i != robot_index) {
             if(distance_meters(Robots::get_position(robot_index), Robots::get_position(i)) < rep_radius) {
                 pot_magnitude[j] = gain_rep*pow(1/(distance_meters(Robots::get_position(robot_index), Robots::get_position(i)) - 1/rep_radius), 2)/2;
                 pot_angle[j] = atan2(double(Robots::get_position(robot_index).y - Robots::get_position(i).y),- double(Robots::get_position(robot_index).x - Robots::get_position(i).x));
                 if(pot_rotation_decision(robot_index,goal,Robots::get_position(i)) == 0) {
                     pot_magnitude[j] = 0;
                 } else if(pot_rotation_decision(robot_index,goal,Robots::get_position(i)) > 0) {
                     pot_angle[j] = atan2(sin(pot_angle[j]+PI/2),cos(pot_angle[j]+PI/2));
                     //  printf("HORARIO ");
                 } else{
                     pot_angle[j] = atan2(sin(pot_angle[j]+3*PI/2),cos(pot_angle[j]+3*PI/2));
                     //  printf("ANTI-HORARIO ");
                 }
             // printf("robots[%d] x %d, y %d|magnitude [%d] %f | angle[%d] %f\n",i,Robots::get_position(i).x,Robots::get_position(i).y,j,pot_magnitude[j],j,pot_angle[j]*180/PI);
             }else {
                 pot_magnitude[j] = 0;
                 pot_angle[j] = 0;
             }
             j++;
         }
     }
     switch(behavior) {
         case BALL_IS_OBS:
             if(distance_meters(Robots::get_position(robot_index), Ball) > 0 && distance_meters(Robots::get_position(robot_index), Ball) < ball_rep_radius) {
                 // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                 ball_mag = (gain_rep*pow(1/(distance_meters(Robots::get_position(robot_index), Ball) - 1/(ball_rep_radius)), 2)/2 );
                 // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                 ball_angle = atan2(double(Robots::get_position(robot_index).y - Ball.y),- double(Robots::get_position(robot_index).x - Ball.x));
                 if(pot_rotation_decision(robot_index,goal,Ball) == 0) {
                     ball_mag = 0;
                 } else if(pot_rotation_decision(robot_index,goal,Ball)>0) {
                     // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                     ball_angle = atan2(sin(ball_angle+PI/2),cos(ball_angle+PI/2));
                 //  printf("HORARIO ");
                 } else {
                     // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                     ball_angle = atan2(sin(ball_angle+3*PI/2),cos(ball_angle+3*PI/2));
                     //  printf("ANTI-HORARIO ");
                 }
                 pot_thetaY += ball_mag*sin(ball_angle);
                 pot_thetaX += ball_mag*cos(ball_angle);
             } else {
                 ball_mag = 0;
                 ball_angle = 0;
             }
             break;
         case BALL_ONLY_OBS:
             for(double &i : pot_magnitude) i = 0;
             if(distance_meters(Robots::get_position(robot_index), Ball) > 0 && distance_meters(Robots::get_position(robot_index), Ball) < ball_rep_radius) {
                 // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                 ball_mag = (gain_rep*pow(1/(distance_meters(Robots::get_position(robot_index), Ball) - 1/ball_rep_radius), 2)/2.0);
                 // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                 ball_angle = atan2(double(Robots::get_position(robot_index).y - Ball.y),- double(Robots::get_position(robot_index).x - Ball.x));
                 if(pot_rotation_decision(robot_index,goal,Ball) == 0) {
                     ball_mag = 0;
                 } else if(pot_rotation_decision(robot_index,goal,Ball) > 0) {
                     // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                     ball_angle = atan2(sin(ball_angle+PI/2),cos(ball_angle+PI/2));
                         //  printf("HORARIO ");
                 } else {
                     // !TODO Mudar variável para DOUBLE ou fazer cast para FLOAT?
                     ball_angle = atan2(sin(ball_angle+3*PI/2),cos(ball_angle+3*PI/2));
                     //  printf("ANTI-HORARIO ");
                 }
                 pot_thetaY = ball_mag*sin(ball_angle);
                 pot_thetaX = ball_mag*cos(ball_angle);
             } else {
                 ball_mag = 0;
                 ball_angle = 0;
             }
             break;
         case NO_OBS:
             for(double &i : pot_magnitude) i = 0;
             break;
         case BALL_NOT_OBS:
             break;
         default:break;
     }
     for (int i = 0; i < 5; i++) {
         pot_thetaY += pot_magnitude[i] * sin(pot_angle[i]);
         pot_thetaX += pot_magnitude[i] * cos(pot_angle[i]);
     }
     pot_goalTheta = atan2(double(Robots::get_position(robot_index).y -goal.y ),- double(Robots::get_position(robot_index).x - goal.x ));
     pot_goalMag = gain_att * pow(distance_meters(Robots::get_position(robot_index), goal), 2)/2;
     //  printf("goalMag %f | goalTheta %f\n",pot_goalMag,pot_goalTheta*180/PI);
     pot_thetaY += pot_goalMag * sin(pot_goalTheta);
     pot_thetaX += pot_goalMag * cos(pot_goalTheta);
     pot_theta = atan2(pot_thetaY, pot_thetaX);
     // pot_theta = robots[robot_index].orientation - pot_theta;
     // pot_theta = atan2(-sin(robots[robot_index].orientation - pot_theta),cos(robots[robot_index].orientation - pot_theta));
     // printf("THETA %f \n",pot_theta*180/PI);
     return pot_theta;
 }
reset_flags()
void Strategy::reset_flags ()
Definition at line 123 of file strategy.cpp.
References atk, def, gk, Robots::set_cmdType(), Robots::set_fixedPos(), Robots::set_usingPotField(), Robots::SIZE, transitions_enabled, and VECTOR.
Referenced by get_targets().
{
     for(int i = 0; i < Robots::SIZE; i++) {
         Robots::set_cmdType(i, Robots::CMD::VECTOR);
         Robots::set_fixedPos(i, false);
         Robots::set_usingPotField(i, false);
         if(transitions_enabled)
             atk = def = gk = 0;
     }
 }
set_Ball()
void Strategy::set_Ball (cv::Point b)
Definition at line 1130 of file strategy.cpp.
References LS::addValue(), Ball, Ball_Est, LS::estimate(), LS_ball_x, and LS_ball_y.
Referenced by CamCap::capture_and_show().
{
     Ball = b;
     LS_ball_x.addValue(Ball.x);
     LS_ball_y.addValue(Ball.y);
     Ball_Est.x = static_cast<int>(LS_ball_x.estimate(10));
     Ball_Est.y = static_cast<int>(LS_ball_y.estimate(10));
 }
set_constants()
void Strategy::set_constants (int w, int h)
< tamanho do gol em X
< tamanho da área em Y
< tamanho da área em X
Definition at line 36 of file strategy.cpp.
References CONST::ABS_BOX_SIZE_X, CONST::ABS_BOX_SIZE_Y, CONST::ABS_FIELD_HEIGHT, CONST::ABS_GOAL_SIZE_X, CONST::ABS_GOAL_SIZE_Y, CONST::ABS_GOAL_TO_GOAL_WIDTH, CONST::ABS_ROBOT_SIZE, CONST::collision_radius, CONST::COORD_BOX_ATK_X, CONST::COORD_BOX_DEF_X, CONST::COORD_BOX_DWN_Y, CONST::COORD_BOX_UP_Y, CONST::COORD_GOAL_ATK_FRONT_X, CONST::COORD_GOAL_DEF_FRONT_X, CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, CONST::COORD_MID_FIELD_X, CONST::corner_atk_limit, CONST::def_corner_line, CONST::fixed_pos_distance, CONST::goalie_line, CONST::goalie_offset, CONST::height, CONST::max_approach, CONST::max_collision_count, CONST::transition_y_distance, and CONST::width.
Referenced by CamCap::start_signal().
{
     width = w;
     height = h;
     // GOAL_DANGER_ZONE = false,
     // ADV_NA_AREA = false;
     // ABS_PLAYING_FIELD_WIDTH = (int) round(1.50*float(width)/1.70);
     ABS_GOAL_TO_GOAL_WIDTH = width;
     ABS_ROBOT_SIZE = (int) round(0.08*float(width)/1.70);
     // ABS_BALL_SIZE = (int) round(0.04*float(width)/1.70);
     COORD_MID_FIELD_X = ABS_GOAL_TO_GOAL_WIDTH/2;
     ABS_FIELD_HEIGHT = height;
     ABS_GOAL_SIZE_Y = (int) round(0.40*float(height)/1.30);
     ABS_GOAL_SIZE_X = (int) round(0.10*float(width)/1.70);
     COORD_GOAL_DEF_FRONT_X = ABS_GOAL_SIZE_X;
     COORD_GOAL_ATK_FRONT_X = ABS_GOAL_TO_GOAL_WIDTH - ABS_GOAL_SIZE_X;
     COORD_GOAL_MID_Y = ABS_FIELD_HEIGHT/2;
     COORD_GOAL_UP_Y = ABS_FIELD_HEIGHT/2 - ABS_GOAL_SIZE_Y/2;
     COORD_GOAL_DWN_Y = ABS_FIELD_HEIGHT/2 + ABS_GOAL_SIZE_Y/2;
     ABS_BOX_SIZE_Y = (int) round(0.70*float(height)/1.30);
     ABS_BOX_SIZE_X = (int) round(0.15*float(width)/1.70);
     COORD_BOX_DEF_X = ABS_GOAL_SIZE_X + ABS_BOX_SIZE_X; // linha da frente da área
     COORD_BOX_ATK_X = ABS_GOAL_TO_GOAL_WIDTH - (ABS_GOAL_SIZE_X + ABS_BOX_SIZE_X); // linha da frente da área adversária
     COORD_BOX_UP_Y = (int) round((ABS_FIELD_HEIGHT - ABS_BOX_SIZE_Y)/2.0); // canto de cima do gol
     COORD_BOX_DWN_Y = (int) round(ABS_BOX_SIZE_Y + (ABS_FIELD_HEIGHT - ABS_BOX_SIZE_Y)/2.0); // canto de baixo do gol
     // variáveis ajustáveis
     corner_atk_limit = COORD_BOX_ATK_X - ABS_ROBOT_SIZE;
     def_corner_line = COORD_BOX_DEF_X;
     // def_line = ABS_GOAL_TO_GOAL_WIDTH/3;
     // possession_distance = ABS_ROBOT_SIZE;
     collision_radius = ABS_ROBOT_SIZE/2;
     fixed_pos_distance = ABS_ROBOT_SIZE;
     max_approach = ABS_ROBOT_SIZE*2;
     max_collision_count = 30;
     goalie_line = COORD_GOAL_DEF_FRONT_X + ABS_ROBOT_SIZE/2;
     goalie_offset = ABS_ROBOT_SIZE;
     // transition_back_radius = ABS_ROBOT_SIZE*3;
     transition_y_distance = ABS_ROBOT_SIZE*4;
     // // Não usando
     // BANHEIRA     =   (int) (round((0.50*COMPRIMENTO_CAMPO_TOTAL))+round(0.16*float(width)/1.70));
     // DIVISAO_AREAS    =   (int) round((0.50*COMPRIMENTO_CAMPO_TOTAL) - 10); // O valor negativo é um offset para não ficar exatamente no meio.
     // OFFSET_BANHEIRA  =   (int) round(0.20*float(width)/1.70);
     // MEIO_GOL_X       =   (int) round(COMPRIMENTO_CAMPO_TOTAL-round(0.05*float(width)/1.70));
     // MEIO_GOL_Y       =   (int) round(LARGURA_CAMPO/2);
     // MAX_GOL_Y        =   (int) round(MEIO_GOL_Y + TAMANHO_GOL/2);
     // MIN_GOL_Y        =   (int) round(MEIO_GOL_Y - TAMANHO_GOL/2);
     // LINHA_ZAGA       =   (int) round(0.30*COMPRIMENTO_CAMPO_TOTAL);
     // // Parametros para atacante sem bola
     // OFFSET_RATIO =   (int) round(0.12*float(width)/1.70);
     // CONE_RATIO       =   (int) round(0.8*float(width)/1.70);
     // MAX_DECISION_COUNT = 10;
     // COUNT_DECISION = MAX_DECISION_COUNT;
     // TARGET_LOCK_COUNT = 10;
     // MAX_TARGET_LOCK_COUNT = 10;
     // // Parametros do Defensor na defesa
     // DESLOCAMENTO_ZAGA_ATAQUE =   (int) round(1.3*float(width)/1.70);
     // BALL_RADIUS = 100;
 }
set_role()
void Strategy::set_role (int i, int role)
Definition at line 217 of file strategy.cpp.
References NORMAL_STATE, Robots::set_role(), Robots::set_status(), and Robots::set_velocity().
Referenced by set_roles().
{
     Robots::set_status(i, NORMAL_STATE);
     Robots::set_role(i, role);
     Robots::set_velocity(i, role);
 }
set_roles()
void Strategy::set_roles ()
Definition at line 136 of file strategy.cpp.
References CONST::ABS_GOAL_SIZE_X, CONST::ABS_ROBOT_SIZE, atk, ATTACKER, Ball, compare_pos(), CONST::COORD_GOAL_DWN_Y, CONST::COORD_GOAL_MID_Y, CONST::COORD_GOAL_UP_Y, CONST::COORD_MID_FIELD_X, CONST::corner_atk_limit, def, DEFENDER, distance(), Robots::get_position(), Robots::get_role(), gk, GOALKEEPER, set_role(), Robots::SIZE, and transitions_enabled.
Referenced by get_targets().
{
     if(!transitions_enabled) {
         for(int i = 0; i < Robots::SIZE; i++) {
             switch(Robots::get_role(i)) {
                 case ATTACKER:
                     atk = i;
                 break;
                 case DEFENDER:
                     def = i;
                 break;
                 case GOALKEEPER:
                     gk = i;
                 break;
                 default:break;
             }
         }
         return;
     }
     //< lista ordenada de melhores posicionamentos; id do robo -> <distancia do alvo, angulo com o objetivo>
     std::vector< std::pair<int, std::pair<double, double> > > bestAtk, bestGk;
     cv::Point goal = cv::Point(ABS_GOAL_SIZE_X, COORD_GOAL_MID_Y);
     // ----- SELEÇÃO DE CANDIDATOS
     // pega os candidatos a atacante e ordena por melhor posicionamento e angulo da bola com o gol
     // !TODO calcular os angulos de todos os (robôs -> bola, bola-> gol)
     // !TODO verificar se está mais perto do ponto da defesa do que defensor
     for(unsigned short i = 0; i < Robots::SIZE; i++) {
         std::pair<int, std::pair<double, double> > temp = {i, {distance(Robots::get_position(i), Ball), 0}};
         bestAtk.push_back(temp);
     }
     sort(bestAtk.begin(), bestAtk.end(), compare_pos); // !TODO pode ser que exista uma forma mais eficiente de ordenar isso
     // pega os candidatos a goleiro e ordena por melhor posicionamento e angulo para nosso gol
     // !TODO deve verificar depois se o goleiro pode sair do gol ou não
     for(unsigned short i = 0; i < Robots::SIZE; i++) {
         if(i == bestAtk.at(0).first) continue; // !TODO tirar isso se quiser que o atacante possa ser goleiro também
         std::pair<int, std::pair<double, double> > temp = {i, {distance(Robots::get_position(i), goal), 0}};
         bestGk.push_back(temp);
     }
     sort(bestGk.begin(), bestGk.end(), compare_pos);
     // ----- ATRIBUIÇÃO INICIAL DE PAPÉIS
     // a gente tem garantido que o vetor não é vazio pois a visão, no pior caso, nos dá (-1, -1)
     atk = bestAtk.at(0).first;
     gk = bestGk.at(0).first;
     // seta o robô restante pra defensor
     // não precisa inicializar pois é sempre setado no for
     for(int i = 0; i < Robots::SIZE; i++) {
         if(i == atk || i == gk) continue;
         def = i;
         break;
     }
     // ----- SITUAÇÕES ESPECÍFICAS (TROCAS)
     // situação de cruzamento
     if(Ball.x > corner_atk_limit && Ball.y > COORD_GOAL_UP_Y + ABS_ROBOT_SIZE && Ball.y < COORD_GOAL_DWN_Y - ABS_ROBOT_SIZE // se a bola tá dentro da área
          && distance(Robots::get_position(atk), Ball) > 2.0 * ABS_ROBOT_SIZE // atacante não tem a posse de bola
          && Robots::get_position(def).x > COORD_MID_FIELD_X) { // defensor está depois do meio de campo esperando rebote
         int tmp = atk;
         atk = def;
         def = tmp;
     }
     // atacante perdeu a bola, é melhor defensor ir em cima
     else if(distance(Ball, Robots::get_position(atk)) > 3*ABS_ROBOT_SIZE // bola está longe do atacante
              && Ball.x < Robots::get_position(atk).x // bola está atrás do atacante
              && distance(Ball, Robots::get_position(def)) < COORD_GOAL_MID_Y // defensor está a até um meio campo de distância
              && Ball.x > Robots::get_position(def).x + ABS_ROBOT_SIZE/2) { // e tá na frente do defensor
         int tmp = atk;
         atk = def;
         def = tmp;
     }
     // seta o atacante
     set_role(atk, ATTACKER);
     // seta o goleiro
     set_role(gk, GOALKEEPER);
     // seta o defensor
     set_role(def, DEFENDER);
 }
Field Documentation
action1
bool Strategy::action1 = false
Definition at line 58 of file strategy.hpp.
Referenced by pot_field_around().
adv
std::vector<cv::Point> Strategy::adv
Definition at line 44 of file strategy.hpp.
Referenced by get_targets(), and potField().
atk
int Strategy::atk
Definition at line 48 of file strategy.hpp.
Referenced by def_routine(), get_targets(), reset_flags(), and set_roles().
Ball
cv::Point Strategy::Ball
Definition at line 28 of file strategy.hpp.
Referenced by atk_routine(), collision_check(), def_routine(), def_wait(), gk_routine(), has_ball(), pot_field_around(), potField(), set_Ball(), and set_roles().
ball_angle
double Strategy::ball_angle = 0
Definition at line 41 of file strategy.hpp.
Referenced by potField().
Ball_Est
cv::Point Strategy::Ball_Est
Definition at line 29 of file strategy.hpp.
Referenced by def_routine(), get_Ball_Est(), gk_routine(), pot_field_around(), and set_Ball().
ball_mag
double Strategy::ball_mag = 0
Definition at line 42 of file strategy.hpp.
Referenced by potField().
collision_count
int Strategy::collision_count[3]
Definition at line 45 of file strategy.hpp.
Referenced by collision_check().
def
int Strategy::def
Definition at line 48 of file strategy.hpp.
Referenced by atk_routine(), get_targets(), reset_flags(), and set_roles().
distBall
int Strategy::distBall
Definition at line 30 of file strategy.hpp.
frames_blocked
int Strategy::frames_blocked
Definition at line 51 of file strategy.hpp.
gk
int Strategy::gk
Definition at line 48 of file strategy.hpp.
Referenced by get_targets(), reset_flags(), and set_roles().
lock_angle
double Strategy::lock_angle
Definition at line 49 of file strategy.hpp.
LS_ball_x
LS Strategy::LS_ball_x
Definition at line 31 of file strategy.hpp.
Referenced by set_Ball(), and Strategy().
LS_ball_y
LS Strategy::LS_ball_y
Definition at line 32 of file strategy.hpp.
Referenced by set_Ball(), and Strategy().
opp
int Strategy::opp
Definition at line 48 of file strategy.hpp.
past_position
cv::Point Strategy::past_position[3]
Definition at line 47 of file strategy.hpp.
Referenced by collision_check(), and get_past().
past_transangle
double Strategy::past_transangle[3]
Definition at line 46 of file strategy.hpp.
Referenced by collision_check(), and get_past().
pot_angle
double Strategy::pot_angle[5]
Definition at line 40 of file strategy.hpp.
Referenced by potField().
pot_goalMag
double Strategy::pot_goalMag
Definition at line 38 of file strategy.hpp.
Referenced by potField().
pot_goalTheta
double Strategy::pot_goalTheta = 0
Definition at line 37 of file strategy.hpp.
Referenced by potField().
pot_magnitude
double Strategy::pot_magnitude[5]
Definition at line 39 of file strategy.hpp.
Referenced by potField().
pot_theta
double Strategy::pot_theta = 0
Definition at line 36 of file strategy.hpp.
Referenced by potField().
pot_thetaX
double Strategy::pot_thetaX = 0
Definition at line 34 of file strategy.hpp.
Referenced by potField().
pot_thetaY
double Strategy::pot_thetaY = 0
Definition at line 35 of file strategy.hpp.
Referenced by potField().
t
int Strategy::t = 0
Definition at line 55 of file strategy.hpp.
testFrame
TestFrame Strategy::testFrame
Definition at line 26 of file strategy.hpp.
Referenced by StrategyGUI::configureTestFrame(), get_variables(), and StrategyGUI::StrategyGUI().
timeout
int Strategy::timeout = 0
Definition at line 56 of file strategy.hpp.
transition_timeout
int Strategy::transition_timeout = 0
Definition at line 57 of file strategy.hpp.
transitions_enabled
bool Strategy::transitions_enabled = true
Definition at line 53 of file strategy.hpp.
Referenced by StrategyGUI::_event_transitions_checkbox_signal_clicked(), reset_flags(), and set_roles().
The documentation for this class was generated from the following files:
src/strategy.hpp
src/strategy.cpp