VSSS-INF: Vision Class Reference
Vision Class Reference
#include <vision.hpp>
Public Member Functions
Vision (int w, int h)
~Vision ()
void run (cv::Mat raw_frame)
Call preProcessing() method, searchTags() and pick-a-tag()
void setCalibParams (int H[5][2], int S[5][2], int V[5][2], int Amin[5], int E[5], int D[5], int B[5])
double calcDistance (cv::Point p1, cv::Point p2)
void startNewVideo (std::string videoName)
bool recordToVideo ()
bool finishVideo ()
bool isRecording ()
void savePicture (std::string in_name)
void switchMainWithAdv ()
cv::Point getBall ()
std::vector< cv::Point > getAdvs ()
cv::Mat getSplitFrame ()
cv::Mat getThreshold (int index)
int getHue (int index0, int index1)
int getSaturation (int index0, int index1)
int getValue (int index0, int index1)
int getErode (int index)
int getDilate (int index)
int getBlur (int index)
int getAmin (int index)
void setFrameSize (int inWidth, int inHeight)
int getFrameHeight ()
int getFrameWidth ()
void setHue (int index0, int index1, int inValue)
void setSaturation (int index0, int index1, int inValue)
void setValue (int index0, int index1, int inValue)
void setErode (int index, int inValue)
void setDilate (int index, int inValue)
void setBlur (int index, int inValue)
void setAmin (int index, int inValue)
void preloadHSV ()
Loads default values to vision object, making callibration easier.
Private Member Functions
void preProcessing ()
void posProcessing (int color)
Executes medianBlur, erode and dilate.
void segmentAndSearch (int color)
invokes posProcessing() and searchTags() methods
void searchTags (int color)
void findTags ()
void pick_a_tag ()
uses inSphere() method
int inSphere (Robots::_Status *robot, std::vector< Tag > *tempTags, cv::Point secondary)
Private Attributes
cv::Mat in_frame
cv::Mat hsv_frame
std::vector< cv::Mat > threshold_frame
cv::Mat splitFrame
std::vector< cv::Point > advRobots
cv::Point ball
std::vector< std::vector< Tag > > tags
int hue [5][2]
int saturation [5][2]
int value [5][2]
int dilate [5]
int erode [5]
int blur [5]
int areaMin [5]
int width
int height
bool bOnAir
cv::VideoWriter video
boost::thread_group threshold_threads
Static Private Attributes
static const int MAIN = 0
static const int GREEN = 1
static const int BALL = 2
static const int ADV = 3
static const int MAX_ADV = 3
static const int TOTAL_COLORS = 4
static const int MIN = 0
static const int MAX = 1
Detailed Description
Definition at line 25 of file vision.hpp.
Constructor & Destructor Documentation
Vision()
Vision::Vision (int w, int h)
Vision's constructor
Parameters
w width
h height
Definition at line 423 of file vision.cpp.
References tags, threshold_frame, and TOTAL_COLORS.
                            : width(w), height(h), bOnAir(false) {
     // Variables Init
     cv::Mat mat;
     std::vector<Tag> tagVec;
     for(int i = 0; i < TOTAL_COLORS; i++) {
         threshold_frame.push_back(mat);
         tags.push_back(tagVec);
     }
 }
~Vision()
Vision::~Vision ()
Definition at line 434 of file vision.cpp.
 {}
Member Function Documentation
calcDistance()
double Vision::calcDistance (cv::Point p1, cv::Point p2)
Calculates Euclidean distance between two points
Parameters
p1 first point
p2 second point
Returns
double value with distance value
Definition at line 165 of file vision.cpp.
Referenced by inSphere().
{
     return sqrt(pow(p1.x-p2.x,2) + pow(p1.y-p2.y,2));
 }
findTags()
void Vision::findTags () private
Invokes with threads the Vision::segmentAndSearch() method.
Definition at line 16 of file vision.cpp.
References segmentAndSearch(), threshold_threads, and TOTAL_COLORS.
Referenced by run().
                       {
     for (int i = 0; i < TOTAL_COLORS; i++)
         threshold_threads.add_thread(new boost::thread(&Vision::segmentAndSearch, this, i));
     threshold_threads.join_all();
 }
finishVideo()
bool Vision::finishVideo ()
Finishes video recording
Returns
true if was successful false if not
Definition at line 268 of file vision.cpp.
References bOnAir, debug_log, and video.
Referenced by VisionGUI::bt_record_video_pressed(), VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked(), and VisionGUI::~VisionGUI().
{
     if (!video.isOpened()) return false;
     debug_log("Finished video recording.");
     video.release();
     bOnAir = false;
     return true;
 }
getAdvs()
std::vector< cv::Point > Vision::getAdvs ()
Gets a pointer containing all adversary positions
Returns
pointer containing all adversary positions
Definition at line 388 of file vision.cpp.
References advRobots.
Referenced by CamCap::capture_and_show().
{
     return advRobots;
 }
getAmin()
int Vision::getAmin (int index)
Gets min area value
Parameters
index color position
Returns
min area value from color position
Definition at line 315 of file vision.cpp.
References areaMin.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return areaMin[index];
 }
getBall()
cv::Point Vision::getBall ()
Gets the ball position in image
Returns
cv::Point containing the ball position
Definition at line 282 of file vision.cpp.
References ball.
Referenced by CamCap::updateAllPositions().
{
     return ball;
 }
getBlur()
int Vision::getBlur (int index)
Gets blur value
Parameters
index color position
Returns
blur value from color position
Definition at line 311 of file vision.cpp.
References blur.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return blur[index];
 }
getDilate()
int Vision::getDilate (int index)
Gets dilate value
Parameters
index color position
Returns
dilate value from color position
Definition at line 307 of file vision.cpp.
References dilate.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return dilate[index];
 }
getErode()
int Vision::getErode (int index)
Gets erode value
Parameters
index color position
Returns
erode value (min or max) from color position
Definition at line 303 of file vision.cpp.
References erode.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return erode[index];
 }
getFrameHeight()
int Vision::getFrameHeight ()
Gets frame's height
Returns
height value from image
Definition at line 380 of file vision.cpp.
References height.
{
     return height;
 }
getFrameWidth()
int Vision::getFrameWidth ()
Gets frame's width
Returns
width value from image
Definition at line 384 of file vision.cpp.
References width.
{
     return width;
 }
getHue()
int Vision::getHue (int index0, int index1)
Gets hue (Hsv) value
Parameters
index0 color position
index1 min (0) or max (1)
Returns
hue value (min or max) from color position
Definition at line 291 of file vision.cpp.
References hue.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return hue[index0][index1];
 }
getSaturation()
int Vision::getSaturation (int index0, int index1)
Gets saturation (hSv) value
Parameters
index0 color position
index1 min (0) or max (1)
Returns
saturation value (min or max) from color position
Definition at line 295 of file vision.cpp.
References saturation.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return saturation[index0][index1];
 }
getSplitFrame()
cv::Mat Vision::getSplitFrame ()
Concatenate all frames(capture frame and threshold frames (ball, main color and secondary color))
Returns
concatenated image, with capture frame size with all frames
Definition at line 203 of file vision.cpp.
References in_frame, splitFrame, and threshold_frame.
Referenced by CamCap::capture_and_show().
{
     cv::Mat horizontal[2], vertical[2];
     for (int index = 0; index < 3; index++)
         cv::cvtColor(threshold_frame.at(index), threshold_frame.at(index), cv::COLOR_GRAY2RGB);
     cv::pyrDown(in_frame, vertical[0]);
     cv::pyrDown(threshold_frame.at(0), vertical[1]);
     cv::hconcat(vertical, 2, horizontal[0]);
     cv::pyrDown(threshold_frame.at(1), vertical[0]);
     cv::pyrDown(threshold_frame.at(2), vertical[1]);
     cv::hconcat(vertical, 2, horizontal[1]);
     cv::vconcat(horizontal, 2, splitFrame);
     // cv::imwrite("teste.png", splitFrame);
     return splitFrame;
 }
getThreshold()
cv::Mat Vision::getThreshold (int index)
Gets threshold image
Parameters
index color
Returns
threshold frame in color position
Definition at line 286 of file vision.cpp.
References threshold_frame.
Referenced by CamCap::capture_and_show().
{
     cv::cvtColor(threshold_frame.at(index), threshold_frame.at(index), cv::COLOR_GRAY2RGB);
     return threshold_frame.at(index);
 }
getValue()
int Vision::getValue (int index0, int index1)
Gets value (hsV) value (hehehe)
Parameters
index0 color position
index1 min (0) or max (1)
Returns
value value (min or max) from color position
Definition at line 299 of file vision.cpp.
References value.
Referenced by VisionGUI::__event_bt_left_HSV_calib_clicked(), VisionGUI::__event_bt_right_HSV_calib_clicked(), VisionGUI::__event_bt_switchMainAdv_clicked(), jsonSaveManager::save_camera(), and VSSS_GUI::V4LInterface::update_interface_camera().
{
     return value[index0][index1];
 }
inSphere()
int Vision::inSphere (Robots::_Status * robot, std::vector< Tag > * tempTags, cv::Point secondary) private
Checks if a given secondary tag belongs to our current primary tag
Parameters
robot robot's vector
tempTags tag's vector
secondary actual secondary position
Returns
0, if secondary tag isn't part of robot 1, if secondary tag is in right side -1, if secondary tag is in left side
Definition at line 147 of file vision.cpp.
References calcDistance(), height, Robots::_Status::orientation, Robots::_Status::position, ROBOT_RADIUS, and width.
Referenced by pick_a_tag().
{
     // se esta secundria faz parte do rob
     if(calcDistance(robot->position, secondary) <= ROBOT_RADIUS) {
         if(calcDistance(tempTags->at(0).frontPoint, secondary) < calcDistance(tempTags->at(0).rearPoint, secondary)) {
             tempTags->at(0).switchPoints();
             // recalcula a orientao com os novos pontos (isso s  feito uma vez em cada rob, se necessrio)
             robot->orientation = atan2((tempTags->at(0).frontPoint.y-robot->position.y)*1.3/height,(tempTags->at(0).frontPoint.x-robot->position.x)*1.5/width);
         }
         double secSide = atan2((secondary.y-robot->position.y)*1.3/height,(secondary.x-robot->position.x)*1.5/width);
         // Clculo do ngulo de orientao para diferenciar robs de mesma cor
         return (atan2(sin(secSide-robot->orientation+3.1415), cos(secSide-robot->orientation+3.1415))) > 0 ? 1 : -1;
     }
     return 0;
 }
isRecording()
bool Vision::isRecording ()
Verifies if is recording
Returns
true if is recording false if isn't recording
Definition at line 278 of file vision.cpp.
References bOnAir.
Referenced by VisionGUI::bt_record_video_pressed(), VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked(), and VisionGUI::~VisionGUI().
{
     return bOnAir;
 }
pick_a_tag()
void Vision::pick_a_tag () private
uses inSphere() method
Give tags to the robots
Definition at line 85 of file vision.cpp.
References ADV, advRobots, BALL, ball, GREEN, height, inSphere(), MAIN, Robots::_Status::orientation, Robots::_Status::position, Robots::set_orientation(), Robots::set_position(), Robots::set_secondary_tag(), tags, and width.
Referenced by run().
{
     // OUR ROBOTS
     for(unsigned short i = 0; i < tags.at(MAIN).size() && i<3; i++) {
         std::vector<Tag> tempTags;
         Robots::_Status robot;
         // Posio do rob
         robot.position = (cv::Point_<int>) tags.at(MAIN).at(i).position;
         // Clculo da orientao de acordo com os pontos rear e front
         robot.orientation = atan2((tags.at(MAIN).at(i).frontPoint.y - robot.position.y) * 1.3 / height,
                                   (tags.at(MAIN).at(i).frontPoint.x - robot.position.x) * 1.5 / width);
         // Armazena a tag
         tempTags.push_back(tags.at(MAIN).at(i));
         // Para cada tag principal, verifica quais so as secundrias correspondentes
         for (unsigned j = 0;
              j < tags.at(GREEN).size(); j++) { // (no usei unsigned short pois pode ter muitas tags verdes)
             // j faz a atribuio verificando se o valor retornado  0 (falso); alm disso, altera a orientao caso esteja errada
             int tmpSide = inSphere(&robot, &tempTags, tags.at(GREEN).at(j).position);
             if (tmpSide) {
                 tags.at(GREEN).at(j).left = tmpSide > 0;
                 // calculos feitos, joga tag no vetor
                 tempTags.push_back(tags.at(GREEN).at(j));
                 // identifica se j tem mais de duas tags (amarela e uma verde.)
                 if (tempTags.size() > 2) {
                     break;
                 }
             }
         }
         // D nome aos bois (robs)
         if (tempTags.size() > 2) { // se tem trs tags,  o full pick-a
             Robots::set_position(2, robot.position);
             Robots::set_orientation(2, robot.orientation);
             Robots::set_secondary_tag(2, tempTags.at(0).frontPoint);
             //robot_list.at(2).rearPoint = tempTags.at(0).rearPoint;
         } else if (tempTags.size() > 1) { // no classifica se no tiver encontrado pelo menos uma verde
             if (tempTags.at(1).left) {
                 Robots::set_position(0, robot.position);
                 Robots::set_orientation(0, robot.orientation);
                 Robots::set_secondary_tag(0, tempTags.at(0).frontPoint);
             } else {
                 Robots::set_position(1, robot.position);
                 Robots::set_orientation(1, robot.orientation);
                 Robots::set_secondary_tag(1, tempTags.at(0).frontPoint);
             }
         }
     } // OUR ROBOTS
     // ADV ROBOTS
     advRobots.clear();
     for(int i = 0; i < tags.at(ADV).size(); i++) {
         advRobots.push_back(tags.at(ADV).at(i).position);
     }
     // BALL POSITION
     if (!tags[BALL].empty())
         ball = tags.at(BALL).at(0).position;
 }
posProcessing()
void Vision::posProcessing (int color) private
Executes medianBlur, erode and dilate.
Run pos-processing methods in actual frame
Parameters
color ball, main or secondary color
Definition at line 33 of file vision.cpp.
References blur, dilate, erode, and threshold_frame.
Referenced by segmentAndSearch().
{
     cv::Mat erodeElement = cv::getStructuringElement( cv::MORPH_RECT,cv::Size(3,3));
     cv::Mat dilateElement = cv::getStructuringElement( cv::MORPH_RECT,cv::Size(3,3));
     cv::medianBlur(threshold_frame.at(color), threshold_frame.at(color), blur[color]);
     cv::erode(threshold_frame.at(color),threshold_frame.at(color),erodeElement,cv::Point(-1,-1),erode[color]);
     cv::dilate(threshold_frame.at(color),threshold_frame.at(color),dilateElement,cv::Point(-1,-1),dilate[color]);
 }
preloadHSV()
void Vision::preloadHSV ()
Loads default values to vision object, making callibration easier.
Definition at line 392 of file vision.cpp.
References setAmin(), setBlur(), setErode(), setHue(), setSaturation(), and setValue().
Referenced by CamCap::start_signal().
{
     for(int i = 0; i < 4; i++) {
         setBlur(i, 5);
     }
     setHue(0, 0, 20);
     setHue(0, 1, 30);
     setSaturation(0, 0, 50);
     setValue(0, 0, 150);
     setErode(0, 1);
     setAmin(0, 70);
     setHue(1, 0, 31);
     setHue(1, 1, 60);
     setSaturation(1, 0, 45);
     setValue(1, 0, 150);
     setAmin(1, 40);
     setHue(2, 0, 1);
     setHue(2, 1, 15);
     setSaturation(2, 0, 70);
     setValue(2, 0, 130);
     setAmin(2, 50);
     setHue(3, 0, 55);
     setHue(3, 1, 150);
     setSaturation(3, 0, 50);
     setValue(3, 0, 150);
     setErode(3, 1);
     setAmin(3, 70);
 }
preProcessing()
void Vision::preProcessing () private
Run pre-processing methods in actual frame
Definition at line 12 of file vision.cpp.
References hsv_frame, and in_frame.
Referenced by run().
{
     cv::cvtColor(in_frame,hsv_frame,cv::COLOR_RGB2HSV);
 }
recordToVideo()
bool Vision::recordToVideo ()
Writes the input frame in video object
Returns
false if camera is closed, true if frame was successful written
Definition at line 257 of file vision.cpp.
References in_frame, and video.
Referenced by run().
{
     if (!video.isOpened()) return false;
     cv::Mat frame = in_frame.clone();
     cv::cvtColor(frame, frame, cv::COLOR_RGB2BGR);
     video.write(frame);
     return true;
 }
run()
void Vision::run (cv::Mat raw_frame)
Call preProcessing() method, searchTags() and pick-a-tag()
Run the vision
Parameters
raw_frame image from camcap.hpp
Definition at line 4 of file vision.cpp.
References bOnAir, findTags(), in_frame, pick_a_tag(), preProcessing(), and recordToVideo().
Referenced by CamCap::capture_and_show().
{
     in_frame = raw_frame.clone();
     if (bOnAir) recordToVideo();
     preProcessing();
     findTags();
     pick_a_tag();
 }
savePicture()
void Vision::savePicture (std::string in_name)
Save a picture
Parameters
in_name picture's name
Definition at line 241 of file vision.cpp.
References in_frame.
Referenced by VisionGUI::bt_save_picture_clicked().
{
     cv::Mat frame = in_frame.clone();
     std::string picName = "media/pictures/" + in_name + ".png";
     cv::cvtColor(frame, frame, cv::COLOR_RGB2BGR);
     cv::imwrite(picName, frame);
 }
searchTags()
void Vision::searchTags (int color) private
Search tag in threshold frames
Parameters
color frame indicator (ball, main or secondary frame)
See also
Vision::searchSecondaryTags
Definition at line 42 of file vision.cpp.
References ADV, areaMin, MAIN, tags, and threshold_frame.
Referenced by segmentAndSearch().
{
     std::vector< std::vector<cv::Point> > contours;
     std::vector<cv::Vec4i> hierarchy;
     tags.at(color).clear();
     cv::findContours(threshold_frame.at(color),contours,hierarchy,cv::RETR_CCOMP,cv::CHAIN_APPROX_NONE);
     for(int i = 0; i < contours.size(); i++) {
         double area = contourArea(contours[i]);
         if(area >= areaMin[color]) {
             cv::Moments moment = moments(cv::Mat(contours[i]));
             // seta as linhas para as tags principais do pick-a-tag
             if(color == MAIN) {
                 tags.at(color).push_back(Tag(cv::Point(moment.m10/area, moment.m01/area), area));
                 // tem que ter jogado a tag no vetor antes de mexer nos valores dela
                 cv::Vec4f line;
                 cv::fitLine(cv::Mat(contours[i]),line,2,0,0.01,0.01);
                 tags.at(color).at(tags.at(color).size() - 1).setLine(line);
             } else if(color == ADV) {
                 if(tags.at(color).size() >= 3) {
                     // pega o menor ndice
                     int menor = 0;
                     for(int j = 1; j < 3; j++) {
                         if(tags.at(color).at(j).area < tags.at(color).at(menor).area)
                         menor = j;
                     }
                     if(menor < tags.at(color).size() && area > tags.at(color).at(menor).area)
                     tags.at(color).at(menor) = Tag(cv::Point(moment.m10/area, moment.m01/area), area);
                 } else {
                   tags.at(color).push_back(Tag(cv::Point(moment.m10/area, moment.m01/area), area));
                 }
             } else {
                 tags.at(color).push_back(Tag(cv::Point(moment.m10/area, moment.m01/area), area));
             }
         }
     }
 }
segmentAndSearch()
void Vision::segmentAndSearch (int color) private
invokes posProcessing() and searchTags() methods
Make the threshold with interface values
Parameters
color threshold color, indicates threshold frame in vector
Definition at line 23 of file vision.cpp.
References hsv_frame, hue, MAX, MIN, posProcessing(), saturation, searchTags(), threshold_frame, and value.
Referenced by findTags().
{
     cv::Mat frame = hsv_frame.clone();
     inRange(frame,cv::Scalar(hue[color][MIN],saturation[color][MIN],value[color][MIN]),
     cv::Scalar(hue[color][MAX],saturation[color][MAX],value[color][MAX]),threshold_frame.at(color));
     posProcessing(color);
     searchTags(color);
 }
setAmin()
void Vision::setAmin (int index, int inValue)
Sets area min value
Parameters
index0 color position in vector
inValue area min value
Definition at line 367 of file vision.cpp.
References areaMin, debug_error, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Amin_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
     if(index >= 0 && index < TOTAL_COLORS) {
         areaMin[index] = inValue;
     } else {
         debug_error("Vision:setAmin: could not set (invalid index)");
     }
 }
setBlur()
void Vision::setBlur (int index, int inValue)
Sets blur value
Parameters
index0 color position in vector
inValue blur value
Definition at line 359 of file vision.cpp.
References blur, debug_error, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Blur_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
     if(index >= 0 && index < TOTAL_COLORS) {
         blur[index] = inValue;
     } else {
         debug_error("Vision:setBlur: could not set (invalid index)");
     }
 }
setCalibParams()
void Vision::setCalibParams (int H[5][2], int S[5][2], int V[5][2], int Amin[5], int E[5], int D[5], int B[5])
Set HSV calib parameters
Note
receive values from interface
Parameters
H hue value
S saturation value
V value
Amin area min
E erode value
D dilate value
B blur value
Definition at line 227 of file vision.cpp.
References areaMin, blur, dilate, erode, hue, saturation, and value.
Referenced by VisionGUI::init_calib_params().
{
     for (int i = 0; i < 5; i++) {
         areaMin[i] = Amin[i];
         erode[i] = E[i];
         dilate[i] = D[i];
         blur[i] = B[i];
         for (int j = 0; j < 2; j++) {
             hue[i][j] = H[i][j];
             saturation[i][j] = S[i][j];
             value[i][j] = V[i][j];
         }
     }
 }
setDilate()
void Vision::setDilate (int index, int inValue)
Sets dilation value
Parameters
index0 color position in vector
inValue dilation value
Definition at line 351 of file vision.cpp.
References debug_error, dilate, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Dilate_value_changed(), and jsonSaveManager::load_camera().
{
     if(index >= 0 && index < TOTAL_COLORS) {
         dilate[index] = inValue;
     } else {
         debug_error("Vision:setDilate: could not set (invalid index)");
     }
 }
setErode()
void Vision::setErode (int index, int inValue)
Sets erosion value
Parameters
index0 color position in vector
inValue erosion value
Definition at line 343 of file vision.cpp.
References debug_error, erode, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Erode_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
     if(index >= 0 && index < TOTAL_COLORS) {
         erode[index] = inValue;
     } else {
         debug_error("Vision:setErode: could not set (invalid index)");
     }
 }
setFrameSize()
void Vision::setFrameSize (int inWidth, int inHeight)
Sets the width and height
Parameters
inWidth input width
inHeight input height
Definition at line 375 of file vision.cpp.
References height, and width.
Referenced by VisionGUI::setFrameSize().
{
     if (inWidth >= 0) width = inWidth;
     if (inHeight >= 0) height = inHeight;
 }
setHue()
void Vision::setHue (int index0, int index1, int inValue)
Sets hue (Hsv) value
Parameters
index0 color position in vector
index1 0 to min hue value, otherwise 1 to max hue value
inValue hue value
Definition at line 319 of file vision.cpp.
References debug_error, hue, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Hmax_value_changed(), VisionGUI::HScale_Hmin_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
     if(index0 >= 0 && index0 < TOTAL_COLORS && (index1 == 0 || index1 == 1)) {
         hue[index0][index1] = inValue;
     } else {
         debug_error("Vision:setHue: could not set (invalid index)");
     }
 }
setSaturation()
void Vision::setSaturation (int index0, int index1, int inValue)
Sets saturation (hSv) value
Parameters
index0 color position in vector
index1 0 to min saturation value, otherwise 1 to max saturation value
inValue saturation value
Definition at line 327 of file vision.cpp.
References debug_error, saturation, and TOTAL_COLORS.
Referenced by VisionGUI::HScale_Smax_value_changed(), VisionGUI::HScale_Smin_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
     if(index0 >= 0 && index0 < TOTAL_COLORS && (index1 == 0 || index1 == 1)) {
         saturation[index0][index1] = inValue;
     } else {
         debug_error("Vision:setSaturation: could not set (invalid index)");
     }
 }
setValue()
void Vision::setValue (int index0, int index1, int inValue)
Sets value (hsV) value
Parameters
index0 color position in vector
index1 0 to min saturation value, otherwise 1 to max saturation value
inValue value value
Definition at line 335 of file vision.cpp.
References debug_error, TOTAL_COLORS, and value.
Referenced by VisionGUI::HScale_Vmax_value_changed(), VisionGUI::HScale_Vmin_value_changed(), jsonSaveManager::load_camera(), and preloadHSV().
{
   if(index0 >= 0 && index0 < TOTAL_COLORS && (index1 == 0 || index1 == 1)) {
       value[index0][index1] = inValue;
   } else{
       debug_error("Vision:setValue: could not set (invalid index)");
   }
 }
startNewVideo()
void Vision::startNewVideo (std::string videoName)
Start a new video
Parameters
videoName video name
Definition at line 249 of file vision.cpp.
References bOnAir, debug_log, height, video, and width.
Referenced by VisionGUI::bt_record_video_pressed(), and VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked().
{
     std::string videoName = "media/videos/" + in_name + ".avi";
     video.open(videoName, cv::VideoWriter::fourcc('M','J','P','G'), 30, cv::Size(width,height));
     debug_log("Started a new video recording.");
     bOnAir = true;
 }
switchMainWithAdv()
void Vision::switchMainWithAdv ()
Switch main color to adversary color
Note
main and adversary color will be blue or yellow.
Definition at line 169 of file vision.cpp.
References ADV, areaMin, blur, dilate, erode, hue, MAIN, MAX, MIN, saturation, and value.
Referenced by VisionGUI::__event_bt_switchMainAdv_clicked().
{
     int tmp;
     for(int i = MIN; i <= MAX; i++) {
         tmp = hue[MAIN][i];
         hue[MAIN][i] = hue[ADV][i];
         hue[ADV][i] = tmp;
         tmp = saturation[MAIN][i];
         saturation[MAIN][i] = saturation[ADV][i];
         saturation[ADV][i] = tmp;
         tmp = value[MAIN][i];
         value[MAIN][i] = value[ADV][i];
         value[ADV][i] = tmp;
     }
     tmp = areaMin[MAIN];
     areaMin[MAIN] = areaMin[ADV];
     areaMin[ADV] = tmp;
     tmp = erode[MAIN];
     erode[MAIN] = erode[ADV];
     erode[ADV] = tmp;
     tmp = dilate[MAIN];
     dilate[MAIN] = dilate[ADV];
     dilate[ADV] = tmp;
     tmp = blur[MAIN];
     blur[MAIN] = blur[ADV];
     blur[ADV] = tmp;
 }
Field Documentation
ADV
const int Vision::ADV = 3 static private
Definition at line 33 of file vision.hpp.
Referenced by pick_a_tag(), searchTags(), and switchMainWithAdv().
advRobots
std::vector<cv::Point> Vision::advRobots private
Definition at line 44 of file vision.hpp.
Referenced by getAdvs(), and pick_a_tag().
areaMin
int Vision::areaMin[5] private
Definition at line 59 of file vision.hpp.
Referenced by getAmin(), searchTags(), setAmin(), setCalibParams(), and switchMainWithAdv().
BALL
const int Vision::BALL = 2 static private
Definition at line 32 of file vision.hpp.
Referenced by pick_a_tag().
ball
cv::Point Vision::ball private
Definition at line 47 of file vision.hpp.
Referenced by getBall(), and pick_a_tag().
blur
int Vision::blur[5] private
Definition at line 58 of file vision.hpp.
Referenced by getBlur(), posProcessing(), setBlur(), setCalibParams(), and switchMainWithAdv().
bOnAir
bool Vision::bOnAir private
Definition at line 66 of file vision.hpp.
Referenced by finishVideo(), isRecording(), run(), and startNewVideo().
dilate
int Vision::dilate[5] private
Definition at line 56 of file vision.hpp.
Referenced by getDilate(), posProcessing(), setCalibParams(), setDilate(), and switchMainWithAdv().
erode
int Vision::erode[5] private
Definition at line 57 of file vision.hpp.
Referenced by getErode(), posProcessing(), setCalibParams(), setErode(), and switchMainWithAdv().
GREEN
const int Vision::GREEN = 1 static private
Definition at line 30 of file vision.hpp.
Referenced by pick_a_tag().
height
int Vision::height private
Definition at line 63 of file vision.hpp.
Referenced by getFrameHeight(), inSphere(), pick_a_tag(), setFrameSize(), and startNewVideo().
hsv_frame
cv::Mat Vision::hsv_frame private
Definition at line 40 of file vision.hpp.
Referenced by preProcessing(), and segmentAndSearch().
hue
int Vision::hue[5][2] private
Definition at line 53 of file vision.hpp.
Referenced by getHue(), segmentAndSearch(), setCalibParams(), setHue(), and switchMainWithAdv().
in_frame
cv::Mat Vision::in_frame private
Definition at line 40 of file vision.hpp.
Referenced by getSplitFrame(), preProcessing(), recordToVideo(), run(), and savePicture().
MAIN
const int Vision::MAIN = 0 static private
Definition at line 29 of file vision.hpp.
Referenced by pick_a_tag(), searchTags(), and switchMainWithAdv().
MAX
const int Vision::MAX = 1 static private
Definition at line 37 of file vision.hpp.
Referenced by segmentAndSearch(), and switchMainWithAdv().
MAX_ADV
const int Vision::MAX_ADV = 3 static private
Definition at line 34 of file vision.hpp.
MIN
const int Vision::MIN = 0 static private
Definition at line 36 of file vision.hpp.
Referenced by segmentAndSearch(), and switchMainWithAdv().
saturation
int Vision::saturation[5][2] private
Definition at line 54 of file vision.hpp.
Referenced by getSaturation(), segmentAndSearch(), setCalibParams(), setSaturation(), and switchMainWithAdv().
splitFrame
cv::Mat Vision::splitFrame private
Definition at line 42 of file vision.hpp.
Referenced by getSplitFrame().
tags
std::vector<std::vector<Tag> > Vision::tags private
Definition at line 50 of file vision.hpp.
Referenced by pick_a_tag(), searchTags(), and Vision().
threshold_frame
std::vector<cv::Mat> Vision::threshold_frame private
Definition at line 41 of file vision.hpp.
Referenced by getSplitFrame(), getThreshold(), posProcessing(), searchTags(), segmentAndSearch(), and Vision().
threshold_threads
boost::thread_group Vision::threshold_threads private
Definition at line 72 of file vision.hpp.
Referenced by findTags().
TOTAL_COLORS
const int Vision::TOTAL_COLORS = 4 static private
Definition at line 35 of file vision.hpp.
Referenced by findTags(), setAmin(), setBlur(), setDilate(), setErode(), setHue(), setSaturation(), setValue(), and Vision().
value
int Vision::value[5][2] private
Definition at line 55 of file vision.hpp.
Referenced by getValue(), segmentAndSearch(), setCalibParams(), setValue(), and switchMainWithAdv().
video
cv::VideoWriter Vision::video private
Definition at line 69 of file vision.hpp.
Referenced by finishVideo(), recordToVideo(), and startNewVideo().
width
int Vision::width private
Definition at line 62 of file vision.hpp.
Referenced by getFrameWidth(), inSphere(), pick_a_tag(), setFrameSize(), and startNewVideo().
The documentation for this class was generated from the following files:
src/vision/vision.hpp
src/vision/vision.cpp