VSSS-INF: VisionGUI Class Reference
VisionGUI Class Reference
#include <visionGUI.hpp>
Public Member Functions
void selectFrame (int sector)
void setFrameSize (int inWidth, int inHeight)
bool getIsSplitView ()
VisionGUI ()
~VisionGUI ()
Data Fields
Vision * vision
Gtk::ToggleButton bt_HSV_calib
int Img_id
bool HSV_calib_event_flag
Gtk::RadioButton rb_original_view
Gtk::RadioButton rb_split_view
Gtk::Scale HScale_Hmin
Gtk::Scale HScale_Smin
Gtk::Scale HScale_Vmin
Gtk::Scale HScale_Hmax
Gtk::Scale HScale_Smax
Gtk::Scale HScale_Vmax
Gtk::Scale HScale_Dilate
Gtk::Scale HScale_Erode
Gtk::Scale HScale_Blur
Gtk::Scale HScale_Amin
Gtk::ToggleButton bt_record_video
Gtk::Button bt_save_picture
Gtk::Entry en_video_name
Gtk::Entry en_picture_name
Gtk::RadioButton rb_mode_GMM
Gtk::RadioButton rb_mode_HSV
Private Member Functions
void __event_bt_HSV_calib_pressed ()
Event triggered when HSV Calib button is pressed.
void __event_bt_right_HSV_calib_clicked ()
Event triggered when HSV Calib right button is pressed.
void __event_bt_left_HSV_calib_clicked ()
Event triggered when HSV Calib left button is pressed.
void __event_bt_switchMainAdv_clicked ()
Event triggered when 'Main <-> Adv' button is pressed.
void __event_rb_split_mode_clicked ()
Turns 'isSplitView' flag active when triggered when Split mode is selected.
void bt_save_picture_clicked ()
Saves the actual frame image in /media/pictures when 'save' button is clicked If 'Picture name' textfield is empty, a numeric ID value will be assigned.
void bt_record_video_pressed ()
Starts video recording when 'REC' button is pressed, changing its label to 'Stop', and vice-versa. If 'Video name' textfield is empty, a numeric ID value will be assigned.
void __create_frm_hsv ()
Creates HSV calibration frame and its inner elements. Ataches interface signals (button pressing/clicking, values change) to events.
void __create_frm_capture ()
Creates HSV calibration frame and its inner elements. Ataches interface signals (button pressing/clicking) to events.
void __create_frm_split_view ()
Creates Split View frame and its inner elements. Ataches interface signals (signals pressing/clicking) to events.
void HScale_Hmin_value_changed ()
Call Vision's setHue method passsing Hmin value as a parameter.
void HScale_Smin_value_changed ()
Call Vision's setSaturation method passsing Smin value as a parameter.
void HScale_Vmin_value_changed ()
Call Vision's setValue method passsing Vmin value as a parameter.
void HScale_Hmax_value_changed ()
Call Vision's setHue method passsing Hmax value as a parameter.
void HScale_Smax_value_changed ()
Call Vision's setSaturation method passsing Smax value as a parameter.
void HScale_Vmax_value_changed ()
Call Vision's setValue method passsing Vmax value as a parameter.
void HScale_Dilate_value_changed ()
Call Vision's setDilate method passsing Dilate value as a parameter.
void HScale_Erode_value_changed ()
Call Vision's Erode method passsing Erode value as a parameter.
void HScale_Blur_value_changed ()
Call Vision's setBlur method passsing Blur value as a parameter.
void HScale_Amin_value_changed ()
Call Vision's setAmin method passsing Amin value as a parameter.
void init_calib_params ()
Sets initial calibration parameter values shown at interface.
Private Attributes
bool isSplitView
int picIndex
int vidIndex
Gtk::Label HSV_label
Gtk::Button bt_HSV_left
Gtk::Button bt_HSV_right
Gtk::Button bt_switchMainAdv
Detailed Description
Definition at line 12 of file visionGUI.hpp.
Constructor & Destructor Documentation
VisionGUI()
VisionGUI::VisionGUI ()
Definition at line 581 of file visionGUI.cpp.
References __create_frm_capture(), __create_frm_hsv(), __create_frm_split_view(), init_calib_params(), and vision.
                      :
   HSV_calib_event_flag(false), Img_id(0), vidIndex(0), picIndex(0), isSplitView(false)
 {
     vision = new Vision(640, 480);
     __create_frm_capture();
     __create_frm_split_view();
     __create_frm_hsv();
     init_calib_params();
 }
~VisionGUI()
VisionGUI::~VisionGUI ()
Definition at line 594 of file visionGUI.cpp.
References Vision::finishVideo(), Vision::isRecording(), and vision.
                       {
     if(vision->isRecording()) vision->finishVideo();
 }
Member Function Documentation
__create_frm_capture()
void VisionGUI::__create_frm_capture () private
Creates HSV calibration frame and its inner elements. Ataches interface signals (button pressing/clicking) to events.
Definition at line 49 of file visionGUI.cpp.
References bt_record_video, bt_record_video_pressed(), bt_save_picture, bt_save_picture_clicked(), en_picture_name, and en_video_name.
Referenced by VisionGUI().
{
     Gtk::VBox * vbox;
     Gtk::Grid * grid;
     Gtk::Label * label;
     Gtk::Frame * frame;
     vbox = new Gtk::VBox();
     grid = new Gtk::Grid();
     frame = new Gtk::Frame();
     pack_start(*frame, false, false, 5);
     frame->add(*vbox);
     vbox->pack_start(*grid, false, true, 5);
     vbox->set_halign(Gtk::ALIGN_CENTER);
     vbox->set_valign(Gtk::ALIGN_CENTER);
     frame->set_label("Video/Image Capture");
     grid->set_border_width(5);
     grid->set_column_spacing(10);
     grid->set_row_spacing(5);
     label = new Gtk::Label("Picture Name:");
     label->set_alignment(1.0);
     grid->attach(*label, 0, 0, 1, 1);
     label = new Gtk::Label("Video Name:");
     label->set_alignment(1.0);
     grid->attach(*label, 0, 1, 1, 1);
     grid->attach(en_picture_name, 1, 0, 1, 1);
     grid->attach(en_video_name, 1, 1, 1, 1);
     bt_save_picture.set_label("Save");
     bt_record_video.set_label("REC");
     grid->attach(bt_save_picture, 2, 0, 1, 1);
     grid->attach(bt_record_video, 2, 1, 1, 1);
     en_video_name.set_state(Gtk::STATE_INSENSITIVE);
     en_picture_name.set_state(Gtk::STATE_INSENSITIVE);
     bt_record_video.set_state(Gtk::STATE_INSENSITIVE);
     bt_save_picture.set_state(Gtk::STATE_INSENSITIVE);
     bt_record_video.signal_pressed().connect(sigc::mem_fun(*this, &VisionGUI::bt_record_video_pressed));
     bt_save_picture.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::bt_save_picture_clicked));
 }
__create_frm_hsv()
void VisionGUI::__create_frm_hsv () private
Creates HSV calibration frame and its inner elements. Ataches interface signals (button pressing/clicking, values change) to events.
Definition at line 125 of file visionGUI.cpp.
References __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), bt_HSV_calib, bt_HSV_left, bt_HSV_right, bt_switchMainAdv, HScale_Amin, HScale_Amin_value_changed(), HScale_Blur, HScale_Blur_value_changed(), HScale_Dilate, HScale_Dilate_value_changed(), HScale_Erode, HScale_Erode_value_changed(), HScale_Hmax, HScale_Hmax_value_changed(), HScale_Hmin, HScale_Hmin_value_changed(), HScale_Smax, HScale_Smax_value_changed(), HScale_Smin, HScale_Smin_value_changed(), HScale_Vmax, HScale_Vmax_value_changed(), HScale_Vmin, HScale_Vmin_value_changed(), and HSV_label.
Referenced by VisionGUI().
{
     Gtk::VBox * vbox;
     Gtk::Grid * grid;
     Gtk::Label * label;
     Gtk::Frame * frame;
     vbox = new Gtk::VBox();
     grid = new Gtk::Grid();
     frame = new Gtk::Frame();
     pack_start(*frame, false, false, 5);
     frame->add(*vbox);
     vbox->pack_start(*grid, false, true, 5);
     vbox->set_halign(Gtk::ALIGN_CENTER);
     vbox->set_valign(Gtk::ALIGN_CENTER);
     frame->set_label("HSV Calibration");
     grid->set_border_width(5);
     grid->set_column_spacing(15);
     grid->set_row_spacing(0);
     // grid->set_column_homogeneous(true);
     bt_HSV_calib.set_label("HSV Calib.");
     grid->attach(bt_HSV_calib, 0, 0, 1, 1);
     bt_HSV_left.set_label(" < ");
     grid->attach(bt_HSV_left, 2, 0, 1, 1);
     HSV_label.set_text("Main");
     grid->attach(HSV_label, 3, 0, 1, 1);
     bt_HSV_right.set_label(" > ");
     grid->attach(bt_HSV_right, 4, 0, 1, 1);
     bt_switchMainAdv.set_label("Main <-> Adv");
     grid->attach(bt_switchMainAdv, 6, 0, 1, 1);
     grid = new Gtk::Grid();
     grid->set_border_width(5);
     grid->set_column_spacing(15);
     grid->set_row_spacing(0);
     grid->set_column_homogeneous(true);
     vbox->pack_start(*grid, false, true, 5);
     label = new Gtk::Label("Hmin:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 0, 0, 1, 1);
     HScale_Hmin.set_digits(0);
     HScale_Hmin.set_increments(1,1);
     HScale_Hmin.set_range(0,255);
     HScale_Hmin.set_value_pos(Gtk::POS_TOP);
     HScale_Hmin.set_draw_value();
     grid->attach(HScale_Hmin, 1, 0, 2, 1);
     label = new Gtk::Label("Hmax:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 3, 0, 1, 1);
     HScale_Hmax.set_digits(0);
     HScale_Hmax.set_increments(1,1);
     HScale_Hmax.set_range(0,180);
     HScale_Hmax.set_value_pos(Gtk::POS_TOP);
     HScale_Hmax.set_draw_value();
     grid->attach(HScale_Hmax, 4, 0, 2, 1);
     label = new Gtk::Label("Smin:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 0, 1, 1, 1);
     HScale_Smin.set_digits(0);
     HScale_Smin.set_increments(1,1);
     HScale_Smin.set_range(0,255);
     HScale_Smin.set_value_pos(Gtk::POS_TOP);
     HScale_Smin.set_draw_value();
     grid->attach(HScale_Smin, 1, 1, 2, 1);
     label = new Gtk::Label("Smax:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 3, 1, 1, 1);
     HScale_Smax.set_digits(0);
     HScale_Smax.set_increments(1,1);
     HScale_Smax.set_range(0,255);
     HScale_Smax.set_value_pos(Gtk::POS_TOP);
     HScale_Smax.set_draw_value();
     grid->attach(HScale_Smax,4, 1, 2, 1);
     label = new Gtk::Label("Vmin:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 0, 2, 1, 1);
     HScale_Vmin.set_digits(0);
     HScale_Vmin.set_increments(1,1);
     HScale_Vmin.set_range(0,255);
     HScale_Vmin.set_value_pos(Gtk::POS_TOP);
     HScale_Vmin.set_draw_value();
     grid->attach(HScale_Vmin, 1, 2, 2, 1);
     label = new Gtk::Label("Vmax:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 3, 2, 1, 1);
     HScale_Vmax.set_digits(0);
     HScale_Vmax.set_increments(1,1);
     HScale_Vmax.set_range(0,255);
     HScale_Vmax.set_value_pos(Gtk::POS_TOP);
     HScale_Vmax.set_draw_value();
     grid->attach(HScale_Vmax, 4, 2, 2, 1);
     label = new Gtk::Label("Erode:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 0, 3, 1, 1);
     HScale_Erode.set_digits(0);
     HScale_Erode.set_increments(1,1);
     HScale_Erode.set_range(0,50);
     HScale_Erode.set_value_pos(Gtk::POS_TOP);
     HScale_Erode.set_draw_value();
     grid->attach(HScale_Erode, 1, 3, 2, 1);
     label = new Gtk::Label("Dilate:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 3, 3, 1, 1);
     HScale_Dilate.set_digits(0);
     HScale_Dilate.set_increments(1,1);
     HScale_Dilate.set_range(0,50);
     HScale_Dilate.set_value_pos(Gtk::POS_TOP);
     HScale_Dilate.set_draw_value();
     grid->attach(HScale_Dilate, 4, 3, 2, 1);
     label = new Gtk::Label("Blur:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 0, 4, 1, 1);
     HScale_Blur.set_digits(0);
     HScale_Blur.set_increments(2,2);
     HScale_Blur.set_range(3,9);
     HScale_Blur.set_value_pos(Gtk::POS_TOP);
     HScale_Blur.set_draw_value();
     grid->attach(HScale_Blur, 1, 4, 2, 1);
     label = new Gtk::Label("Amin:");
     label->set_alignment(1.0, 1.0);
     grid->attach(*label, 3, 4, 1, 1);
     HScale_Amin.set_digits(0);
     HScale_Amin.set_increments(1,1);
     HScale_Amin.set_range(0,200);
     HScale_Amin.set_value_pos(Gtk::POS_TOP);
     HScale_Amin.set_draw_value();
     grid->attach(HScale_Amin, 4, 4, 2, 1);
     bt_HSV_calib.set_state(Gtk::STATE_INSENSITIVE);
     bt_switchMainAdv.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Hmin.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Smin.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Vmin.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Hmax.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Smax.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Vmax.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Dilate.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Erode.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Blur.set_state(Gtk::STATE_INSENSITIVE);
     HScale_Amin.set_state(Gtk::STATE_INSENSITIVE);
     bt_HSV_left.set_state(Gtk::STATE_INSENSITIVE);
     bt_HSV_right.set_state(Gtk::STATE_INSENSITIVE);
     bt_HSV_calib.signal_pressed().connect(sigc::mem_fun(*this, &VisionGUI::__event_bt_HSV_calib_pressed));
     bt_HSV_right.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::__event_bt_right_HSV_calib_clicked));
     bt_HSV_left.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::__event_bt_left_HSV_calib_clicked));
     bt_switchMainAdv.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::__event_bt_switchMainAdv_clicked));
     HScale_Hmin.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Hmin_value_changed));
     HScale_Hmax.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Hmax_value_changed));
     HScale_Smin.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Smin_value_changed));
     HScale_Smax.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Smax_value_changed));
     HScale_Vmin.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Vmin_value_changed));
     HScale_Vmax.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Vmax_value_changed));
     HScale_Erode.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Erode_value_changed));
     HScale_Dilate.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Dilate_value_changed));
     HScale_Blur.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Blur_value_changed));
     HScale_Amin.signal_value_changed().connect(sigc::mem_fun(*this, &VisionGUI::HScale_Amin_value_changed));
 }
__create_frm_split_view()
void VisionGUI::__create_frm_split_view () private
Creates Split View frame and its inner elements. Ataches interface signals (signals pressing/clicking) to events.
Definition at line 3 of file visionGUI.cpp.
References __event_rb_split_mode_clicked(), rb_original_view, and rb_split_view.
Referenced by VisionGUI().
{
     Gtk::VBox * vbox;
     Gtk::Grid * grid;
     Gtk::Label * label;
     Gtk::Frame * frame;
     vbox = new Gtk::VBox();
     grid = new Gtk::Grid();
     frame = new Gtk::Frame();
     pack_start(*frame, false, false, 5);
     frame->add(*vbox);
     vbox->pack_start(*grid, false, true, 5);
     vbox->set_halign(Gtk::ALIGN_CENTER);
     vbox->set_valign(Gtk::ALIGN_CENTER);
     frame->set_label("Split View");
     grid->set_border_width(5);
     grid->set_column_spacing(10);
     grid->set_row_spacing(5);
     label = new Gtk::Label("Select Mode: ");
     grid->attach(*label, 0, 0, 1, 1);
     rb_original_view.set_label("Original");
     grid->attach(rb_original_view, 1, 0, 1, 1);
     rb_split_view.set_label("Split");
     rb_split_view.join_group(rb_original_view);
     grid->attach(rb_split_view, 2, 0, 1, 1);
     rb_original_view.set_state(Gtk::STATE_INSENSITIVE);
     rb_split_view.set_state(Gtk::STATE_INSENSITIVE);
     rb_original_view.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::__event_rb_split_mode_clicked));
     rb_split_view.signal_clicked().connect(sigc::mem_fun(*this, &VisionGUI::__event_rb_split_mode_clicked));
 }
__event_bt_HSV_calib_pressed()
void VisionGUI::__event_bt_HSV_calib_pressed () private
Event triggered when HSV Calib button is pressed.
Switches HSV_calib_event_flag value and turns calibration parameters (non)editable
Definition at line 375 of file visionGUI.cpp.
References bt_HSV_left, bt_HSV_right, bt_switchMainAdv, HScale_Amin, HScale_Blur, HScale_Dilate, HScale_Erode, HScale_Hmax, HScale_Hmin, HScale_Smax, HScale_Smin, HScale_Vmax, HScale_Vmin, and HSV_calib_event_flag.
Referenced by __create_frm_hsv(), and selectFrame().
{
     if(HSV_calib_event_flag) {
         HSV_calib_event_flag=false;
         // VisionGUI::__event_auto_save();
         HScale_Hmin.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Smin.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Vmin.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Hmax.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Smax.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Vmax.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Dilate.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Erode.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Blur.set_state(Gtk::STATE_INSENSITIVE);
         HScale_Amin.set_state(Gtk::STATE_INSENSITIVE);
         bt_HSV_right.set_state(Gtk::STATE_INSENSITIVE);
         bt_HSV_left.set_state(Gtk::STATE_INSENSITIVE);
         bt_switchMainAdv.set_state(Gtk::STATE_INSENSITIVE);
     } else {
         HSV_calib_event_flag=true;
         HScale_Hmin.set_state(Gtk::STATE_NORMAL);
         HScale_Smin.set_state(Gtk::STATE_NORMAL);
         HScale_Vmin.set_state(Gtk::STATE_NORMAL);
         HScale_Hmax.set_state(Gtk::STATE_NORMAL);
         HScale_Smax.set_state(Gtk::STATE_NORMAL);
         HScale_Vmax.set_state(Gtk::STATE_NORMAL);
         HScale_Dilate.set_state(Gtk::STATE_NORMAL);
         HScale_Erode.set_state(Gtk::STATE_NORMAL);
         HScale_Blur.set_state(Gtk::STATE_NORMAL);
         HScale_Amin.set_state(Gtk::STATE_NORMAL);
         bt_HSV_right.set_state(Gtk::STATE_NORMAL);
         bt_HSV_left.set_state(Gtk::STATE_NORMAL);
         bt_switchMainAdv.set_state(Gtk::STATE_NORMAL);
     }
 }
__event_bt_left_HSV_calib_clicked()
void VisionGUI::__event_bt_left_HSV_calib_clicked () private
Event triggered when HSV Calib left button is pressed.
Jump to the previous calibration category and loads its parameters values
Definition at line 511 of file visionGUI.cpp.
References Vision::getAmin(), Vision::getBlur(), Vision::getDilate(), Vision::getErode(), Vision::getHue(), Vision::getSaturation(), Vision::getValue(), HScale_Amin, HScale_Blur, HScale_Dilate, HScale_Erode, HScale_Hmax, HScale_Hmin, HScale_Smax, HScale_Smin, HScale_Vmax, HScale_Vmin, HSV_label, Img_id, and vision.
Referenced by __create_frm_hsv().
{
     Img_id = Img_id-1;
     if(Img_id < 0) Img_id = 3;
     HScale_Hmin.set_value(vision->getHue(Img_id, 0));
     HScale_Hmax.set_value(vision->getHue(Img_id, 1));
     HScale_Smin.set_value(vision->getSaturation(Img_id, 0));
     HScale_Smax.set_value(vision->getSaturation(Img_id, 1));
     HScale_Vmin.set_value(vision->getValue(Img_id, 0));
     HScale_Vmax.set_value(vision->getValue(Img_id, 1));
     HScale_Dilate.set_value(vision->getDilate(Img_id));
     HScale_Erode.set_value(vision->getErode(Img_id));
     HScale_Blur.set_value(vision->getBlur(Img_id));
     HScale_Amin.set_value(vision->getAmin(Img_id));
     switch(Img_id) {
         case 0:
             HSV_label.set_text("Main");
             break;
         case 1:
             HSV_label.set_text("Green");
             break;
         case 2:
             HSV_label.set_text("Ball");
             break;
         case 3:
             HSV_label.set_text("Opp.");
             break;
         default:
             break;
     }
 }
__event_bt_right_HSV_calib_clicked()
void VisionGUI::__event_bt_right_HSV_calib_clicked () private
Event triggered when HSV Calib right button is pressed.
Jump to the next calibration category and loads its parameters values
Definition at line 465 of file visionGUI.cpp.
References Vision::getAmin(), Vision::getBlur(), Vision::getDilate(), Vision::getErode(), Vision::getHue(), Vision::getSaturation(), Vision::getValue(), HScale_Amin, HScale_Blur, HScale_Dilate, HScale_Erode, HScale_Hmax, HScale_Hmin, HScale_Smax, HScale_Smin, HScale_Vmax, HScale_Vmin, HSV_label, Img_id, and vision.
Referenced by __create_frm_hsv(), and selectFrame().
{
     Img_id = Img_id + 1;
     if(Img_id > 3) Img_id = 0;
     HScale_Hmin.set_value(vision->getHue(Img_id, 0));
     HScale_Hmax.set_value(vision->getHue(Img_id, 1));
     HScale_Smin.set_value(vision->getSaturation(Img_id, 0));
     HScale_Smax.set_value(vision->getSaturation(Img_id, 1));
     HScale_Vmin.set_value(vision->getValue(Img_id, 0));
     HScale_Vmax.set_value(vision->getValue(Img_id, 1));
     HScale_Dilate.set_value(vision->getDilate(Img_id));
     HScale_Erode.set_value(vision->getErode(Img_id));
     HScale_Blur.set_value(vision->getBlur(Img_id));
     HScale_Amin.set_value(vision->getAmin(Img_id));
     switch(Img_id) {
         case 0:
             HSV_label.set_text("Main");
             break;
         case 1:
             HSV_label.set_text("Green");
             break;
         case 2:
             HSV_label.set_text("Ball");
             break;
         case 3:
             HSV_label.set_text("Opp.");
             break;
         default:
             break;
     }
 }
__event_bt_switchMainAdv_clicked()
void VisionGUI::__event_bt_switchMainAdv_clicked () private
Event triggered when 'Main <-> Adv' button is pressed.
Switches host team and adversary calibration parameters
Definition at line 313 of file visionGUI.cpp.
References Vision::getAmin(), Vision::getBlur(), Vision::getDilate(), Vision::getErode(), Vision::getHue(), Vision::getSaturation(), Vision::getValue(), HScale_Amin, HScale_Blur, HScale_Dilate, HScale_Erode, HScale_Hmax, HScale_Hmin, HScale_Smax, HScale_Smin, HScale_Vmax, HScale_Vmin, Img_id, Vision::switchMainWithAdv(), and vision.
Referenced by __create_frm_hsv().
{
     vision->switchMainWithAdv();
     HScale_Hmin.set_value(vision->getHue(Img_id, 0));
     HScale_Hmax.set_value(vision->getHue(Img_id, 1));
     HScale_Smin.set_value(vision->getSaturation(Img_id, 0));
     HScale_Smax.set_value(vision->getSaturation(Img_id, 1));
     HScale_Vmin.set_value(vision->getValue(Img_id, 0));
     HScale_Vmax.set_value(vision->getValue(Img_id, 1));
     HScale_Amin.set_value(vision->getAmin(Img_id));
     HScale_Blur.set_value(vision->getBlur(Img_id));
     HScale_Erode.set_value(vision->getErode(Img_id));
     HScale_Dilate.set_value(vision->getDilate(Img_id));
 }
__event_rb_split_mode_clicked()
void VisionGUI::__event_rb_split_mode_clicked () private
Turns 'isSplitView' flag active when triggered when Split mode is selected.
Definition at line 41 of file visionGUI.cpp.
References isSplitView, and rb_split_view.
Referenced by __create_frm_split_view(), and selectFrame().
{
     isSplitView = rb_split_view.get_active();
 }
bt_record_video_pressed()
void VisionGUI::bt_record_video_pressed () private
Starts video recording when 'REC' button is pressed, changing its label to 'Stop', and vice-versa. If 'Video name' textfield is empty, a numeric ID value will be assigned.
Definition at line 96 of file visionGUI.cpp.
References bt_record_video, en_video_name, Vision::finishVideo(), Vision::isRecording(), Vision::startNewVideo(), vidIndex, and vision.
Referenced by __create_frm_capture().
{
     if(vision->isRecording()) {
         vision->finishVideo();
         bt_record_video.set_label("REC");
         en_video_name.set_text("");
         en_video_name.set_state(Gtk::STATE_NORMAL);
     } else {
         std::string name = en_video_name.get_text();
         bt_record_video.set_label("Stop");
         en_video_name.set_state(Gtk::STATE_INSENSITIVE);
         if(name.empty()) {
           vision->startNewVideo(std::to_string(vidIndex++));
           en_video_name.set_text(std::to_string(vidIndex));
       } else {
           vision->startNewVideo(name);
       }
   }
 }
bt_save_picture_clicked()
void VisionGUI::bt_save_picture_clicked () private
Saves the actual frame image in /media/pictures when 'save' button is clicked If 'Picture name' textfield is empty, a numeric ID value will be assigned.
Definition at line 116 of file visionGUI.cpp.
References en_picture_name, picIndex, Vision::savePicture(), and vision.
Referenced by __create_frm_capture().
{
     std::string name = en_picture_name.get_text();
     if(name.empty()) vision->savePicture(std::to_string(picIndex++));
     else vision->savePicture(name);
     en_picture_name.set_text("");
 }
getIsSplitView()
bool VisionGUI::getIsSplitView ()
Definition at line 45 of file visionGUI.cpp.
References isSplitView.
Referenced by CamCap::capture_and_show().
{
   return isSplitView;
 }
HScale_Amin_value_changed()
void VisionGUI::HScale_Amin_value_changed () private
Call Vision's setAmin method passsing Amin value as a parameter.
Definition at line 351 of file visionGUI.cpp.
References HScale_Amin, Img_id, Vision::setAmin(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setAmin(Img_id, (int) HScale_Amin.get_value());
 }
HScale_Blur_value_changed()
void VisionGUI::HScale_Blur_value_changed () private
Call Vision's setBlur method passsing Blur value as a parameter.
Definition at line 365 of file visionGUI.cpp.
References HScale_Blur, Img_id, Vision::setBlur(), and vision.
Referenced by __create_frm_hsv().
{
     if(HScale_Blur.get_value() < 3) {
         vision->setBlur(Img_id, 3);
     } else if((int) HScale_Blur.get_value() % 2 == 0){
         vision->setBlur(Img_id, (int) HScale_Blur.get_value()+1);
     } else{
         vision->setBlur(Img_id, (int)HScale_Blur.get_value());
     }
 }
HScale_Dilate_value_changed()
void VisionGUI::HScale_Dilate_value_changed () private
Call Vision's setDilate method passsing Dilate value as a parameter.
Definition at line 355 of file visionGUI.cpp.
References HScale_Dilate, Img_id, Vision::setDilate(), and vision.
Referenced by __create_frm_hsv().
{
     if(HScale_Dilate.get_value() < 0) vision->setDilate(Img_id, 0);
     else vision->setDilate(Img_id, (int) HScale_Dilate.get_value());
 }
HScale_Erode_value_changed()
void VisionGUI::HScale_Erode_value_changed () private
Call Vision's Erode method passsing Erode value as a parameter.
Definition at line 360 of file visionGUI.cpp.
References HScale_Erode, Img_id, Vision::setErode(), and vision.
Referenced by __create_frm_hsv().
{
     if(HScale_Erode.get_value() < 0) vision->setErode(Img_id, 0);
     else vision->setErode(Img_id, (int) HScale_Erode.get_value());
 }
HScale_Hmax_value_changed()
void VisionGUI::HScale_Hmax_value_changed () private
Call Vision's setHue method passsing Hmax value as a parameter.
Definition at line 339 of file visionGUI.cpp.
References HScale_Hmax, Img_id, Vision::setHue(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setHue(Img_id, 1, (int) HScale_Hmax.get_value());
 }
HScale_Hmin_value_changed()
void VisionGUI::HScale_Hmin_value_changed () private
Call Vision's setHue method passsing Hmin value as a parameter.
Definition at line 327 of file visionGUI.cpp.
References HScale_Hmin, Img_id, Vision::setHue(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setHue(Img_id, 0, (int) HScale_Hmin.get_value());
 }
HScale_Smax_value_changed()
void VisionGUI::HScale_Smax_value_changed () private
Call Vision's setSaturation method passsing Smax value as a parameter.
Definition at line 343 of file visionGUI.cpp.
References HScale_Smax, Img_id, Vision::setSaturation(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setSaturation(Img_id, 1, (int) HScale_Smax.get_value());
 }
HScale_Smin_value_changed()
void VisionGUI::HScale_Smin_value_changed () private
Call Vision's setSaturation method passsing Smin value as a parameter.
Definition at line 331 of file visionGUI.cpp.
References HScale_Smin, Img_id, Vision::setSaturation(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setSaturation(Img_id, 0, (int) HScale_Smin.get_value());
 }
HScale_Vmax_value_changed()
void VisionGUI::HScale_Vmax_value_changed () private
Call Vision's setValue method passsing Vmax value as a parameter.
Definition at line 347 of file visionGUI.cpp.
References HScale_Vmax, Img_id, Vision::setValue(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setValue(Img_id, 1, (int) HScale_Vmax.get_value());
 }
HScale_Vmin_value_changed()
void VisionGUI::HScale_Vmin_value_changed () private
Call Vision's setValue method passsing Vmin value as a parameter.
Definition at line 335 of file visionGUI.cpp.
References HScale_Vmin, Img_id, Vision::setValue(), and vision.
Referenced by __create_frm_hsv().
{
     vision->setValue(Img_id, 0, (int) HScale_Vmin.get_value());
 }
init_calib_params()
void VisionGUI::init_calib_params () private
Sets initial calibration parameter values shown at interface.
Definition at line 557 of file visionGUI.cpp.
References HScale_Amin, HScale_Hmax, HScale_Smax, HScale_Vmax, Vision::setCalibParams(), and vision.
Referenced by VisionGUI().
{
     // Inicializar variveis de calibrao
     int H[5][2] = { {0,180}, {0,180}, {0,180}, {0,180}, {0,180} };
     int S[5][2] = { {0, 255}, {0, 255}, {0, 255}, {0, 255}, {0, 255} };
     int V[5][2] = { {0, 255}, {0, 255}, {0, 255}, {0, 255}, {0, 255} };
     int B[5] {3, 3, 3, 3, 3};
     int D[5] = {0, 0, 0, 0, 0};
     int E[5] = {0, 0, 0, 0, 0};
     int Amin[5] = {150, 90, 90, 115, 50};
     // Configurar os valores iniciais de calibrao
     vision->setCalibParams(H, S, V, Amin, E, D, B);
     // Corrigir os valores mostrados na interface
     HScale_Hmax.set_value(H[0][1]);
     HScale_Smax.set_value(S[0][1]);
     HScale_Vmax.set_value(V[0][1]);
     HScale_Amin.set_value(Amin[0]);
 }
selectFrame()
void VisionGUI::selectFrame (int sector)
Definition at line 410 of file visionGUI.cpp.
References __event_bt_HSV_calib_pressed(), __event_bt_right_HSV_calib_clicked(), __event_rb_split_mode_clicked(), bt_HSV_calib, Img_id, and rb_original_view.
Referenced by CamCap::capture_and_show().
{
     switch (sector) {
         case 0:
             rb_original_view.set_active(true);
             __event_rb_split_mode_clicked();
             break;
         case 1:
             Img_id = 3;
             rb_original_view.set_active(true);
             __event_rb_split_mode_clicked();
             __event_bt_right_HSV_calib_clicked();
             if(!bt_HSV_calib.get_active()) {
                 bt_HSV_calib.set_active(true);
                 __event_bt_HSV_calib_pressed();
             }
             break;
         case 2:
             Img_id = 0;
             rb_original_view.set_active(true);
             __event_rb_split_mode_clicked();
             __event_bt_right_HSV_calib_clicked();
             if(!bt_HSV_calib.get_active()) {
                 bt_HSV_calib.set_active(true);
                 __event_bt_HSV_calib_pressed();
             }
             break;
         case 3:
             Img_id = 1;
             rb_original_view.set_active(true);
             __event_rb_split_mode_clicked();
             __event_bt_right_HSV_calib_clicked();
             if(!bt_HSV_calib.get_active()) {
                 bt_HSV_calib.set_active(true);
                 __event_bt_HSV_calib_pressed();
             }
             break;
         default:
             break;
     }
 }
setFrameSize()
void VisionGUI::setFrameSize (int inWidth, int inHeight)
Definition at line 577 of file visionGUI.cpp.
References Vision::setFrameSize(), and vision.
Referenced by CamCap::start_signal().
{
     vision->setFrameSize(inWidth, inHeight);
 }
Field Documentation
bt_HSV_calib
Gtk::ToggleButton VisionGUI::bt_HSV_calib
Definition at line 16 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and selectFrame().
bt_HSV_left
Gtk::Button VisionGUI::bt_HSV_left private
Definition at line 63 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), and __event_bt_HSV_calib_pressed().
bt_HSV_right
Gtk::Button VisionGUI::bt_HSV_right private
Definition at line 64 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), and __event_bt_HSV_calib_pressed().
bt_record_video
Gtk::ToggleButton VisionGUI::bt_record_video
Definition at line 38 of file visionGUI.hpp.
Referenced by __create_frm_capture(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), bt_record_video_pressed(), and VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked().
bt_save_picture
Gtk::Button VisionGUI::bt_save_picture
Definition at line 39 of file visionGUI.hpp.
Referenced by __create_frm_capture(), and VSSS_GUI::V4LInterface::__event_bt_start_clicked().
bt_switchMainAdv
Gtk::Button VisionGUI::bt_switchMainAdv private
Definition at line 65 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), and __event_bt_HSV_calib_pressed().
en_picture_name
Gtk::Entry VisionGUI::en_picture_name
Definition at line 40 of file visionGUI.hpp.
Referenced by __create_frm_capture(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and bt_save_picture_clicked().
en_video_name
Gtk::Entry VisionGUI::en_video_name
Definition at line 40 of file visionGUI.hpp.
Referenced by __create_frm_capture(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), bt_record_video_pressed(), and VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked().
HScale_Amin
Gtk::Scale VisionGUI::HScale_Amin
Definition at line 36 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Amin_value_changed(), init_calib_params(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Blur
Gtk::Scale VisionGUI::HScale_Blur
Definition at line 34 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Blur_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Dilate
Gtk::Scale VisionGUI::HScale_Dilate
Definition at line 31 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Dilate_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Erode
Gtk::Scale VisionGUI::HScale_Erode
Definition at line 32 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Erode_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Hmax
Gtk::Scale VisionGUI::HScale_Hmax
Definition at line 27 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Hmax_value_changed(), init_calib_params(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Hmin
Gtk::Scale VisionGUI::HScale_Hmin
Definition at line 24 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Hmin_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Smax
Gtk::Scale VisionGUI::HScale_Smax
Definition at line 28 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Smax_value_changed(), init_calib_params(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Smin
Gtk::Scale VisionGUI::HScale_Smin
Definition at line 25 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Smin_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Vmax
Gtk::Scale VisionGUI::HScale_Vmax
Definition at line 29 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Vmax_value_changed(), init_calib_params(), and VSSS_GUI::V4LInterface::update_interface_camera().
HScale_Vmin
Gtk::Scale VisionGUI::HScale_Vmin
Definition at line 26 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_HSV_calib_pressed(), __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), HScale_Vmin_value_changed(), and VSSS_GUI::V4LInterface::update_interface_camera().
HSV_calib_event_flag
bool VisionGUI::HSV_calib_event_flag
Definition at line 20 of file visionGUI.hpp.
Referenced by __event_bt_HSV_calib_pressed(), and CamCap::capture_and_show().
HSV_label
Gtk::Label VisionGUI::HSV_label private
Definition at line 62 of file visionGUI.hpp.
Referenced by __create_frm_hsv(), __event_bt_left_HSV_calib_clicked(), and __event_bt_right_HSV_calib_clicked().
Img_id
int VisionGUI::Img_id
Definition at line 18 of file visionGUI.hpp.
Referenced by __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), CamCap::capture_and_show(), HScale_Amin_value_changed(), HScale_Blur_value_changed(), HScale_Dilate_value_changed(), HScale_Erode_value_changed(), HScale_Hmax_value_changed(), HScale_Hmin_value_changed(), HScale_Smax_value_changed(), HScale_Smin_value_changed(), HScale_Vmax_value_changed(), HScale_Vmin_value_changed(), selectFrame(), and VSSS_GUI::V4LInterface::update_interface_camera().
isSplitView
bool VisionGUI::isSplitView private
Definition at line 56 of file visionGUI.hpp.
Referenced by __event_rb_split_mode_clicked(), and getIsSplitView().
picIndex
int VisionGUI::picIndex private
Definition at line 59 of file visionGUI.hpp.
Referenced by bt_save_picture_clicked().
rb_mode_GMM
Gtk::RadioButton VisionGUI::rb_mode_GMM
Definition at line 43 of file visionGUI.hpp.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked().
rb_mode_HSV
Gtk::RadioButton VisionGUI::rb_mode_HSV
Definition at line 43 of file visionGUI.hpp.
Referenced by VSSS_GUI::V4LInterface::__event_bt_start_clicked().
rb_original_view
Gtk::RadioButton VisionGUI::rb_original_view
Definition at line 22 of file visionGUI.hpp.
Referenced by __create_frm_split_view(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and selectFrame().
rb_split_view
Gtk::RadioButton VisionGUI::rb_split_view
Definition at line 22 of file visionGUI.hpp.
Referenced by __create_frm_split_view(), VSSS_GUI::V4LInterface::__event_bt_start_clicked(), and __event_rb_split_mode_clicked().
vidIndex
int VisionGUI::vidIndex private
Definition at line 59 of file visionGUI.hpp.
Referenced by bt_record_video_pressed().
vision
Vision* VisionGUI::vision
Definition at line 15 of file visionGUI.hpp.
Referenced by __event_bt_left_HSV_calib_clicked(), __event_bt_right_HSV_calib_clicked(), __event_bt_switchMainAdv_clicked(), bt_record_video_pressed(), bt_save_picture_clicked(), CamCap::capture_and_show(), VSSS_GUI::V4LInterface::event_start_game_bt_signal_clicked(), HScale_Amin_value_changed(), HScale_Blur_value_changed(), HScale_Dilate_value_changed(), HScale_Erode_value_changed(), HScale_Hmax_value_changed(), HScale_Hmin_value_changed(), HScale_Smax_value_changed(), HScale_Smin_value_changed(), HScale_Vmax_value_changed(), HScale_Vmin_value_changed(), init_calib_params(), jsonSaveManager::load_camera(), jsonSaveManager::save_camera(), setFrameSize(), CamCap::start_signal(), VSSS_GUI::V4LInterface::update_interface_camera(), CamCap::updateAllPositions(), VisionGUI(), and ~VisionGUI().
The documentation for this class was generated from the following files:
src/gui/visionGUI.hpp
src/gui/visionGUI.cpp