VSSS-INF: v4ldev Class Reference
v4ldev Class Reference
#include <v4ldev.hpp>
Public Member Functions
v4ldev ()
~v4ldev ()
bool open_device (const char *devname, bool emulate_fmt)
bool query_capability (struct v4l2_capability *cap)
bool get_input_index (int *input)
bool get_input (struct v4l2_input *input)
bool get_format (struct v4l2_format *fmt, enum v4l2_buf_type type)
bool get_standard_id (v4l2_std_id *std_id)
bool get_standard (struct v4l2_standard *standard)
bool get_stream_parameter (struct v4l2_streamparm *streamparm)
bool get_stream_parameter (struct v4l2_streamparm *streamparm, __u32 type)
bool get_control (struct v4l2_control *ctrl)
bool get_control (struct v4l2_control *ctrl, unsigned int ctrl_id)
bool query_buffer (struct v4l2_buffer *buffer)
bool query_buffer (struct v4l2_buffer *buf, enum v4l2_buf_type type, enum v4l2_memory memory, unsigned int index)
bool enqueue_buff (struct v4l2_buffer *vbuf)
bool enqueue_buff (struct v4l2_buffer *vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, int index)
bool streamon (enum v4l2_buf_type type)
bool streamoff (enum v4l2_buf_type type)
bool dequeue_buff (struct v4l2_buffer *vbuf)
bool dequeue_buff (struct v4l2_buffer *vbuf, unsigned int buf_type, unsigned int memory, bool *again)
bool query_control (struct v4l2_queryctrl *qctrl)
bool query_control_menu (struct v4l2_querymenu *qmenu)
bool request_buffers (struct v4l2_requestbuffers *req_buff)
bool request_buffers (struct v4l2_requestbuffers *req_buff, int nbuffers, enum v4l2_memory memory, enum v4l2_buf_type type)
Private Member Functions
int xioctl (int fd, int request, void *arg)
Private Attributes
int fd
bool emulate_format
Detailed Description
Definition at line 22 of file v4ldev.hpp.
Constructor & Destructor Documentation
v4ldev()
v4ldev::v4ldev ()
Definition at line 11 of file v4ldev.cpp.
 : fd(0), emulate_format(false) {};
~v4ldev()
v4ldev::~v4ldev ()
Definition at line 13 of file v4ldev.cpp.
 {};
Member Function Documentation
dequeue_buff() [1/2]
bool v4ldev::dequeue_buff (struct v4l2_buffer * vbuf)
Definition at line 143 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by dequeue_buff().
{
     return xioctl(fd, VIDIOC_DQBUF, vbuf) >= 0;
 }
dequeue_buff() [2/2]
bool v4ldev::dequeue_buff (struct v4l2_buffer * vbuf, unsigned int buf_type, unsigned int memory, bool * again)
Definition at line 147 of file v4ldev.cpp.
References dequeue_buff().
{
     memset(vbuf, 0, sizeof(struct v4l2_buffer));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     int r = dequeue_buff(vbuf);
     // if the buffer is not avaliable, try again.
     *again = (r < 0) && (errno == EAGAIN);
     return (r >= 0) || (*again);
 }
enqueue_buff() [1/2]
bool v4ldev::enqueue_buff (struct v4l2_buffer * vbuf)
Definition at line 122 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by enqueue_buff().
{
     return xioctl(fd, VIDIOC_QBUF, vbuf) >= 0;
 }
enqueue_buff() [2/2]
bool v4ldev::enqueue_buff (struct v4l2_buffer * vbuf, enum v4l2_buf_type buf_type, enum v4l2_memory memory, int index)
Definition at line 126 of file v4ldev.cpp.
References enqueue_buff().
{
     memset(vbuf, 0, sizeof(*vbuf));
     vbuf->type = buf_type;
     vbuf->memory = memory;
     vbuf->index = index;
     return enqueue_buff(vbuf);
 }
get_control() [1/2]
bool v4ldev::get_control (struct v4l2_control * ctrl)
Definition at line 95 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by get_control().
{
     return xioctl(fd, VIDIOC_G_CTRL, ctrl) >= 0;
 }
get_control() [2/2]
bool v4ldev::get_control (struct v4l2_control * ctrl, unsigned int ctrl_id)
Definition at line 99 of file v4ldev.cpp.
References get_control().
{
     ctrl->id = ctrl_id;
     return get_control(ctrl);
 }
get_format()
bool v4ldev::get_format (struct v4l2_format * fmt, enum v4l2_buf_type type)
Definition at line 61 of file v4ldev.cpp.
References fd, and xioctl().
{
     fmt->type = type;
     return xioctl(fd, VIDIOC_G_FMT, fmt) >= 0;
 }
get_input()
bool v4ldev::get_input (struct v4l2_input * input)
Definition at line 53 of file v4ldev.cpp.
References fd, get_input_index(), and xioctl().
{
     int index;
     if (!get_input_index(&index)) return false;
     input->index = index;
     return xioctl(fd, VIDIOC_ENUMINPUT, input) >= 0;
 }
get_input_index()
bool v4ldev::get_input_index (int * input)
Definition at line 49 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by get_input().
{
     return xioctl(fd, VIDIOC_G_INPUT, input) >= 0;
 }
get_standard()
bool v4ldev::get_standard (struct v4l2_standard * standard)
Definition at line 70 of file v4ldev.cpp.
References fd, get_standard_id(), and xioctl().
{
     v4l2_std_id std_id;
     if (!get_standard_id(&std_id)) return false;
     standard->id = std_id;
     for (__u32 index = 0;; ++index) {
         standard->index = index;
         if (standard->id == std_id) return true;
         if (!xioctl(fd, VIDIOC_ENUMSTD, standard)) break;
     }
     return false;
 }
get_standard_id()
bool v4ldev::get_standard_id (v4l2_std_id * std_id)
Definition at line 66 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by get_standard().
{
     return xioctl(fd, VIDIOC_G_STD, std_id) >= 0;
 }
get_stream_parameter() [1/2]
bool v4ldev::get_stream_parameter (struct v4l2_streamparm * streamparm)
Definition at line 86 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by get_stream_parameter().
{
     return xioctl(fd, VIDIOC_G_PARM, streamparm) >= 0;
 }
get_stream_parameter() [2/2]
bool v4ldev::get_stream_parameter (struct v4l2_streamparm * streamparm, __u32 type)
Definition at line 90 of file v4ldev.cpp.
References get_stream_parameter().
{
     streamparm->type = type;
     return get_stream_parameter(streamparm);
 }
open_device()
bool v4ldev::open_device (const char * devname, bool emulate_fmt)
Definition at line 15 of file v4ldev.cpp.
References emulate_format, fd, and query_capability().
{
     fd = open(devname, O_RDWR);
     emulate_format = emulate_fmt;
     if(fd < 0) {
         std::cout << "Can not open " << devname << "device!" << std::endl;
         return false;
     }
     if(emulate_fmt) {
         int fd2 = v4l2_fd_open(fd, V4L2_ENABLE_ENUM_FMT_EMULATION);
         if(fd2 < 0) {
             std::cout << "Cannot use libv4l2 wrapper for " << devname << "!" << std::endl;
             emulate_fmt = false;
         }
     }
     struct v4l2_capability cap;
     if(!query_capability(&cap)) {
         std::cout << devname << " is not a V4L2 device!" << std::endl;
         if(emulate_fmt) v4l2_close(fd);
         else close(fd);
         return false;
     }
     return true;
 }
query_buffer() [1/2]
bool v4ldev::query_buffer (struct v4l2_buffer * buffer)
Definition at line 104 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by query_buffer().
{
     int r = xioctl(fd, VIDIOC_QUERYBUF, buffer);
     if (r >= 0) return true;
     perror("VIDIOC_QUERYBUF");
     return false;
 }
query_buffer() [2/2]
bool v4ldev::query_buffer (struct v4l2_buffer * buf, enum v4l2_buf_type type, enum v4l2_memory memory, unsigned int index)
Definition at line 114 of file v4ldev.cpp.
References query_buffer().
{
     buf->type = type;
     buf->memory = memory;
     buf->index = index;
     return query_buffer(buf);
 }
query_capability()
bool v4ldev::query_capability (struct v4l2_capability * cap)
Definition at line 45 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by open_device().
{
     return xioctl(fd, VIDIOC_QUERYCAP, cap) >= 0;
 }
query_control()
bool v4ldev::query_control (struct v4l2_queryctrl * qctrl)
Definition at line 159 of file v4ldev.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_QUERYCTRL, qctrl) >= 0;
 }
query_control_menu()
bool v4ldev::query_control_menu (struct v4l2_querymenu * qmenu)
Definition at line 163 of file v4ldev.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_QUERYMENU, qmenu) >= 0;
 }
request_buffers() [1/2]
bool v4ldev::request_buffers (struct v4l2_requestbuffers * req_buff)
Definition at line 167 of file v4ldev.cpp.
References fd, and xioctl().
Referenced by request_buffers().
{
     return xioctl(fd, VIDIOC_REQBUFS, req_buff) >= 0;
 }
request_buffers() [2/2]
bool v4ldev::request_buffers (struct v4l2_requestbuffers * req_buff, int nbuffers, enum v4l2_memory memory, enum v4l2_buf_type type)
Definition at line 171 of file v4ldev.cpp.
References request_buffers().
{
     req_buff->reserved[0] = 0;
     req_buff->reserved[1] = 0;
     req_buff->count = nbuffers;
     req_buff->memory = memory;
     req_buff->type = type;
     return request_buffers(req_buff);
 }
streamoff()
bool v4ldev::streamoff (enum v4l2_buf_type type)
Definition at line 139 of file v4ldev.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_STREAMOFF, &type) >= 0;
 }
streamon()
bool v4ldev::streamon (enum v4l2_buf_type type)
Definition at line 135 of file v4ldev.cpp.
References fd, and xioctl().
{
     return xioctl(fd, VIDIOC_STREAMON, &type) >= 0;
 }
xioctl()
int v4ldev::xioctl (int fd, int request, void * arg) private
Definition at line 3 of file v4ldev.cpp.
References emulate_format.
Referenced by dequeue_buff(), enqueue_buff(), get_control(), get_format(), get_input(), get_input_index(), get_standard(), get_standard_id(), get_stream_parameter(), query_buffer(), query_capability(), query_control(), query_control_menu(), request_buffers(), streamoff(), and streamon().
{
     int r;
     if (emulate_format) r = v4l2_ioctl(fd, request, arg);
     else r = ioctl(fd, request, arg);
     return r;
 }
Field Documentation
emulate_format
bool v4ldev::emulate_format private
Definition at line 24 of file v4ldev.hpp.
Referenced by open_device(), and xioctl().
fd
int v4ldev::fd private
Definition at line 23 of file v4ldev.hpp.
Referenced by dequeue_buff(), enqueue_buff(), get_control(), get_format(), get_input(), get_input_index(), get_standard(), get_standard_id(), get_stream_parameter(), open_device(), query_buffer(), query_capability(), query_control(), query_control_menu(), request_buffers(), streamoff(), and streamon().
The documentation for this class was generated from the following files:
src/capture/v4ldev.hpp
src/capture/v4ldev.cpp