VSSS-INF: Debug Namespace Reference
Debug Namespace Reference
Functions
void log (const char *file_caller, const int line_caller, const char *function_caller, const short level, const string &msg)
void _set_debug_level (const int level)
bool _set_output_file (const string &file_name)
string _get_class (const string &file)
Variables
static int _debug_level
static bool _debug_level_set
static bool _write_enabled
static ofstream _debug_output
static ofstream _terminal_output
Function Documentation
_get_class()
string Debug::_get_class (const string & file) inline
Get File Name from a Path with or without extension
Parameters
file Full path to the given file
Returns
string The file's name without extension.
Definition at line 117 of file debug.hpp.
Referenced by log().
{
         // Create a Path object from File Path
         filesys::path pathObj(file);
         if(pathObj.has_stem()) {
             // return the stem (file name without extension) from path object
             return pathObj.stem().string();
         }
         // return the file name with extension from path object
         return pathObj.filename().string();
     }
_set_debug_level()
void Debug::_set_debug_level (const int level) inline
Sets the verbosity of this debug script.
Parameters
level 0 = log, 1 = success, 2 = warning, 3 = error, 4 = fatal error, 5 = no messages
Definition at line 77 of file debug.hpp.
{
         if(_debug_level_set) return;
         stringstream color;
         _debug_level = level;
         _debug_level_set = true;
         if(level > 4) return;
         cout << "\033[0;37mDebug will show only ";
         switch(level) {
             case 0: // log
                 color << "log, ";
             case 1: // success
                 color << "success, ";
             case 2: // warning
                 color << "warning, ";
             case 3: // error
                 color << "error and ";
             case 4: // fatal
                 color << "fatal error ";
         }
         cout << color.str() << "messages.\033[0m" << endl << endl;
     }
_set_output_file()
bool Debug::_set_output_file (const string & file_name) inline
Tries to open a given file name as our debug output and redirects the standard output to this file
Parameters
file_name Name of the output file to be opened
Returns
bool True on success, False on error.
Definition at line 104 of file debug.hpp.
References log().
{
         if(_write_enabled) return false;
         _terminal_output.open("/dev/tty", std::ios_base::out);
         if(!_terminal_output.is_open() || freopen(file_name.c_str(),"w",stdout) == NULL) {
             _write_enabled = false;
             log(__FILE__, __LINE__, __FUNCTION__, (short)3, "Debug log can't work properly. Some features will be disabled.");
             return false;
         }
         _write_enabled = true;
         return true;
     }
log()
void Debug::log (const char * file_caller, const int line_caller, const char * function_caller, const short level, const string & msg) inline
Logs a string in a fancy way
Parameters
file_caller The name of the file where this function was called
line_caller The line of the file where this function was called
function_caller The name of the function where this one was called
level The priority level (used for verbosity) of the received message
msg The message to be printed
Definition at line 129 of file debug.hpp.
References _get_class().
Referenced by _set_output_file().
{
         string class_caller = _get_class(file_caller);
         string color, details;
         stringstream output_message;
         switch(level) {
             case 0: // log
                 color = "\033[0;37m(log) \t\033[1;37m";
             break;
             case 1: // success
                 color = "\033[0;32m(success) \t\033[1;32m";
             break;
             case 2: // warning
                 color = "\033[0;33m(warning) \t\033[1;33m";
             break;
             case 3: // error
                 color = "\033[0;31m(error) \t\033[1;31m";
             break;
             case 4: // fatal
                 color = "\033[1;31m(fatal) \t\033[41m\033[1;37m";
             break;
         }
         details = "\033[0m[" + class_caller + " -> " + function_caller + " (" + to_string(line_caller) + ")]: ";
         if(_debug_level == 0)
             output_message << details;
         if(string(msg).size() > 0)
             output_message << color << msg;
         output_message << "\033[0m" << endl;
         if(level >= _debug_level) {
             _terminal_output << output_message.str();
             _terminal_output.flush();
         }
         if(_write_enabled) {
             cout << details << output_message.str();
             cout.flush();
         }
     }
Variable Documentation
_debug_level
int Debug::_debug_level static
Definition at line 40 of file debug.hpp.
_debug_level_set
bool Debug::_debug_level_set static
Definition at line 41 of file debug.hpp.
_debug_output
ofstream Debug::_debug_output static
Definition at line 43 of file debug.hpp.
_terminal_output
ofstream Debug::_terminal_output static
Definition at line 44 of file debug.hpp.
_write_enabled
bool Debug::_write_enabled static
Definition at line 42 of file debug.hpp.